### ISSUE TITLE
Ability to disable object cache completely

### ISSUE THREAD

**Issue by matihost** [operator-framework/operator-sdk#1051]
Ansible base operators essentially runs watch playbook/role:
- when CR object changes (oc apply)
- when objects created by CR invocation are removed (and changed?)
depending on https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/advanced_options.md#watches-file-options settings

However when CR object is deleted  - the playbook is not run and object created by CR invocation is removed.

Essentially it is impossible to run some cleaning logic upon object deletion.

Proposal:
Inject some additional variable to Ansible play/role indicating whether CR is created/configured/deleted

**Comment by shawn-hurley** [comment]
@matihost 

This is possible with an undocumented feature that should have had docs around it. Sorry.

This is called a finalizer. You can add it per GVK in you watches file. example
```
- ....gvk and playbook
  finalizer:
    name: finalizer.myappsg.io #name of the finalizer.
    role/playbook: /path/to/this # this is the playbook or role to run when deleting. This is optional if vars are defined
    vars: # this is optional if a role/playbook is defined. 
      "ansible_var_to_denote_removal": True
       ......
```
This needs to be documented much better but is this basically what you're looking for?
