### ISSUE TITLE
Writing CSV from existing operator

### ISSUE THREAD

**Issue by leseb** [operator-framework/operator-sdk#1091]
## How to write CSV from an existing operator?

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

I'm currently trying to implement the Rook (https://rook.io) orchestrator as a community operator. We have existing files for the operator itself and the cluster (CRD) we want to deploy.

## Question

So my question is, what's the correct approach to build a CSV with `operator-sdk`? I've looked around but I haven't found an explicit documentation for this.

**What did you do?**

This is what I've done so far:

* decouple my operator and cluster files into different files such as `role.yaml`, `role_binding.yaml`, `operator.yaml`, `service_account.yaml`. I ended up with the following:

```
.
├── deploy
│   ├── crds
│   │   ├── ceph_cr.yaml
│   │   ├── ceph_crd.yaml
│   │   ├── rookcephblockpools.crd.yaml
│   │   ├── rookcephfilesystem.crd.yaml
│   │   ├── rookcephnfses.crd.yaml
│   │   ├── rookcephobjectstores.crd.yaml
│   │   ├── rookcephobjectstoreusers.crd.yaml
│   │   ├── rookoperator.crd.yaml
│   │   └── rookvolumes.crd.yaml
│   ├── operator.yaml
│   ├── role.yaml
│   ├── role_binding.yaml
│   └── service_account.yaml
```

Then I ran:

```
$ operator-sdk olm-catalog gen-csv --csv-version 0.0.1
INFO[0000] Generating CSV manifest version 0.0.1        
INFO[0000] Fill in the following required fields in file deploy/olm-catalog/rook.csv.yaml:
        spec.keywords
        spec.maintainers
        spec.provider
        spec.labels 
INFO[0000] Create deploy/olm-catalog/rook.csv.yaml      
INFO[0000] Create deploy/olm-catalog/_generated.concat_crd.yaml 
```

Is this the correct approach?

**What did you expect to see?**
A complete `rook.csv.yaml` file.

**What did you see instead? Under which circumstances?**

Somehow I have the impression that the `rook.csv.yaml` misses a couple of things such as some parameters from my `ceph_cr.yaml` (which represents the definition of my Ceph cluster).

Thanks in advance for your help.

**Comment by TimMoran** [comment]
Hey,

Have you seen [this doc](https://docs.google.com/document/d/1TMPXk9NqkK8Dhsc1PiF-Z-DiVn19LNBk28d_hLcujoA/edit#heading=h.iaq2jsfvvf5c)? 

That doc is incomplete but I did find [this one](https://docs.google.com/document/d/1mC7vwBIzDEiEn356WJye9cAsPBU4FZqoK3n29zkjEvQ/edit?ts=5c45d19d) that looks to have a little more content. Please let me know if this is sufficient.

**Comment by estroz** [comment]
@leseb check out this [design doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/design/milestone-0.2.0/csv-generation.md) detailing the SDK's CSV scaffold implementation. If you don't find what you're looking for there, feel free to ask specific questions here!

**Comment by leseb** [comment]
@estroz thanks for your help, glad to see the approach is correct. Also, the design doc was useful.
Here's what I've got so far:

```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  creationTimestamp: null
  name: rook.v0.0.1
  namespace: placeholder
  annotations:
    tectonic-visibility: ocs
    alm-examples: |-
      [
        {
          "apiVersion": "ceph.rook.io/v1",
          "kind": "CephCluster",
          "metadata": {
            "name": "my-rook-ceph"
            "namespace": "rook-ceph"
          },
          "spec": {
            "cephVersion": {
              "image": "ceph/daemon-base:latest-master"
            },
            "dataDirHostPath": "/var/lib/rook",
            "mon": {
              "count": "3"
            },
            "dashboard": {
              "enabled": true
            },
            "network": {
              "hostNetwork": false
            },
            "rbdMirroring": {
              "workers": "0"
            },
            "storage": {
              "useAllNodes": true
              "useAllDevices": true
            },
          }
        },
      ]
spec:
  displayName: rook
  description: |
      Rook: Storage Orchestration for Kubernetes

      Rook runs as a cloud-native service for optimal integration with applications in need of storage, and handles the heavy-lifting behind the scenes such as provisioning and management.      ## Before Your Start
      Rook orchestrates battle-tested open-source storage technologies including Ceph, which has years of production deployments and runs some of the worlds largest clusters.
      Rook is open source software released under the Apache 2.0 license. Rook has an active developer and user community.

  keywords: ['rook', 'ceph', 'storage', 'object storage', 'open source']
  version: 0.0.1
  maturity: alpha
  maintainers:
  - name: Red Hat, Inc.
    email: customerservice@redhat.com
  provider:
    name: Red Hat, Inc.
  labels:
    alm-owner-etcd: etcdoperator
    operated-by: rookoperator
  selector:
    matchLabels:
      alm-owner-etcd: etcdoperator
      operated-by: rookoperator
  links:
  - name: Blog
    url: https://blog.rook.io
  - name: Documentation
    url: https://rook.github.io/docs/rook/master/
  - name: rook Operator Source Code
    url: https://github.com/rook/rook/tree/master/pkg/operator/ceph

  icon:
  - base64data: #TODO
    mediatype: image/png
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: CephCluster
      name: cephclusters.ceph.rook.io
      version: v1
      displayName: Ceph Cluster
      description: Represents a Ceph cluster.
      # resources:
      #   - kind: Service
      #     version: v1
      #   - kind: Pod
      #     version: v1
      # specDescriptors:
      #   - description: The desired number of member Pods for the etcd cluster.
      #     displayName: Size
      #     path: size
      #     x-descriptors:
      #       - 'urn:alm:descriptor:com.tectonic.ui:podCount'
    - kind: CephBlockPool
      name: cephblockpools.ceph.rook.io
      version: v1
      displayName: Ceph Block Pool
      description: Represents a Ceph Block Pool.
    - kind: CephFilesystem
      name: cephfilesystems.ceph.rook.io
      version: v1
      displayName: Ceph Filesystem
      description: Represents a Ceph Filesystem.
    - kind: CephNFS
      name: cephnfses.ceph.rook.io
      version: v1
      displayName: Ceph NFS
      description: Represents a Ceph NFS interface.
    - kind: CephObjectStore
      name: cephobjectstores.ceph.rook.io
      version: v1
      displayName: Ceph Object Store
      description: Represents a Ceph Object Store.
    - kind: CephObjectStoreUser
      name: cephobjectstoreusers.ceph.rook.io
      version: v1
      displayName: Ceph Object Store User
      description: Represents a Ceph Object Store User.
    - kind: Volume
      name: volumes.rook.io
      version: v1alpha2
      displayName: Ceph Volume
      description: Represents a Ceph volume.
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: false
  install:
    spec:
      clusterPermissions:
      # BEGIN: to run on OC
      - rules:
        - verbs:
          - use
          apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          resourceNames:
          - privileged
        serviceAccountName:
          - rook-ceph-system
          - rook-ceph-mgr
          - default
          - rook-ceph-osd
          # not sure how to reflect the namespace here, our sc was written like:
            # - system:serviceaccount:rook-ceph-system:rook-ceph-system
            # - system:serviceaccount:rook-ceph:default
            # - system:serviceaccount:rook-ceph:rook-ceph-mgr
            # - system:serviceaccount:rook-ceph:rook-ceph-osd
      # END: to run on OC
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/log
          - services
          - configmaps
          verbs:
          - get
          - list
          - watch
          - patch
          - create
          - update
          - delete
        - apiGroups:
          - extensions
          resources:
          - deployments
          - daemonsets
          - replicasets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        serviceAccountName: rook-ceph-cluster-mgmt
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - nodes
          - nodes/proxy
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          - persistentvolumes
          - persistentvolumeclaims
          - endpoints
          verbs:
          - get
          - list
          - watch
          - patch
          - create
          - update
          - delete
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - ceph.rook.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - rook.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: rook-ceph-global
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - nodes
          - nodes/proxy
          verbs:
          - get
          - list
          - watch
        serviceAccountName: rook-ceph-mgr-cluster
      deployments:
      - name: rook-ceph-operator
        spec:
          replicas: 1
          selector: null
          strategy: {}
          template:
            metadata:
              creationTimestamp: null
              labels:
                app: rook-ceph-operator
            spec:
              containers:
              - args:
                - ceph
                - operator
                env:
                - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
                  value: "false"
                - name: ROOK_LOG_LEVEL
                  value: INFO
                - name: ROOK_MON_HEALTHCHECK_INTERVAL
                  value: 45s
                - name: ROOK_MON_OUT_TIMEOUT
                  value: 300s
                - name: ROOK_DISCOVER_DEVICES_INTERVAL
                  value: 60m
                - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
                  value: "false"
                - name: ROOK_ENABLE_SELINUX_RELABELING
                  value: "true"
                - name: ROOK_ENABLE_FSGROUP
                  value: "true"
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: rook/ceph:master
                name: rook-ceph-operator
                resources: {}
                volumeMounts:
                - mountPath: /var/lib/rook
                  name: rook-config
                - mountPath: /etc/ceph
                  name: default-config-dir
              serviceAccountName: rook-ceph-system
              volumes:
              - emptyDir: {}
                name: rook-config
              - emptyDir: {}
                name: default-config-dir
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - configmaps
          verbs:
          - get
          - list
          - watch
          - patch
          - create
          - update
          - delete
        - apiGroups:
          - extensions
          resources:
          - daemonsets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        serviceAccountName: rook-ceph-system
    strategy: deployment
```

My `ceph_cr.yaml`:

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/daemon-base:latest-master
    allowUnsupported: true
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  resources:
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: false
    deviceFilter:
    location:
    config:
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
```

My `_generated.concat_crd.yaml`:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephclusters.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephCluster
    listKind: CephClusterList
    plural: cephclusters
    singular: cephcluster
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cephVersion:
              properties:
                allowUnsupported:
                  type: boolean
                image:
                  type: string
                name:
                  pattern: ^(luminous|mimic|nautilus)$
                  type: string
            dashboard:
              properties:
                enabled:
                  type: boolean
                urlPrefix:
                  type: string
                port:
                  type: integer
            dataDirHostPath:
              pattern: ^/(\S+)
              type: string
            mon:
              properties:
                allowMultiplePerNode:
                  type: boolean
                count:
                  maximum: 9
                  minimum: 1
                  type: integer
              required:
              - count
            network:
              properties:
                hostNetwork:
                  type: boolean
            storage:
              properties:
                nodes:
                  items: {}
                  type: array
                useAllDevices: {}
                useAllNodes:
                  type: boolean
          required:
          - mon
  additionalPrinterColumns:
    - name: DataDirHostPath
      type: string
      description: Directory used on the K8s nodes
      JSONPath: .spec.dataDirHostPath
    - name: MonCount
      type: string
      description: Number of MONs
      JSONPath: .spec.mon.count
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: State
      type: string
      description: Current State
      JSONPath: .status.state

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephblockpools.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephBlockPool
    listKind: CephBlockPoolList
    plural: cephblockpools
    singular: cephblockpool
  scope: Namespaced
  version: v1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephfilesystems.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephFilesystem
    listKind: CephFilesystemList
    plural: cephfilesystems
    singular: cephfilesystem
  scope: Namespaced
  version: v1
  additionalPrinterColumns:
    - name: MdsCount
      type: string
      description: Number of MDSs
      JSONPath: .spec.metadataServer.activeCount
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephnfses.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephNFS
    listKind: CephNFSList
    plural: cephnfses
    singular: cephnfs
    shortNames:
    - nfs
  scope: Namespaced
  version: v1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephobjectstores.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephObjectStore
    listKind: CephObjectStoreList
    plural: cephobjectstores
    singular: cephobjectstore
  scope: Namespaced
  version: v1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephobjectstoreusers.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephObjectStoreUser
    listKind: CephObjectStoreUserList
    plural: cephobjectstoreusers
    singular: cephobjectstoreuser
  scope: Namespaced
  version: v1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumes.rook.io
spec:
  group: rook.io
  names:
    kind: Volume
    listKind: VolumeList
    plural: volumes
    singular: volume
    shortNames:
    - rv
  scope: Namespaced
  version: v1alpha2
```

However when I try to validate it I get the following error:

```
$ operator-sdk scorecard --cr-manifest deploy/crds/ceph_cr.yaml  --csv-path deploy/olm-catalog/rook.csv.yaml --verbose
WARN[0000] Could not load config file; using flags      
Error: failed to create namespaced resources: failed to convert object to deployment: conversion of runtime object to deployment failed (resulting runtime object not deployment type)
```

Looking rapidly at the `operator-sdk` code it seems that it was unable to decode the `Deployment` section properly?

Any pointers would be appreciated, thanks.
