### ISSUE TITLE
Failed with "the server could not find the requested resource"

### ISSUE THREAD

**Issue by ladmitry** [operator-framework/operator-sdk#1124]
## Bug Report

**What did we do?**
Trying to deploy custom resource via the operator:
Facing the issue: _**the server could not find the requested resource**_

**What we expect:**
Below is the stdout log from the operator deployed on **Openshift 3.11**:
`
2019-02-21T13:55:19.173Z	INFO	logging_event_handler	[playbook task]	{"name": "example-full", "namespace": "redis-cluster", "gvk": "db.mysite.com/v1alpha1, Kind=RedisCluster", "event_type": "playbook_on_task_start", "job": "3033838985510594553", "EventData.Name": "Gathering Facts"}
`

**What we see instead:**
The same CRD, the same role, service account, permissions etc. on **Openshift 3.10**:
`
{"level":"error","ts":1550756524.2727947,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"rediscluster-controller","request":"redis-cluster/example-full","error":"the server could not find the requested resource","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
`

**Environment**
* operator-sdk version: 0.3.0, 0.4.1, 0.5.0
* openshift v3.10.0+fd501dd-48 *
* kubernetes v1.10.0+b81c8f8 *
* operator code is written on: Ansible *

**Comment by shawn-hurley** [comment]
Can you please paste your CRD here. 

The ansible operator needs to use the status subresource which requires k8s 1.10 or higher, you get the same error when the status subresource does not exist, and I am pretty sure this is the problem.

**Comment by ladmitry** [comment]
Sure, here is CRD:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redisclusters.db.mysite.com
spec:
  group: db.mysite.com
  names:
    kind: RedisCluster
    listKind: RedisClusterList
    plural: redisclusterses
    singular: rediscluster
    shortNames:
    - rcl
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
```

**Comment by shawn-hurley** [comment]
@ladmitry I think that 3.11 does this for you so for 3.10 I think you need to do this extra step: https://docs.openshift.com/container-platform/3.10/admin_guide/custom_resource_definitions.html#creating-aggregated-cluster-role-crd_admin-guide-custom-resources

**Comment by ladmitry** [comment]
Unfortunately, it doesn't work.
We've created the ClusterRoles, but the error is still in place and the cause is somewhere else.
Below is the ClusterRole we created. Besides, we are namespace-scoped, not cluster-scoped. So it seems it's not a solution.

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-redisclusters-admin-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["db.mysite.com"]
  resources: ["redisclusters"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-redisclusters-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["db.mysite.com"]
  resources: ["redisclusters"]
  verbs: ["get", "list", "watch"]
```
