### ISSUE TITLE
Generate k8s command generates openAPIV3Schema where every field is required

### ISSUE THREAD

**Issue by baluchicken** [operator-framework/operator-sdk#1137]
## Bug Report

**What did you do?**
Generated a new api with: `operator-sdk add api`
Modified generated types skeleton.
Used the `operator-sdk generate k8s`

**What did you expect to see?**
Generate a proper openAPIV3Schema where only those fields are required which are annotated with
`json:"foo,required"`

**What did you see instead? Under which circumstances?**
All my fields are marked as required, in the generated `zz_generated_openapi.go, *_crd.yaml`

**Environment**
* operator-sdk version: 0.5.0

* Kubernetes version information:
1.13

* Are you writing your operator in ansible, helm, or go?
go

**Comment by joelanford** [comment]
@baluchicken To mark a field as optional, you need to use either the `+optional` annotation or the json `omitempty` tag (or both).

```go
// MyAppSpec defines the desired state of MyApp
// +k8s:openapi-gen=true
type MyAppSpec struct {
        // +optional
        FooOptional string `json:"fooOptional,omitempty"`
        FooRequired string `json:"fooRequired"`
}

**Comment by baluchicken** [comment]
@joelanford Thanks for the quick reply, I tried both, unfortunately it does not help.

**Comment by joelanford** [comment]
@baluchicken I successfully tested that example in a new project. Here's the CRD I was able to generate:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: myapps.example.com
spec:
  group: example.com
  names:
    kind: MyApp
    listKind: MyAppList
    plural: myapps
    singular: myapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            fooOptional:
              type: string
            fooRequired:
              type: string
          required:
          - fooRequired
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
```

Are you able to share the struct you're having trouble with?
