### ISSUE TITLE
Ansible opeator playbook successfull but status still running with unknown reason code

### ISSUE THREAD

**Issue by matihost** [operator-framework/operator-sdk#1174]
When CR is created or reconcilled - the status or cr, and then play output are the following:

```
sh-4.2$ oc get cat operator-sample -o yaml | tail -n 18
status:
  conditions:
  - lastTransitionTime: 2019-03-06T10:08:25Z
    message: Running reconciliation
    reason: Running
    status: "False"
    type: Running
  - ansibleResult:
      changed: 13
      completion: 2019-03-06T10:08:57.041558
      failures: 0
      ok: 103
      skipped: 116
    lastTransitionTime: 2019-03-06T10:08:57Z
    message: non-zero return code
    reason: Failed
    status: "True"
    type: Failure
sh-4.2$ cat /tmp/ansible-operator/runner/ngp.cat.com/v1/catcustomresourcename/operator-sample/artifacts/latest/stdout | tail -n 5
META: ran handlers

PLAY RECAP *********************************************************************
localhost                  : ok=103  changed=13   unreachable=0    failed=0   

sh-4.2$ cat /tmp/ansible-operator/runner/ngp.cat.com/v1/catcustomresourcename/operator-sample/artifacts/latest/status
successfulsh-4.2$ cat /tmp/ansible-operator/runner/ngp.cat.com/v1/catcustomresourcename/operator-sample/artifacts/latest/rc
0
```

+
sometimes the message contains also:
```
      message: |-
        non-zero return code
        unknown playbook failure
```

The operator-sdk version:
```
cd ~/go/src/github.com/operator-framework/operator-sdk/ && git describe 
v0.5.0-50-gbf6eabe
```

Unfortunatelly there are no meaningful logs in the operator pod stdout.

PS. Nice feature by adding a symlink `latest` to the last ansible play logs!

**Comment by matihost** [comment]
* Removed all CRs of any kind.
* Restarted operator with: "--zap-level=debug", "--zap-encoder=console" on operator pod entrypoint
* Applied single CR - it took a sub-second to finish.
* Status:
```
  status:
    conditions:
    - lastTransitionTime: 2019-03-07T08:55:10Z
      message: Running reconciliation
      reason: Running
      status: "False"
      type: Running
    - ansibleResult:
        changed: 9
        completion: 2019-03-07T08:55:39.578939
        failures: 0
        ok: 83
        skipped: 104
      lastTransitionTime: 2019-03-07T08:55:39Z
      message: |-
        non-zero return code
        unknown playbook failure
      reason: Failed
      status: "True"
      type: Failure
```
* Last logs:
```
2019-03-07T08:55:39.672Z	DEBUG	eventapi	Dropping event that is not a JobEvent	{"job": "5319083292958780074"}
2019-03-07T08:55:39.803Z	INFO	runner	Ansible-runner exited successfully	{"job": "5319083292958780074", "name": "cr-sample-name", "namespace": ""}
2019-03-07T08:55:39.803Z	DEBUG	eventapi	Event API stopped	{"job": "5319083292958780074"}
```
