### ISSUE TITLE
The CR status timestamps are not in sync

### ISSUE THREAD

**Issue by matihost** [operator-framework/operator-sdk#1175]
The ansible-operator CR status timestamps are not in sync.

In particular:
.status.conditions.lastTransitionTime not sync with .status.conditions.ansibleResult.completion
```
  status:
    conditions:
    - ansibleResult:
        changed: 1
        completion: 2019-03-06T11:08:15.782885
        failures: 0
        ok: 6
        skipped: 5
      lastTransitionTime: 2019-03-06T10:57:59Z
      message: Awaiting next reconciliation
      reason: Successful
      status: "True"
      type: Running
```

Additionally

2019-03-06T11:08:15.782885  is not valid timestamp - so that it cannot be used in CRD column as `date`.

**Comment by matihost** [comment]
>The transition time is when the operator actually makes the transition.

It is not, it equals to CR creation timestamp.
```
metadata:
  (...)
  creationTimestamp: 2019-03-07T08:20:08Z
```

After first pass:
```
    conditions:
    - ansibleResult:
        changed: 2
        completion: 2019-03-07T08:20:14.081847
        failures: 0
        ok: 6
        skipped: 5
      lastTransitionTime: 2019-03-07T08:20:08Z
      message: Awaiting next reconciliation
      reason: Successful
      status: "True"
      type: Running
```

After second pass:
```  
  status:
    conditions:
    - ansibleResult:
        changed: 1
        completion: 2019-03-07T08:25:20.111347
        failures: 0
        ok: 6
        skipped: 5
      lastTransitionTime: 2019-03-07T08:20:08Z
      message: Awaiting next reconciliation
      reason: Successful
      status: "True"
      type: Running
```  
After third pass:
```  
  status:
    conditions:
    - ansibleResult:
        changed: 1
        completion: 2019-03-07T08:30:24.973539
        failures: 0
        ok: 6
        skipped: 5
      lastTransitionTime: 2019-03-07T08:20:08Z
      message: Awaiting next reconciliation
      reason: Successful
      status: "True"
      type: Running
```

the reconciliationPeriod is 5m.

The lastTransitionTime in general is useful - showing that operator is alive ;) 
But honestly I would use it to calculate calculate Ansible playbook duration (assuming it is a timestamp when Ansible play/role is run)

It would be totally cool if there `lastAnsibleRunDuration` field in the status as well.

It would be nice if there is status saying how long playbook run as well.
