### ISSUE TITLE
How to generate RBAC files from CLI

### ISSUE THREAD

**Issue by prometherion** [operator-framework/operator-sdk#1226]
## Type of question

Update the RBAC according to `kubebuilder` annotations.

## Question

**What did you do?**

I accidentally delete the `deploy/role.yaml` and `deploy/role_binding.yaml` files: so I thought that just a `operator generate k8s` could be enough to regenerate them but seems not.

**What did you expect to see?**

A brand new or updated RBAC files (_Role/ClusterRole_ and _RoleBinding/ClusterRoleBinding_)

**What did you see instead? Under which circumstances?**

As mentioned before, deleted files: `operators-sdk generate k8s` doesn't create new RBAC files.

I'm annotating the `Reconcile` Operator func as following:

```
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=extensions,resources=ingresses,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=,resources=services,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=,resources=persistentvolumes,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=,resources=persistentvolumeclaims,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=,resources=secrets,verbs=get;list;watch;create;update;patch;delete
```

**Environment**
* operator-sdk version:

operator-sdk version v0.5.0+git

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Minikube

**Additional context**

Nothing relevant.

**Comment by joelanford** [comment]
@prometherion operator-sdk currently generates a static role and role binding when the operator project is created during `operator-sdk new` and appends to the role when new apis are added during `operator-sdk add api`. It does not currently support regenerating the RBAC files from kubebuilder annotations.

If you're not able to restore your files from git you'll have to recreate them manually. Your role and role binding would have looked like the following if you didn't make any manual changes (based on running [1] and [2]):

[1]: `operator-sdk new my-operator`
[2]: `operator-sdk add api --api-version=example.com/v1alpha1 kind=MyApp`

**`deploy/role.yaml`:**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - my-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - example.com
  resources:
  - '*'
  verbs:
  - '*'
```

**`deploy/role_binding.yaml`:**
```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-operator
subjects:
- kind: ServiceAccount
  name: my-operator
roleRef:
  kind: Role
  name: my-operator
  apiGroup: rbac.authorization.k8s.io
```

Using the kubebuilder annotations does seem like a useful feature, especially since we've started using them in other areas (e.g. generating validation schemas based on annotations in `_types.go` files).

@estroz Did you run across the `+kubebuilder:rbac:` annotations when you were working on the openapi generation? Any thoughts on what it would take to use those?
