### ISSUE TITLE
Ansible operator fails with errors

### ISSUE THREAD

**Issue by ArjonBu** [operator-framework/operator-sdk#1246]
## Bug Report

**What did you do?**
I am writing an ansible operator https://gitlab.com/ArjonBu/mautic-operator
I created the CRD. Deployed all manifests related to operator. 
Deployed one custom resource and the operator pod gives errors.

**What did you expect to see?**
I expected the object pod to start running. 

**What did you see instead? Under which circumstances?**
The deployment of the custom resource was not created and the operator pod gave errors.

**Environment**
* operator-sdk version:

operator-sdk version v0.6.0+git

* Kubernetes version information:

  Minikube

* Are you writing your operator in ansible, helm, or go? Ansible

**Additional context**
Error log of operator container:
```
{"level":"info","ts":1553614792.752315,"logger":"cmd","msg":"Go Version: go1.10.3"}
{"level":"info","ts":1553614792.7524931,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1553614792.7525265,"logger":"cmd","msg":"Version of operator-sdk: v0.6.0"}
{"level":"info","ts":1553614792.752643,"logger":"cmd","msg":"Watching namespace.","Namespace":"default"}
{"level":"info","ts":1553614792.8018248,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1553614792.9642322,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1553614792.9642794,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1553614792.9661891,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"error","ts":1553614792.9663382,"logger":"runner","msg":"Failed to get config file","error":"open /opt/ansible/watches.yaml: permission denied","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/runner.NewFromWatches\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/runner/runner.go:104\ngithub.com/operator-framework/operator-sdk/pkg/ansible/operator.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/operator/operator.go:42"}
{"level":"error","ts":1553614792.966553,"logger":"manager","msg":"Failed to get watches","error":"open /opt/ansible/watches.yaml: permission denied","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/operator.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/operator/operator.go:44"}
{"level":"error","ts":1553614792.9666312,"logger":"cmd","msg":"Proxy or operator exited with error.","Namespace":"default","error":"open /opt/ansible/watches.yaml: permission denied","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:110\ngithub.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/run.RunAnsibleCmd.func1\n\tsrc/github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/run/ansible.go:38\ngithub.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).execute\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).Execute\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/commands/operator-sdk/main.go:24\nruntime.main\n\t/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/proc.go:198"}
```

watches.yaml
```
---
- version: v1alpha1
  group: mautic.bujupi.me
  kind: Mautic
  role: /opt/ansible/roles/mautic
```

Tasks:
```
---
# tasks file for mautic
- name: Deploy mautic
  k8s:
        definition: "{{ lookup('template', 'deploy-mautic.yml') }}"
```

template:
```
apiVersion: v1
kind: Secret
metadata:
  name: '{{ meta.name }}-mautic-mysql'
  namespace: '{{ meta.namespace }}'
type: Opaque
data:
  password: {{ dbPassword | b64encode }}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: '{{ meta.name }}-mautic'
  namespace: '{{ meta.namespace }}'
  labels:
    app: mautic 
spec:
  replicas: "{{ size }}"
  selector:
    matchLabels:
      app: mautic 
  template:
    metadata:
      labels:
        app: mautic 
    spec:
      containers:
        - image: {{ image }} 
          name: mautic
          env:
          - name: MAUTIC_DB_HOST
            value: {{ db_host }}
          - name: MAUTIC_DB_NAME
            value: {{ db_name }}
          - name: MAUTIC_DB_USER
            value: {{ db_user }}
          - name: MAUTIC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
          ports:
            - containerPort: 80
              name: mautic

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mautic 
  name: '{{ meta.name }}-mautic' 
  namespace: '{{ meta.namespace }}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mautic 

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: '{{ meta.name }}-mautic'
  namespace: '{{ meta.namespace }}'
  labels:
    app: mautic
spec:  
  rules:
  - host: "{{ ingress_name }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: '{{ meta.name }}-mautic' 
          servicePort: 80
```

My operator can be found at this repo: https://gitlab.com/ArjonBu/mautic-operator/
