### ISSUE TITLE
Missing attributes in the file generated by "operator-sdk  olm-catalog"

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1259]
## Bug Report

Missing attributes in the file generated by "operator-sdk  olm-catalog"

**What did you do?**
* Use the command operator-sdk  olm-catalog to created the ClusterServiceVersion
`operator-sdk  olm-catalog gen-csv --csv-version 0.0.1 --csv-config memcached-operator.0.0.1.clusterserviceversion.yaml`

**What did you expect to see?**
When applying the resource by " kubectl apply -f ../0.0.1/memcached-operator.v0.0.1.clusterserviceversion.yaml" all worked well

**What did you see instead? Under which circumstances?**
The following attributes missing. 

```
spec.customresourcedefinitions.owned.displayName in body is required
spec.customresourcedefinitions.owned.description in body is required
```
The same issue will be checked for the following attributes. 

```
provider:
    name: Camila, Inc
  keywords:
  - memcached
  - app
  maintainers:
  - email: corp@example.com
    name: Some Corp
```

**Environment**
* operator-sdk version:

```
$ operator-sdk --version
operator-sdk version v0.5.0+git
```
Master Branch

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-03-26T20:24:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: Minishift with OLM

* Are you writing your operator in ansible, helm, or go?
Go

**Possible Solution**
Just make the command add the missing values as I added them manually. 

```
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Memcached
      name: memcacheds.cache.example.com
      version: v1alpha1
      description: Operator Memcached Desc
      displayName: Memcached Operator
```
and

```
provider:
    name: Camila, Inc
  keywords:
  - memcached
  - app
  maintainers:
  - email: corp@example.com
    name: Some Corp
```

**Additional context**
