### ISSUE TITLE
upgrade to Ansible 2.8

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-sdk#1267]
Ansible has recently fixed a bug in the [github_release](https://docs.ansible.com/ansible/latest/modules/github_release_module.html) feature:

https://github.com/ansible/ansible/issues/45391#issuecomment-441086051

In my operator, it will create deployments for a particular image whose version, by default, will be the latest github release, thus it would be nice to use this `github_release`.
 
This, however, requires Ansible 2.8 but operator 0.6.0 only has Ansible 2.7.9.

Would be nice to have the operator pull in Ansible 2.8 in its next release.

(or, perhaps, is there a way to bundle a different Ansible version in my operator build?)

**Comment by hasbro17** [comment]
@shawn-hurley @fabianvf Any thoughts on if we need to bump up the Ansible version in the base image?

**Comment by jmazzitelli** [comment]
For the record, I was able to workaround this:

```
- name: Determine last release image version
  shell: echo -n $(curl -s https://api.github.com/repos/repo_user/repo_name/releases/latest 2> /dev/null | grep  "tag_name" | sed -e 's/.*://' -e 's/ *"//' -e 's/",//')
  register: github_lastrelease
- set_fact:
    image_version: "{{ github_lastrelease.stdout }}"
```
