### ISSUE TITLE
Ansible operator modifying dictionary key retrieved from OpenShift

### ISSUE THREAD

**Issue by aceeric** [operator-framework/operator-sdk#1366]
## Bug Report

**What did you do?**
Created an ansible operator that watches a custom resource. Deployed the operator to  OpenShift. Created debug logging to observe the behavior. The watched custom resource is:

```
apiVersion: foo.com/v1alpha1
kind: ClientApp
metadata:
  name: test-client-app
spec:
  appBindings:
    - name: strimzi-app-binding
      type: strimzi-kafka
      md5sum: ""
    - name: unused
      type: unused
      md5sum: ""
```

The CRD is:

```
---
apiVersion: apiextensions.k8s.io.v1beta1
kind: CustomResourceDefinition
metadata:
  name: clientapps.foo.com
spec:
  group: foo.com
  version: v1alpha1
  names:
    kind: ClientApp
    listKind: ClientAppList
    plural: clientapps
    singular: clientapp
    shortNames:
    - cliapp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            appBindings:
              description: test
              type: array
              items:
                type: object
                properties:
                  name:
                    description: test
                    type: string
                  type:
                    description: test
                    type: string
                  md5sum:
                    description: test
                    type: string
```

Here are the relevant ansible operator files:

Dockerfile:

```
FROM docker.io/operator-framework/ansible-operator:v0.6.0
# this docker file includes OpenJDK 1.8.0_141
COPY jre /java
ENV PATH="${PATH}:/java:/java/bin
COPY roles/ ${HOME}/roles
COPY watches.yaml ${HOME}/watches.yaml
COPY *playbook.yml ${HOME}/
```

The docker build:
```
docker build -t client-app-operator:v1 .
docker tag client-app-operator:v1 <our registry>/foo/client-app-operator:v1
docker push <our registry>/foo/client-app-operator:v1
```

watches.yaml:

```
---
- version: v1alpha1
  group: foo.com
  kind: ClientApp
  playbook: /opt/ansible/client-app-operator-playbook.yml
```

client-app-operator-playbook.yml:

```
---
- hosts: 127.0.0.1
  gather_facts: false
  roles: /opt/ansible/roles/ClientAppOperatorRole
```

roles/ClientAppOperatorRole/tasks/main.yaml:
(simplified)

```
---
- name: Strimzi Kafka
  include_tasks: strimzi-kafka.yml
```

roles/ClientAppOperatorRole/tasks/strimzi-kafka.yml:

```
---
- name: Get the watched CR
  k8s:
    resource_definition:
      "{{ lookup(
           'k8s', kind='ClientApp',
           namespace='<your namespace here>',
           api_version='foo.com/v1alpha1'
           resource_name='test-client-app')
      }}"
    register: client_app

- name: get the app bindings
  set_fact:
    app_bindings: "{{ client_app.result.spec.appBindings }}"  

- name: trace the app bindings
  debug:
    msg: "app_bindings = {{ app_bindings }}"
```

There are no other files defined in the role...

RBAC stuff (all cloned from memcached):

service account yaml:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-app-operator
```

role yaml:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: client-app-operator-role
rules:
  apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/log
  - services
  - endpoints
  - persistentcolumeclaims
  - events
  - configmaps
  - namespaces
  - secrets
  verbs:
  - '*'
  apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - deployments/status
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
  apiGroups:
  - foo.com
  resources:
  - clientapps
  - clientapps/status
  verbs:
  - '*'
```

role binding yaml:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: client-app-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: client-app-operator-role
subjects:
-kind: ServiceAccount
  name: client-app-operator
  namespace: <your namespace here>
```

operator yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app-operator
spec:
  replicas: 1
  selector:
    matchLabels:
	  name: client-app-operator
  template:
    metadata:
	  labels:
	    name: client-app-operator
    spec:
	  serviceAccountName: client-app-operator
	  containers:
	    - name: client-app-operator
		  image: <our registry>/foo/client-app-operator:v1
		  imagePullPolicy: Always
		  env:
		    - name: WATCH_NAMESPACE
			  valueFrom:
			    fieldRef:
				  fieldPath: metadata.namespace
		    - name: POD_NAME
			  valueFrom:
			    fieldRef:
				  fieldPath: metadata.name
		    - name: OPERATOR_NAME
			  value: "client-app-operator"
```

I build the Docker image, push it to our internal registry, and deploy all the descriptors. Again - all this is cloned from memcached Ansible operator. The pod comes up fine.

**What did you expect to see?**
I expected to see the app bindings trace taske in the role appear in the logs with each item in the list represented as it appears in the custom resource definition.

**What did you see instead? Under which circumstances?**
Here's what the log shows for the "trace the app bindings" task:
```
ok: [localhost] => {
  "msg": "app_bindings = [{u'md_5_sum': u'', u'type': u'strimzi-kafka', u'name': u'strimzi-app-binding'}, {u'md_5_sum': u'', u'type': u'unused', u'name': u'unused'}]"
}
```

Notice that the "md5sum" dictionary key gets changed into "md_5_sum". This is a problem because later in the yaml, I need to access/update that dictionary value and the playbook is failing.

What's really confusing is - if I follow these steps:
1) rsh into the pod
2) copy the entire /opt/ansible directory to /tmp/foo
3) Change the playbook to reference the role in the new location
4) from tmp/foo: ansible-playbook client-app-operator-playbook.yml

It works perfectly! It's only when the exact same ansible artifacts are run within the context of the operator that this odd behavior manifests. Note - I've had to hand-type everything here so - my apoligies for any typos. I've tried testing locally and everything is fine. This only manifests when the operator runs my playbook.

**Environment**
operator-sdk version: v0.6.0
ansible 2.7.0
python 2.7.5
Java 1.8.0_141
OpenShift v3.11.59
kubernetes v1.11.0+d4cacc0

**Comment by LiliC** [comment]
cc @jmrodri @shawn-hurley if you can help out ^

**Comment by rbo** [comment]
I ran into the same behavior, it feels broken but might be a thing you need because of ansible.

It is well documented:  https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/developer_guide.md#extra-vars-sent-to-ansible

It looks like you can use: `_foo_com_clientapp.spec.appBindings`

**Comment by fabianvf** [comment]
@aceeric sorry for the massive delay getting back to you, did the above allow you to workaround this issue?

**Comment by feikesteenbergen** [comment]
I'm running into the same issue currently, [this](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/developer_guide.md#extra-vars-sent-to-ansible) does not make it clear to me why this happens.

This is what is created as a CRD:

```yaml
metadata:
  name: example
spec:
  backup:
    abc11def: anothertest
    enabled: true
    pg1_repo_path: test
    s3_bucket: example
```

And this is how `backup` ends up in the ansible run:

```json
{
        "abc_11_def": "anothertest", 
        "enabled": true, 
        "pg_1__repo_path": "test", 
        "s_3__bucket": "example"
}
```

It seems that any set of digits is surrounded by underscores when converted into variables.
