### ISSUE TITLE
ingresses.extensions is forbidden: User cannot delete resource "ingresses" in API group "extensions" in the namespace

### ISSUE THREAD

**Issue by Jinchul81** [operator-framework/operator-sdk#1496]
## Bug Report

**What did you do?**
I was trying to deploy my custom helm chart which was already verified in Helm management tool, but my operator showed some errors related to RBAC issue.

I had realized that `deploy/role.yaml` should include additional rules, but the error still has happened even though adding the following rules. (please see `extensions` in `apiGroups`  and `ingresses` in `resources`)
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: myapp-operator
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - metatron.app
  resources:
  - '*'
  verbs:
  - '*'
``` 

```
$ kubectl describe role myapp-operator -n jc
Name:         myapp-operator
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources                          Non-Resource URLs  Resource Names  Verbs
  ---------                          -----------------  --------------  -----
  configmaps                         []                 []              [* *]
  secrets                            []                 []              [* *]
  endpoints                          []                 []              [*]
  events                             []                 []              [*]
  ingresses                          []                 []              [*]
  persistentvolumeclaims             []                 []              [*]
  pods                               []                 []              [*]
  services                           []                 []              [*]
  daemonsets.apps                    []                 []              [*]
  deployments.apps                   []                 []              [*]
  replicasets.apps                   []                 []              [*]
  statefulsets.apps                  []                 []              [*]
  configmaps.extensions              []                 []              [*]
  endpoints.extensions               []                 []              [*]
  events.extensions                  []                 []              [*]
  ingresses.extensions               []                 []              [*]
  persistentvolumeclaims.extensions  []                 []              [*]
  pods.extensions                    []                 []              [*]
  secrets.extensions                 []                 []              [*]
  services.extensions                []                 []              [*]
  *.mydomain.app                     []                 []              [*]
  namespaces                         []                 []              [get]
```

**What did you expect to see?**
I expected no error.

**What did you see instead? Under which circumstances?**
```
{"level":"error","ts":1559129829.1091373,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"myapp-controller","request":"jc/myapp","error":"release myapp-c9e6t9126ru1jx803frxy7dmr failed: ingresses.extensions is forbidden: User \"system:serviceaccount:jc:myapp-operator\" cannot create resource \"ingresses\" in API group \"extensions\" in the namespace \"mydomain\"","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
2019/05/29 11:38:31 uninstall: Failed deletion of "myapp-c9e6t9126ru1jx803frxy7dmr": ingresses.extensions "coordinator.svc.stg.test.cloud.mydomain.app" is forbidden: User "system:serviceaccount:jc:myapp-operator" cannot delete resource "ingresses" in API group "extensions" in the namespace "mydomain"
```

**Environment**
* operator-sdk version:
> operator-sdk version: v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342

* go version:
> go version go1.12.5 linux/amd64

* Kubernetes version information:

* Kubernetes cluster kind: 
> Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Are you writing your operator in ansible, helm, or go?
Yes, I am using helm operator.

**Possible Solution**

**Additional context**
