### ISSUE TITLE
Ansible operator: disable gathering facts

### ISSUE THREAD

**Issue by kvaps** [operator-framework/operator-sdk#1677]
## Feature Request

**Problem**
Every role call is taking 2-3 seconds for gathering facts, in most cases this is absolutely unnecessary in the kubernetes reality.

**Solution**
Allow specifying `gather_facts: no` option to watches.yaml

```yaml
- version: v1alpha1
  group: cache.example.com
  kind: Memcached
  gather_facts: no
  role: /opt/ansible/roles/memcached
```

When `gather_facts` is set to `no`, then set `ANSIBLE_GATHERING=false` variable before calling ansible-runner.

**Workaround**

Currently this behavior can be simple overridden by specifying `ANSIBLE_GATHERING=false` variable globably.
Other option is using playbook instead role:
```
- hosts: localhost
  gather_facts: no
  tasks:
  - import_role:
      name: "memcached"
```
