### ISSUE TITLE
Ansible operator: allow parallel execution

### ISSUE THREAD

**Issue by kvaps** [operator-framework/operator-sdk#1678]
## Feature Request

**Problem**
Every task execution is taking about 3s, even just simple playbook:

```
- hosts: localhost
  gather_facts: no
  tasks:
  - import_role:
      name: "memcached"
```

If you have updated 100 custom resources in one time, they will be processed only after 5 minutes

**Solution**
Allow concurrent jobs in **watches.yaml** file:

```
- version: v1alpha1
  group: cache.example.com
  kind: Memcached
  parallelJobs: 10
  role: /opt/ansible/roles/memcached
```

if `parallelJobs` is set to `10`, then we can process 10 tasks simultaneously.
