### ISSUE TITLE
Ansible operator: skip execution on init

### ISSUE THREAD

**Issue by kvaps** [operator-framework/operator-sdk#1679]
## Feature Request

**Problem**

Every task execution is taking about 3s, even just simple playbook:

```
- hosts: localhost
  gather_facts: no
  tasks:
  - import_role:
      name: "memcached"
```

Eg if you have 100 custom resources, and then you restart operator, it will be able to process new operations only after 5 minutes, after processing all 100 existing resources.

**Solution**

Allow specifying `preserveStatus: true` option on a par with `reconcilePeriod: 0` in watches.yaml file:

```
- version: v1alpha1
  group: baz.example.com
  kind: Baz
  playbook: /opt/ansible/baz.yml
  reconcilePeriod: 0
  preserveStatus: true
```

*Processing:*

If `preserveStatus` is set to `true`, then save `metadata.generation` to `status.generation` for each resource.

*Initialization:*

During start do the check:  if  `metadata.generation` equals `status.generation`, then skip resource processing.

**Comment by shawn-hurley** [comment]
You could effectively get this now, by turning of dependent watches https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/dependent_watches.md

WDYT?

**Comment by kvaps** [comment]
Hi @shawn-hurley, thanks for answer, but I'm not sure that this option can help somehow in this case.
Eg if I have 100 resources, ansible-operator will process all of them during the restart of the operator itself.

**Comment by kvaps** [comment]
Working prototype:

```yaml
  - meta: end_play
    when: "status.generation is defined and status.generation|int == metadata.generation|int"

  - debug:
      msg: "do something"

  - k8s_status:
      api_version: 'moonshot.wedos.org/v1alpha1'
      kind: 'MoonshotNode'
      name: '{{ metadata.name }}'
      status:
        generation: "{{ metadata.generation }}"
```
