### ISSUE TITLE
Duplicate info in CSV generated by `operator-sdk  olm-catalog gen-csv`

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1707]
## Bug Report

OLM

**What did you do?**
Run  `operator-sdk  olm-catalog gen-csv --csv-version 0.0.1 --csv-config mobile-security-service-operator.0.0.1.clusterserviceversion.yaml` for https://github.com/aerogear/mobile-security-service-operator

**What did you expect to see?**

```
  customresourcedefinitions:
    owned:
    - kind: MobileSecurityService
      name: mobilesecurityservices.mobile-security-service.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityServiceApp
      name: mobilesecurityserviceapps.mobile-security-service.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityServiceBackup
      name: mobilesecurityservicebackups.mobile-security-service.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityServiceDB
      name: mobilesecurityservicedbs.mobile-security-service.aerogear.com
      version: v1alpha1
```
**What did you see instead? Under which circumstances?**

```
  customresourcedefinitions:
    owned:
    - kind: MobileSecurityService
      name: mobilesecurityservices.mobile-security-service.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityServiceApp
      name: mobilesecurityserviceapps.mobile-security-service.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityServiceBackup
      name: mobilesecurityservicebackups.mobile-security-service.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityServiceDB
      name: mobilesecurityservicedbs.mobile-security-service.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityService
      name: mobilesecurityservices.mobilesecurityservice.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityServiceApp
      name: mobilesecurityserviceapps.mobilesecurityservice.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityServiceBackup
      name: mobilesecurityservicebackups.mobilesecurityservice.aerogear.com
      version: v1alpha1
    - kind: MobileSecurityServiceDB
      name: mobilesecurityservicedbs.mobilesecurityservice.aerogear.com
      version: v1alpha1
```
**Environment**
* operator-sdk version:  v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342
