### ISSUE TITLE
k8s_status fails to merge status

### ISSUE THREAD

**Issue by aeb-sia** [operator-framework/operator-sdk#1742]
## Bug Report

**What did you do?**
Running the below playbook:
```yaml
- name: Running Reconciliation
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Set status
    k8s_status:
      api_version: v1
      kind: ResourceType
      name: "{{meta.name}}"
      namespace: "{{meta.namespace}}"
      conditions:
        - type: Foo
          status: False
          reason: bar
          message: meh
  - name: Success status
    k8s_status:
      api_version: v1
      kind: ResourceType
      name: "{{meta.name}}"
      namespace: "{{meta.namespace}}"
      conditions:
        - type: Foo
          status: True
          reason: meh
          message: bar
```
**What did you expect to see?**
I expect that the second status overrides the first in the generated resource.
**What did you see instead? Under which circumstances?**
The status is just appended:
```yaml
  - lastTransitionTime: "2019-07-26T06:38:03Z"
    message: meh
    reason: bar
    status: "False"
    type: Foo
  - lastTransitionTime: "2019-07-26T06:38:03Z"
    message: bar
    reason: meh
    status: "True"
    type: Foo
  - lastTransitionTime: "2019-07-26T06:38:17Z"
    message: meh
    reason: bar
    status: "False"
    type: Foo
  - lastTransitionTime: "2019-07-26T06:38:17Z"
    message: bar
    reason: meh
    status: "True"
    type: Foo
  - lastTransitionTime: "2019-07-26T06:38:31Z"
    message: meh
    reason: bar
    status: "False"
    type: Foo
  - lastTransitionTime: "2019-07-26T06:38:31Z"
    message: bar
    reason: meh
    status: "True"
    type: Foo
  - lastTransitionTime: "2019-07-26T06:38:45Z"
    message: meh
    reason: bar
    status: "False"
    type: Foo
  - lastTransitionTime: "2019-07-26T06:38:45Z"
    message: bar
    reason: meh
    status: "True"
    type: Foo
  - lastTransitionTime: "2019-07-26T06:35:47Z"
    message: Running reconciliation
    reason: Running
    status: "True"
    type: Running
  - message: meh
    reason: bar
    status: "False"
    type: Foo
```

**Environment**
* operator-sdk version:

quay.io/operator-framework/ansible-operator:v0.8.2

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
(not sure - got it from our ops, but I doubt that's relevant here...)

* Operator written in Ansible

**Comment by aeb-sia** [comment]
I also sometimes observe this:
```yaml
  - lastTransitionTime: "2019-07-25T17:40:31Z"
    message: Running reconciliation
    reason: Running
    status: "False"
    type: Reconciling
  - lastTransitionTime: "2019-07-25T17:40:50Z"
    message: Running reconciliation
    reason: Running
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2019-07-25T17:40:50Z"
    message: Running reconciliation
    reason: Running
    status: "False"
    type: Reconciling
  - lastTransitionTime: "2019-07-25T17:41:08Z"
    message: Running reconciliation
    reason: Running
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2019-07-25T17:41:08Z"
    message: Running reconciliation
    reason: Running
    status: "False"
    type: Reconciling
```
But I'm not sure where that comes from...
