### ISSUE TITLE
scorecard test failed to run 'Provided APIs have validation' test

### ISSUE THREAD

**Issue by lluan444** [operator-framework/operator-sdk#1763]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

I am seeking help with scorecard test `Provided APIs have validation: 0/0`

## Question
How to fix scorecard test failure for `Provided APIs have validation: 0/0`? 

**What did you do?**

I ran the scorecard tests against my operator. See the test results below. All other tests were successful except `Provided APIs have validation: 0/0`.  

```
$ operator-sdk scorecard --cr-manifest deploy/esindex-test-secret.cr.yaml --csv-path deploy/ibmcloud_operator.v0.1.0.clusterserviceversion.yaml --namespace default --verbose --proxy-image quay.io/operator-framework/scorecard-proxy
DEBU[0000] Debug logging is set                         
WARN[0000] Could not load config file; using flags      
WARN[0000] Plugin directory not found; skipping external plugins: stat scorecard: no such file or directory 
E0801 08:48:40.460578    4289 memcache.go:135] couldn't get resource list for packages.operators.coreos.com/v1: the server is currently unable to handle the request
E0801 08:48:43.786506    4289 memcache.go:135] couldn't get resource list for packages.operators.coreos.com/v1: the server is currently unable to handle the request
Basic Tests:
	Status Block Exists: 1/1
	Writing into CRs has an effect: 1/1
	Spec Block Exists: 1/1
OLM Tests:
	Spec fields with descriptors: 5/5
	Status fields with descriptors: 3/3
	Provided APIs have validation: 0/0
	Owned CRDs have resources listed: 1/1
	CRs have at least 1 example: 1/1

Total Score: 88%
```
My crd does contain validations for all the properties in spec and status, see esindex.crd.yaml and esindex-test.cr.yaml below.

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: esindices.ibmcloud.ibm.com
spec:
  group: ibmcloud.ibm.com
  names:
    kind: EsIndex
    plural: esindices
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bindOnly:
              description: Bind to an existing index if true, default value false
              type: boolean
            bindingFrom:
              description: Binding resource name that holds the secret for elastic
                search credentials
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            esURIComposed:
              description: EsURIComposed is the URI of elasticesearch resource in
                the format https://<user>:<passwd>@hostname:port. Cannot be used if
                binding is not empty.
              properties:
                configMapKeyRef:
                  description: Selects a key of a ConfigMap in the local namespace.
                  type: object
                secretKeyRef:
                  description: Selects a key of a secret in the local namespace
                  type: object
              type: object
            indexName:
              description: Name of Index to be created on elastic search
              type: string
            numberOfReplicas:
              description: Number of replicas, default value 1
              format: int64
              type: integer
            numberOfShards:
              description: Number of shards, default value 1
              format: int64
              type: integer
          required:
          - indexName
          type: object
        status:
          properties:
            generation:
              description: Generation of the implemented spec
              format: int64
              type: integer
            message:
              description: Message
              type: string
            state:
              description: State of the resource instance
              type: string
          required:
          - generation
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

```
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: EsIndex
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: index-scorecard
spec:
  bindingFrom: 
    name: es-test-binding
  indexName: index-scorecard
  numberOfShards: 2
  numberOfReplicas: 1
```

**What did you expect to see?**
I expected to get `Provided APIs have validation: 1/1`. 

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
I got `Provided APIs have validation: 0/0` and no suggestions or error messages.

**Environment**
* operator-sdk version: 

 0.9.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8+IKS", GitCommit:"fe3e332c2b0f47d4572433c3b0a1687a27fb88c6", GitTreeState:"clean", BuildDate:"2019-07-11T13:45:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

IBM Cloud

**Additional context**
