### ISSUE TITLE
How do you specify OpenAPI constraints?

### ISSUE THREAD

**Issue by jsanda** [operator-framework/operator-sdk#1773]
## Type of question
My question is about `operator-sdk generate openapi`, although it be a question for [kube-openapi](https://github.com/kubernetes/kube-openapi).

## Question
Is is it possible to generate constraints as in the following example taken from the k8s docs:

```yaml
type: object
description: "foo bar object"
properties:
  foo:
    type: string
    pattern: "abc"
  bar:
    type: integer
  metadata:
    type: object
    properties:
      name:
        type: string
        pattern: "^a"
anyOf:
- properties:
    bar:
      minimum: 42
  required: ["bar"]
```
I have looked at other projects that use operator-sdk, like the prometheus operator, and I haven't seen any sort of constraints like in the example above. 

**What did you do?**
I am running `operator-sdk generate openapi` in my project.

**Environment**
* operator-sdk version: v0.7.0, v0.9.0
