### ISSUE TITLE
Code-gen is not ignoring code-annotations

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1893]
## Bug Report

**What did you do?**
Add the code annotation on top of the status and spec fields then run the code-gen commands `operator-sdk generate k8s and operator-sdk generate openapi`. Following an example. 

```
	// Name of the PersistentVolumeClaim created and managed by it
	// +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors=true
	// +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors.displayName="v1.PersistentVolumeClaimStatus"
```

**What did you expect to see?**

The CRD be generated with the desc only

**What did you see instead? Under which circumstances?**

```YAML
            pvcStatus:
              description: Name of the PersistentVolumeClaim created and managed by
                it +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors=true
                +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors.displayName="v1.PersistentVolumeClaimStatus"
              type: object
```

**Environment**
- (master) "v0.10.0-75-g06563665", commit: "065636659cbc0d589c83b805c6a8920124c7eedf", go version: "go1.12.7 darwin/amd64" 
- (v0.10.0) : operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170
