### ISSUE TITLE
Unable to handel multipel CRDs

### ISSUE THREAD

**Issue by jleach** [operator-framework/operator-sdk#1924]
## Type of question

How to implement a specific feature?

## Question

In my `watches.yaml` I have two kinds of CRDs. When I start the operator for local development it complains that one of them can not be found. If I comment out one the other works. Any tips tips would be appreciated.

I'm using version **v0.8.1** of operator-sdk.

My error:
```
2019-09-16T21:22:08.115Z        ERROR   ansible-controller              {"error": "no matches for kind \"NetworkSecurityPolicy\" in version \"secops.pathfinder.gov.bc.ca/v1alpha1\""}
```

My watches.yaml looks like:

```
---
- kind: NetworkSecurityPolicy
  version: v1alpha1
  group: secops.pathfinder.gov.bc.ca
  # reconcilePeriod: 0
  playbook: /opt/ansible/netpol-main.yaml
  finalizer:
    name: finalizer.secops.pathfinder.gov.bc.ca
    playbook: /opt/ansible/netpol-destroy.yaml
- kind: ExternalNetworkPolicy
  version: v1alpha1
  group: secops.pathfinder.gov.bc.ca
  # reconcilePeriod: 0
  playbook: /opt/ansible/extnet-main.yaml
  # finalizer:
  #   name: finalizer.secops.pathfinder.gov.bc.ca
  #   playbook: /opt/ansible/extnet-destroy.yaml
```

And my CRD looks like:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networksecuritypolicies.secops.pathfinder.gov.bc.ca
spec:
  group: secops.pathfinder.gov.bc.ca
  names:
    kind: NetworkSecurityPolicy
    listKind: SecOpsPolicyList
    plural: networksecuritypolicies
    singular: networksecuritypolicy
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: externalnetworkpolicies.secops.pathfinder.gov.bc.ca
spec:
  group: secops.pathfinder.gov.bc.ca
  names:
    kind: ExternalNetworkPolicy
    listKind: SecOpsPolicyList
    plural: externalnetworkpolicies
    singular: externalnetworkpolicy
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
```
