### ISSUE TITLE
Ansible operator not supporting owner reference injection for Projects

### ISSUE THREAD

**Issue by rammohanc** [operator-framework/operator-sdk#1969]
## Bug Report

**What did you do?**
When a CR creates a Project/namespace, there is no owner related annotations in the project such as  "operator-sdk/primary-resource" and "operator-sdk/primary-resource-type" as seen with other objects that are created with owner reference injection (such as LimitRange, ResourceQuota). 

Even after manual addition of above annotations to the Project, dependency watch/reconcile is not triggered when any changes to the Project are made. As a worked around we added ownerReferences to the Project's metadata, and this has helped trigger watch dependency /reconcile whenever the Project is modified.

Example of ownerReference as added to Project definition:
```
metadata:
  ownerReferences:
  - apiVersion: app.test.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: CRTestProject
    name: abc-project
    uid: adc485bf-df0b-11e9-a252-0216b80cbb02
```

**What did you expect to see?**
When a Project is created by a CR, it should have the owner reference injected and any changes to the project should trigger the reconcile.

**What did you see instead? Under which circumstances?**
1. There is no owner reference injection annotations in the Project definition,when inject-owner-ref (in Dockerfile) and watchDependentResources (in watches.yaml)  is enabled
2. Manual addition of owner reference injection annotations to the Project has not triggered reconcile
3. Reconcile happens only when ownerReferences is added to the Project (as workaround)

**Environment**
* operator-sdk version: v0.10.x, go version:  go1.12.4 

* Kubernetes version information: v1.11.0+d4cacc0

* Kubernetes cluster kind:  Openshift v3.11.141

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**
Adding ownerReferences to the project as mentioned above

**Comment by fabianvf** [comment]
hmm, this could be a little tricky, there's some weirdness with Projects and watches, but I'll try and dig into this a bit. Can you paste the task you are using to create the project?

**Comment by Jamstah** [comment]
I opened https://github.com/operator-framework/operator-sdk/issues/2089 but the root cause is this issue. @fabianvf I can provide debug information if it helps.

My task file:
```
---
# tasks file for managednamespace
- name: Create namespace
  k8s:
    definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: '{{ meta.name }}'
```
