### ISSUE TITLE
How to generate CRD with metadata label

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [operator-framework/operator-sdk#2012]
The CRD generated by the operator-SDK is controlled by GO annotations.  Example:
```
+k8s:openapi-gen=true
+kubebuilder:subresource:status
+kubebuilder:resource:shortName=sk
```
If we wanted to create the CRD with some metadata label such as the following:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: somename
  labels:
    department: finance
spec:
  group: somegroup
  names:
    kind: SomeKind
    shortNames:
    - sk
```
Is there something we can put in the go type such that the department: finance would be generated into the CRD?
