### ISSUE TITLE
Validation failure for missing optional field

### ISSUE THREAD

**Issue by zroubalik** [operator-framework/operator-sdk#2075]
## Bug Report

**What did you do?**
Deployed an operator with type with Spec like this:
```go
type MyObjectSpec struct {
	// +optional
	MyType MyObjectType `json:"myType,omitempty"`
	// +optional
	MyTargetRef ObjectReference `json:"myTargetRef,omitempty"`
	// +optional
	JobTargetRef batchv1.JobSpec `json:"jobTargetRef,omitempty"`
	// +optional
	Interval *int32 `json:"interval,omitempty"`
	// +optional
	Period *int32 `json:"period,omitempty"`
	// +listType
	Triggers []MyTriggers `json:"triggers"`
}
```
Then deployed CR like this:
```yaml
apiVersion: myobject.k8s.io/v1alpha1
kind: MyObject
metadata:
  name: object
  namespace: default
spec:
 interval: 15
 targetRef:
    deploymentName: deployment1
 triggers:
    ...

```

**What did you expect to see?**
Object being reconciled.

**What did you see instead? Under which circumstances?**
Reconciler error with message:
`validation failure list:\nspec.jobTargetRef.template.spec.containers in body must be of type array: \"null\""`

**Environment**
* operator-sdk version: 
v0.11.0

* go version:
1.13.1

* Kubernetes version information:
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+e353665", GitCommit:"e353665", GitTreeState:"clean", BuildDate:"2019-09-17T18:43:35Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Openshift 

* Are you writing your operator in ansible, helm, or go?
go

**Additional context**
JobTargetRef is marked with both `// +optional` and `omitempty', so this filed should be ingored by the validator if it is not specified in the CR, but apperantly is required. I can't understand what's wrong, it seems like a bug for me.
