### ISSUE TITLE
ansible: Created namespaces are not cleaned up

### ISSUE THREAD

**Issue by Jamstah** [operator-framework/operator-sdk#2089]
## Bug Report

**What did you do?**

1. Created an ansible operator that creates a namespace
  ```
  ---
  # tasks file for managednamespace
  - name: Create namespace
    k8s:
      definition:
        kind: Namespace
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}'
  ```
2. Created the CR
3. Deleted the CR

**What did you expect to see?**

1. Namespace would be created
2. Namespace would be deleted

**What did you see instead? Under which circumstances?**

1. Namespace was created
2. Namespace was not deleted

**Environment**
* operator-sdk version: operator-sdk version:

"v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64"

* Kubernetes version information:

oc v3.11.98
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://c100-e.eu-gb.containers.cloud.ibm.com:32010
openshift v3.11.146
kubernetes v1.11.0+d4cacc0

* Kubernetes cluster kind: Openshift 3.11

* Are you writing your operator in ansible, helm, or go?: ansible
