### ISSUE TITLE
Scorecard does not wait for finalisers to complete before removing operator

### ISSUE THREAD

**Issue by oseoin** [operator-framework/operator-sdk#2094]
## Bug Report

**What did you do?**
Created a simple Ansible Operator with SDK v0.11.0 to reproduce an issue we are seeing on our Ansible operators where finalisers do not complete within a few seconds. 

Using the following tasks:
```yaml
---
- name: "Set state of {{ meta.name }}-test-cfg"
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: "v1"
      kind: ConfigMap
      metadata:
        name: "{{ meta.name }}-test-cfg"
        namespace: "{{ meta.namespace }}"
      data:
        key: value

- name: test wait
  shell: sleep 10
```

Set a finaliser set in watches:
```yaml
- version: v1
  group: example.com
  kind: TestCr
  playbook: /opt/ansible/playbook.yml
  finalizer:
    name: example.com
    vars:
      state: absent
```

Used the following scorecard configuration:
```yaml
scorecard:
  plugins:
    - basic:
        olm-deployed: false
        cr-manifest:
          - "deploy/crds/icm.ibm.com_v1_testcr_cr.yaml"
        init-timeout: 300
```

**What did you expect to see?**
With the sleep task disabled I see the following as expected: 
```
operator-sdk scorecard --verbose   
DEBU[0000] Debug logging is set                         
INFO[0000] Using config file: /Users/oseoin/playground/kubernetes/operators/operator-test/.osdk-scorecard.yaml 
Basic Tests:
        Writing into CRs has an effect: 1/1
        Spec Block Exists: 1/1
        Status Block Exists: 1/1
```

**What did you see instead? Under which circumstances?**
Instead I get an error that cleanup does not complete:
```
operator-sdk scorecard --verbose       
DEBU[0000] Debug logging is set                         
INFO[0000] Using config file: /Users/oseoin/playground/kubernetes/operators/operator-test/.osdk-scorecard.yaml 
WARN[0044] time="2019-10-23T15:19:35+01:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-23T15:19:45+01:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-23T15:19:45+01:00" level=error msg="Failed to cleanup resources: (a cleanup function failed; see stdout for more details)" 
Basic Tests:
        Spec Block Exists: 1/1
        Status Block Exists: 1/1
        Writing into CRs has an effect: 1/1
```

Watching the operator deployment I can see that it gets removed before the finaliser completes.

**Environment**
* operator-sdk version:

operator-sdk version: "v0.11.0"
commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d"

* go version:
go version: "go1.13.1 darwin/amd64"

* Kubernetes version information:
```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Docker desktop 2.1.4.0 on macOs 10.15

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**
Scorecard should wait before removing the operator deployment if finalisers are set.

**Comment by camilamacedo86** [comment]
Hi,

Thank you for raise it. I will try to reproduce it.

**Comment by camilamacedo86** [comment]
Hi @oseoin,

Thank you for raise it. Could you please let us the following information?

1. Have you tried to increase the `init-timeout: 120`? See [doc](https://github.com/operator-framework/operator-sdk/blob/b964dd61a75948a56bf3bbaadaba453504f1170a/doc/test-framework/scorecard.md#olm-integration).
2.  Is this project public? Could you share it? 
3. What is the command that you have been used to call scorecard? Could you provide the .osdk-scorecard.yaml used? 
4. Have any information in the stdout? See `see stdout for more details`?

**Comment by mew2057** [comment]
I'm hitting a similar problem as well (stdout doesn't show anything):


- [Repo](https://github.com/IBM/ibm-spectrum-scale-csi-operator/tree/dev
) 
- [Travis CI Run](https://travis-ci.org/mew2057/ibm-spectrum-scale-csi-operator/jobs/602840508)
- [Internal Issue](https://github.com/IBM/ibm-spectrum-scale-csi-operator/issues/34)


Scorecard command:
``` bash
# If I don't spec cr-manifest and csv-path it doesn't work.
GO111MODULE=on operator-sdk scorecard --config .osdk-scorecard.yaml --cr-manifest  deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml  --csv-path deploy/olm-catalog/ibm-spectrum-scale-csi-operator/0.0.1/ibm-spectrum-scale-csi-operator.v0.0.1.clusterserviceversion.yaml
```
`.osdk-scorecard.yaml`
``` YAML
scorecard:
  init-timeout: 120
  output: json
  plugins:
    - basic:
        cr-manifest:
            - "deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml"
    - olm:
        cr-manifest:
            - "deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-spectrum-scale-csi-operator/0.0.1/ibm-spectrum-scale-csi-operator.v0.0.1.clusterserviceversion.yaml"
```

**Comment by mew2057** [comment]
I just did two configs of my `watches.yaml` and it looks like there's a pretty concrete connection in the finalizer to the scorecard failing. I ran both versions through travis and got the following results:


[Scorecard 100%](https://travis-ci.org/mew2057/ibm-spectrum-scale-csi-operator/jobs/602897757)
"Good" config:
```
---
- version: v1alpha1
  group: scale.ibm.com
  kind: CSIScaleOperator
  role: /opt/ansible/roles/csi-scale
  ManageStatus: True
```


---

[Scorecard 50%](https://travis-ci.org/mew2057/ibm-spectrum-scale-csi-operator/jobs/602904105)
"Bad" Config
```
---
- version: v1alpha1
  group: scale.ibm.com
  kind: CSIScaleOperator
  role: /opt/ansible/roles/csi-scale
  ManageStatus: True
  finalizer:
    name: finalizer.scale.ibm.com
    vars:
      state: absent
```

**Comment by camilamacedo86** [comment]
Hi @mew2057, 

Really thank you for the great info provide. Could you just please do the following test? 

I just would like to isolate the scenario to know if it is a scorecard issue or a finalizer issue with ansible operator. Then, could you check it out of the scorecard? I mean, could you install all, then check that are all running and then, try to delete the objects to see if it will get stuck? 

See [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/Makefile) a Makefile with the commands `make install` and `make uninstall` which can help you to do this test.

**Comment by camilamacedo86** [comment]
Hi @mew2057, 

Also, checking your logs I notice that you are using python 2.

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

So, try to use Python3. Following how to add it in your .travis file. 
 
```yaml
# Python 3.6 is the default Python when language: python.
# But when not language: python, Python 3 can not be used by default.
# There is pip (/usr/bin/pip), but not pip3.
# Because of it the global env is required.
env:
  global:
    - PATH=/opt/python/3.6.7/bin:$PATH

# Install python3 and utilities dependencies
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip" 
```

It may can be the root cause since because of the deprecation we upgrade it to use Python3.
