### ISSUE TITLE
Is r.client.Get() supposed to require 'watch' permissions?

### ISSUE THREAD

**Issue by patoarvizu** [operator-framework/operator-sdk#2125]
## Type of question

Desired behavior of a piece of functionality.

## Question

**What did you do?**

I run something like `r.client.Get(context.TODO(), types.NamespacedName{Name: "name", Namespace: "namespace"}, resource)` (the hard-coded names and namespaces are on purpose, since I'm looking for a specific resource). The operator's role looks like:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - list
```
I tried this with both `Role` and `ClusterRole`.

**What did you expect to see?**
That the operator doesn't require `watch` permissions to run `r.client.Get()`

**What did you see instead? Under which circumstances?**
I get something like `Failed to watch *v1.ConfigMap: unknown (get configmaps)`

**Environment**
* operator-sdk version:

`operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 darwin/amd64"`

* Kubernetes version information:

`Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4-k3s.1", GitCommit:"a7531b1ab3fd5ff987b074472ddfb84a2f5326bc", GitTreeState:"clean", BuildDate:"2019-09-19T22:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

A [k3s](https://github.com/rancher/k3s) cluster that I'm running locally, deployed with [k3d](https://github.com/rancher/k3d).

**Additional context**

None

**Comment by patoarvizu** [comment]
And maybe somewhat related to this: I'm trying to run an operator that watches existing resources (`ServiceAccount`s in my case) across all namespaces (setting `WATCH_NAMESPACE = ""`), but read its own configuration from a `ConfigMap` on the specific namespace where it's running, but when it tries to read it, I see `Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:vault:operator" cannot list resource "configmaps" in API group "" at the cluster scope`. I have to set the permissions on a `ClusterRole` for this to work.

If I set:
```
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```
It works as expected.

I'm not sure if this is a Kubernetes RBAC issue or an operator-sdk concern, but I thought it was relevant.
