### ISSUE TITLE
Add vars support to ansible watches

### ISSUE THREAD

**Issue by Jamstah** [operator-framework/operator-sdk#2138]
## Feature Request

With ansible watches, you can specify a `playbook` or `role`, but cannot also specify `vars`. With the finalizer, you can also specify `vars`.

In my case, I am creating a number of CRDs with a similar function, it would be good to run them through the same playbook but with different `vars`. If I could specify the `vars` in the watch, it would make it really easy. Instead, I will have to use separate playbooks for each CRD that each call the same roles.

Example `watches.yaml` if vars were supported:
```
---
- version: v1alpha1
  group: example.com
  kind: ManagedNamespace1
  playbook: /opt/ansible/namespace.yml
  vars:
    kind: one
  watchClusterScopedResources: True
  finalizer:
    name: finalizer.example.com
    playbook: /opt/ansible/destroy.yml
- version: v1alpha1
  group: example.com
  kind: ManagedNamespace2
  playbook: /opt/ansible/namespace.yml
  vars:
    kind: two
  watchClusterScopedResources: True
  finalizer:
    name: finalizer.example.com
    playbook: /opt/ansible/destroy.yml
```
