### ISSUE TITLE
Use imported struct in OpenAPI definition

### ISSUE THREAD

**Issue by jthomperoo** [operator-framework/operator-sdk#2193]
## Type of question

How to implement a feature/possible bug?.

## Question

**What did you do?**
I updated my CRD `_types.go` file with an imported type, e.g:
```go
import (
	autoscaling "k8s.io/api/autoscaling/v1"
)
...
type CustomPodAutoscalerSpec struct {
	// ScaleTargetRef defining what the Custom Pod Autoscaler should manage
	ScaleTargetRef autoscaling.CrossVersionObjectReference `json:"scaleTargetRef"`
}
```

This object is imported from `autoscaling.CrossVersionObjectReference`:
```go
// CrossVersionObjectReference contains enough information to let you identify the referred resource.
type CrossVersionObjectReference struct {
    // Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
    Kind string `json:"kind" protobuf:"bytes,1,opt,name=kind"`
    // Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names
    Name string `json:"name" protobuf:"bytes,2,opt,name=name"`
    // API version of the referent
    // +optional
    APIVersion string `json:"apiVersion,omitempty" protobuf:"bytes,3,opt,name=apiVersion"`
}
```
As you can see it has JSON struct tags.

**What did you expect to see?**
I expected the CRD YAML generated by `operator-sdk generate k8s` and `operator-sdk generate openapi` to have JSON properties in it, i.e.
```
scaleTargetRef:
  description: ScaleTargetRef defining what the Custom Pod Autoscaler should manage
  properties:
    apiVersion:
      description: API version of the referent
      type: string
    kind:
      description: 'Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"'
      type: string
    name:
      description: 'Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names'
      type: string
  required:
  - kind
  - name
  type: object
```

**What did you see instead? Under which circumstances?**
Instead it generates a field with the type object and no properties:
```
scaleTargetRef:
  description: ScaleTargetRef defining what the Custom Pod Autoscaler should manage
  type: object
```
I also found a workaround, if I assign the imported type to a type in the `_types.go` file it generates correctly, however this only generates the top level, and if the object itself uses other structs it doesn't generate the YAML for them.
e.g.
```go
import (
	autoscaling "k8s.io/api/autoscaling/v1"
)

// ScaleTargetRef defines a resource to target
type ScaleTargetRef autoscaling.CrossVersionObjectReference

// CustomPodAutoscalerSpec defines the desired state of CustomPodAutoscaler
// +k8s:openapi-gen=true
type CustomPodAutoscalerSpec struct {
	// ScaleTargetRef defining what the Custom Pod Autoscaler should manage
	ScaleTargetRef ScaleTargetRef `json:"scaleTargetRef"`
}
```
This generates the YAML as I expected it to.

**Environment**
* operator-sdk version:

  operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170

**Additional context**
Sorry if there is some documentation I've missed, I wasn't sure if I should raise it as a question or as a bug - I wasn't sure if it was expected behaviour.
