### ISSUE TITLE
Websocket requests are not proxied correctly in Ansible-based operators

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk#2204]
## Bug Report

**What did you do?**

I am trying to an Ansible `k8s_exec` module, which allows running the equivalent of `kubectl exec` commands to exec a command on a Pod via Ansible through the Python Kubernetes library. This allows me to write a task like:

```yaml
- name: Test a simple command.
  k8s_exec:
    namespace: '{{ meta.namespace }}'
    pod: '{{ tower_pod_name }}'
    command: date
```

Instead of installing `kubectl` on my operator image (added `COPY --from=lachlanevenson/k8s-kubectl:v1.16.2 /usr/local/bin/kubectl /usr/local/bin/kubectl` to my `build/Dockerfile`) and writing a task like:

```yaml
- name: Test kubectl exec.
  command: >
    kubectl exec -n {{ meta.namespace }} {{ tower_pod_name }} date
```

**What did you expect to see?**

When I run the same task as above on my system Ansible against a Kubernetes cluster, or even inside of the operator Pod's ansible container using `ansible-playbook` to run it, it executes successfully and registers the result of the command that was executed.

**What did you see instead? Under which circumstances?**

When it is run via the operator/`ansible-runner` using the operator's proxy, it results in the following error:

```
kubernetes.client.rest.ApiException: (0)
Reason: Handshake status 200 OK
```

It should be getting a `101` response from the Kubernetes API websocket.

Full error message from the failed task:

```
TASK [tower : Test a simple command.] ******************************************
task path: /opt/ansible/roles/tower/tasks/main.yml:38
 line 136, in <module>\n  File \"/tmp/ansible_k8s_exec_payload_x8PPAd/__main__.py\", line 123, in main\n  File \"/usr/lib/python2.7/site-packages/kubernetes/stream/stream.py\", line 32, in stream\n    return func(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py\", line 835, in connect_get_namespaced_pod_exec\n    (data) = self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py\", line 935, in connect_get_namespaced_pod_exec_with_http_info\n    collection_formats=collection_formats)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 321, in call_api\n    _return_http_data_only, collection_formats, _preload_content, _request_timeout)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 155, in __call_api\n    _request_timeout=_request_timeout)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/str
eam/stream.py\", line 27, in _intercept_request_call\n    return ws_client.websocket_call(config, *args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/stream/ws_client.py\", line 255, in websocket_call\n    raise ApiException(status=0, reason=str(e))\nkubernetes.client.rest.ApiException: (0)\nReason: Handshake status 200 OK\n\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Environment**
* operator-sdk version:

v0.11.0

* go version:

N/A

* Kubernetes version information:

1.16.2

* Kubernetes cluster kind: 

Molecule

* Are you writing your operator in ansible, helm, or go?

ansible

**Possible Solution**

N/A

**Additional context**

Relates to: https://github.com/geerlingguy/tower-operator/issues/5

**Comment by geerlingguy** [comment]
Note that using `kubectl exec` works fine inside the operator, even if I set the `KUBECONFIG` environment variable to the same as the ansible tasks are using with:

```yaml
- name: Test kubectl exec.
  command: >
    kubectl exec -n {{ meta.namespace }} {{ tower_pod_name }} date
  environment:
    KUBECONFIG: '{{ lookup("env", "KUBECONFIG") }}'
```
