### ISSUE TITLE
Scorecard: Basic Tests fail with 'olm-deployed' option set to true

### ISSUE THREAD

**Issue by jeyaramashok** [operator-framework/operator-sdk#2271]
## Bug Report

Scorecard basic tests fail with error `unrecognized install strategy` _(olm-test plugin runs successfully)_

**What did you do?**

I tried to follow steps in [Running the scorecard with an OLM-managed operator](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#running-the-scorecard-with-an-olm-managed-operator). I fixed the CSV to add scorecard proxy container to deployment and now my operator runs with the additional scorecard container

```
$ k get pods
NAME                                READY   STATUS    RESTARTS   AGE
example-manifests-nshvq             1/1     Running   0          74m
pingpong-operator-9bc967b6c-t7hb4   3/3     Running   1          68m
$ k get pods pingpong-operator-9bc967b6c-t7hb4 -o jsonpath="{.spec.containers[*].image}"
xyz/pingpong-operator:v0.1.4 xyz/pingpong-operator:v0.1.5 quay.io/operator-framework/scorecard-proxy:master⏎
```

When I run scorecard test with `olm-deployed:true`, the basic test plugin fails. The olm-integration runs successfully though. 

The [documentation](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#basic-and-olm) says `olm-deployed:true` is valid for both basic and olm plugins

**What did you expect to see?**

All tests should pass

**What did you see instead? Under which circumstances?**
```
$ operator-sdk scorecard --verbose
DEBU[0000] Debug logging is set
{
  "kind": "ScorecardOutput",
  "apiVersion": "osdk.openshift.io/v1alpha2",
  "metadata": {
    "creationTimestamp": null
  },
  "log": "time=\"2019-11-26T11:47:50-06:00\" level=info msg=\"Using config file: /Users/jey/workspace/go/src/github.ibm.com/jashokr/pingpong-operator/.osdk-scorecard.yaml\"\ntime=\"2019-11-26T11:47:50-06:00\" level=error msg=\"Plugin `Basic Tests` failed with error (unrecognized install strategy)\"\n",
  "results": [
    {
      "name": "Status fields with descriptors",
      "description": "All status fields have matching descriptors in the CSV",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass"
    },
    {
      "name": "Provided APIs have validation",
      "description": "All CRDs have an OpenAPI validation subsection",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass"
    },
    {
      "name": "Owned CRDs have resources listed",
      "description": "All Owned CRDs contain a resources subsection",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass",
      "suggestions": [
        "If it would be helpful to an end-user to understand or troubleshoot your CR, consider adding resources [configmaps/v1 pingpongs/v1alpha1 replicasets/v1 deployments/v1 services/v1 pods/v1] to the resources section for owned CRD Pingpong"
      ]
    },
    {
      "name": "CRs have at least 1 example",
      "description": "The CSV's metadata contains an alm-examples section",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass"
    },
    {
      "name": "Spec fields with descriptors",
      "description": "All spec fields have matching descriptors in the CSV",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass"
    }
  ]
}
```

scorecard config.yaml
```yaml
scorecard:
  output: json
  plugins:
    - basic:
        cr-manifest:
         - "deploy/crds/jey.com_v1alpha1_pingpong_cr.yaml"
        olm-deployed: true
        csv-path: "deploy/olm-catalog/pingpong-operator/0.1.0/pingpong-operator.v0.1.0.clusterserviceversion.yaml"
        init-timeout: 90
    - olm:
        cr-manifest:
          - "deploy/crds/jey.com_v1alpha1_pingpong_cr.yaml"
        olm-deployed: true
        csv-path: "deploy/olm-catalog/pingpong-operator/0.1.0/pingpong-operator.v0.1.0.clusterserviceversion.yaml"
        init-timeout: 90
```

**Environment**
* operator-sdk version:  "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.4 darwin/amd64"

* go version:  go1.13.4 darwin/amd64

* Kubernetes version information: Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+868bc38", GitCommit:"868bc38", GitTreeState:"clean", BuildDate:"2019-10-22T23:38:21Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: NA

* Are you writing your operator in ansible, helm, or go? ansible

**Possible Solution**

The [code](https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/plugins/plugin_runner.go#L129) currently reads the CSV only for OLM plugin, but I think it should be when olmDeployed is enabled

Created a PR https://github.com/operator-framework/operator-sdk/pull/2274 which worked for me

```yaml
$ operator-sdk scorecard --verbose
DEBU[0000] Debug logging is set
{
  "kind": "ScorecardOutput",
  "apiVersion": "osdk.openshift.io/v1alpha2",
  "metadata": {
    "creationTimestamp": null
  },
  "log": "time=\"2019-11-26T12:21:18-06:00\" level=info msg=\"Using config file: /Users/jey/workspace/go/src/github.ibm.com/jashokr/pingpong-operator/.osdk-scorecard.yaml\"\n",
  "results": [
    {
      "name": "Spec Block Exists",
      "description": "Custom Resource has a Spec Block",
      "labels": {
        "necessity": "required",
        "suite": "basic"
      },
      "state": "pass"
    },
    {
      "name": "Status Block Exists",
      "description": "Custom Resource has a Status Block",
      "labels": {
        "necessity": "required",
        "suite": "basic"
      },
      "state": "pass"
    },
    {
      "name": "Writing into CRs has an effect",
      "description": "A CR sends PUT/POST requests to the API server to modify resources in response to spec block changes",
      "labels": {
        "necessity": "required",
        "suite": "basic"
      },
      "state": "pass"
    },
    {
      "name": "Provided APIs have validation",
      "description": "All CRDs have an OpenAPI validation subsection",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass"
    },
    {
      "name": "Owned CRDs have resources listed",
      "description": "All Owned CRDs contain a resources subsection",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass",
      "suggestions": [
        "If it would be helpful to an end-user to understand or troubleshoot your CR, consider adding resources [replicasets/v1 deployments/v1 services/v1 pods/v1 configmaps/v1 pingpongs/v1alpha1] to the resources section for owned CRD Pingpong"
      ]
    },
    {
      "name": "CRs have at least 1 example",
      "description": "The CSV's metadata contains an alm-examples section",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass"
    },
    {
      "name": "Spec fields with descriptors",
      "description": "All spec fields have matching descriptors in the CSV",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass"
    },
    {
      "name": "Status fields with descriptors",
      "description": "All status fields have matching descriptors in the CSV",
      "labels": {
        "necessity": "required",
        "suite": "olm"
      },
      "state": "pass"
    }
  ]
}
```

**Additional context**
