### ISSUE TITLE
finalizer is not defaulting to the top level ansible role

### ISSUE THREAD

**Issue by wfindley** [operator-framework/operator-sdk#2286]
## Bug Report

**What did you do?**
I made a `watches.yaml` file very much like this: 
```
---
- version: v1alpha1
  group: mycoolorg.com
  kind: Mycoolapp
  role: /opt/ansible/roles/mycoolapp
  finalizer:
    name: finalizer.mycoolapps.mycoolorg.com
```

**What did you expect to see?**

https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/finalizers.md#role
describes that 
>  If role is not provided, it will default to the role specified at the top level of the watches.yaml entry.

I expected `/opt/ansible/roles/mycoolapp` to be used.

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

I got an error like this:

```
{"level":"error","ts":1575317467.4597213,"logger":"cmd","msg":"Failed to load watches.","Namespace":"","error":"must specify Role or Playbook","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:94\ngithub.com/operator-framework/operator-sdk/cmd/operator-sdk/run.newRunAnsibleCmd.func1\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/run/ansible.go:38\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/main.go:84\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.3.linux.amd64/src/runtime/proc.go:203"}
Error: must specify Role or Playbook
```
**Environment**
* operator-sdk version:
I was using this container
quay.io/operator-framework/ansible-operator:v0.12.0
( https://quay.io/repository/operator-framework/ansible-operator/manifest/sha256:0cb575a6ee36e3c2091dc82fb334fb94ab71a38207e05145498c569f45c41c47 )
* Are you writing your operator in ansible, helm, or go?

ansible
**Possible Solution**
Rewrite the docs to guide people from expecting the default toplevel role to be used.

**Additional context**
I fixed it by rewriting my `watches.yaml` with an explicit value for `role` under `finalizer`.

```
---
- version: v1alpha1
  group: mycoolorg.com
  kind: Mycoolapp
  role: /opt/ansible/roles/mycoolapp
  finalizer:
    name: finalizer.mycoolapps.mycoolorg.com
    role: /opt/ansible/roles/mycoolapp
```
