### ISSUE TITLE
CSV file does not include spec.customresourcedefinitions.owned.displayName and spec.customresourcedefinitions.owned.description

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#2292]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

```console
root@gyliu-dev1:~/go/src/github.com/operator-framework/olm-test# kubectl get ip -n marketplace -oyaml
apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1alpha1
  kind: InstallPlan
  metadata:
    creationTimestamp: "2019-12-05T06:46:50Z"
    generateName: install-
    generation: 1
    name: install-spxjc
    namespace: marketplace
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: Subscription
      name: myolm-operator-subsription
      uid: cc58da2c-0c2b-4c0e-b7b5-37c0145ba1df
    resourceVersion: "198621"
    selfLink: /apis/operators.coreos.com/v1alpha1/namespaces/marketplace/installplans/install-spxjc
    uid: 3fc00142-eeae-4908-8688-3ba9a36767d8
  spec:
    approval: Automatic
    approved: true
    clusterServiceVersionNames:
    - memcached-operator.v0.0.1
    source: ""
    sourceNamespace: ""
  status:
    catalogSources:
    - myolm-operators
    conditions:
    - lastTransitionTime: "2019-12-05T06:46:50Z"
      lastUpdateTime: "2019-12-05T06:46:50Z"
      message: 'error creating csv memcached-operator.v0.0.1: ClusterServiceVersion.operators.coreos.com
        "memcached-operator.v0.0.1" is invalid: [spec.customresourcedefinitions.owned.displayName:
        Required value, spec.customresourcedefinitions.owned.description: Required
        value]'
      reason: InstallComponentFailed
      status: "False"
      type: Installed
    phase: Failed
```

The CSV was generated by 0.12 operator-sdk.

```console
root@gyliu-dev1:~/go/src/github.com/operator-framework/olm-test# operator-sdk version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"
```
```
operator-sdk olm-catalog gen-csv --csv-version 0.0.1 --update-crds
```

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cache.example.com/v1alpha1",
          "kind": "Memcached",
          "metadata": {
            "name": "example-memcached"
          },
          "spec": {
            "size": 4
          }
        }
      ]
    capabilities: Basic Install
  name: memcached-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned: <<<<< Here, no displayName and description
    - kind: Memcached
      name: memcacheds.cache.example.com
      version: v1alpha1
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:

```console
root@gyliu-dev1:~/go/src/github.com/operator-framework/olm-test# operator-sdk version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"
```

* go version:
```console
root@gyliu-dev1:~/go/src/github.com/operator-framework/olm-test# go version
go version go1.13 linux/amd64
```

* Kubernetes version information:

```console
root@gyliu-dev1:~/go/src/github.com/operator-framework/olm-test# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-16T01:01:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

```console
root@gyliu-dev1:~/go/src/github.com/operator-framework/olm-test# kind version
kind v0.6.0 go1.13.4 linux/amd64
```

* Are you writing your operator in ansible, helm, or go?
Go

**Possible Solution**

**Additional context**

**Comment by gyliu513** [comment]
FYI @clyang82

**Comment by camilamacedo86** [comment]
Hi @gyliu513, 

In the 0.12, the operator-sdk command is not generating the owned metadata info. See that implementation to attend this need is already done and merged in the master https://github.com/operator-framework/operator-sdk/pull/1162. Then, it will be in the next release.

Also, see that the docs are highlighting that this command will NOT gen all required info and point yu to know how to check what is required. 

> Several fields must be updated after generating the CSV. See the CSV generation doc for a list of [required fields](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/generating-a-csv.md#csv-fields),...

Ref.: https://github.com/operator-framework/getting-started#manage-the-operator-using-the-operator-lifecycle-manager

Additionally, I'd recommend you check some examples in the [upstream-community-operators](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators) to see how you could/should do it. 

In this way, I understand that we can close this issue as sorted out. However, please feel free to re-open if you see that is required.

**Comment by gyliu513** [comment]
Thanks @camilamacedo86 , but `Several fields` is a bit difficult to understand, the end user do not know which field they need to input.

As now we already know that only `spec.customresourcedefinitions.owned.displayName` and `spec.customresourcedefinitions.owned.description` are missed, shall we highlight this in the document that only those two fields are needed?

**Comment by camilamacedo86** [comment]
Hi @gyliu513, 

Regards the docs, if you click on the link added above which is in the doc you see all required fields detailed documented. See: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/generating-a-csv.md#csv-fields

Regards the `spec.customresourcedefinitions.owned` if you use the master they will be generated. Regards the name and display fields, see that when you run the command a WARN appears in the output in order to notify that they are required. 
 
However, you are also welcome to collab with any doc improvement that you think that should be great. Please, let us know if you are ok with.

**Comment by gyliu513** [comment]
Thanks @camilamacedo86 , I was a bit confused by the document, the code and my CSV file, let me explain:

My CSV file `owned` only request the following fields and it works:

```yaml
customresourcedefinitions:
    owned:
    - kind: Memcached
      name: memcacheds.cache.example.com
      version: v1alpha1
      description: Placeholder description
      displayName: Memcached Operator
```

But the https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/generating-a-csv.md#csv-fields here, says the following fields are required for `owned`:

* `owned`: all CRDs the Operator deploys itself from it's bundle.
        * `name`: CRD's `metadata.name`.
        * `kind`: CRD's `metadata.spec.names.kind`.
        * `version`: CRD's `metadata.spec.version`.
        * `description` _(user)_ : description of the CRD.
        * `resources` _(user)_ : any Kubernetes resources used by the CRD, ex. `Pod`'s and `ConfigMap`'s.
        * `specDescriptors` _(user)_ : UI hints for inputs and outputs of the Operator's spec.
        * `statusDescriptors` _(user)_ : UI hints for inputs and outputs of the Operator's status.

But my CSV file does not have the field like `resources`, `specDescriptors` and `statusDescriptors`, am I missing anything?

I also check code at https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/api/apis/operators/clusterserviceversion_types.go#L74-L83 , seems the struct does not mention which field is required and which is optional. Comments? Thanks!
