### ISSUE TITLE
Does operator-sdk support additional printer columns?

### ISSUE THREAD

**Issue by yeya24** [operator-framework/operator-sdk#2351]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**

I want to add additional printer columns in my crds. I saw kubebuilder supports this feature, https://book.kubebuilder.io/reference/generating-crd.html#additional-printer-columns. 
I am wondering how to set this in operator-sdk? Currently the only way I find is to add these configurations in the crd file.

**Comment by joelanford** [comment]
@yeya24 Operator SDK uses the same underlying tool as kubebuilder to generate CRDs (controller-tools). Have you tried using the kubebuilder annotations for additional printer columns and then running the `operator-sdk generate crds` subcommand?

**Comment by thegridman** [comment]
It does support additional printer columns, we use it in our CRDs (we're on operator-sdk 0.13.0 but it worked in earlier versions). For example we have the following Go struct:
```
// CoherenceRole is the Schema for the coherenceroles API
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
// +kubebuilder:subresource:scale:specpath=.spec.replicas,statuspath=.status.replicas,selectorpath=.status.selector
// +kubebuilder:categories=coherence
// +kubebuilder:resource:shortName=cohrole
// +kubebuilder:printcolumn:name="Role",type="string",JSONPath=".spec.role",description="The name of this role"
// +kubebuilder:printcolumn:name="Cluster",type="string",JSONPath=".metadata.labels.coherenceCluster",description="The name of the Coherence cluster that this role belongs to"
// +kubebuilder:printcolumn:name="Replicas",type="integer",JSONPath=".spec.replicas",description="The number of Coherence Pods for this role"
// +kubebuilder:printcolumn:name="Ready",type="integer",JSONPath=".status.readyReplicas",description="The number of ready Coherence Pods for this role"
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status",description="The status of this role"
type CoherenceRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CoherenceRoleSpec   `json:"spec,omitempty"`
	Status CoherenceRoleStatus `json:"status,omitempty"`
}
```

Which generates a CRD with this in it:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: coherenceroles.coherence.oracle.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.role
    description: The name of this role
    name: Role
    type: string
  - JSONPath: .metadata.labels.coherenceCluster
    description: The name of the Coherence cluster that this role belongs to
    name: Cluster
    type: string
  - JSONPath: .spec.replicas
    description: The number of Coherence Pods for this role
    name: Replicas
    type: integer
  - JSONPath: .status.readyReplicas
    description: The number of ready Coherence Pods for this role
    name: Ready
    type: integer
  - JSONPath: .status.status
    description: The status of this role
    name: Status
    type: string
  group: coherence.oracle.com
  names:
    kind: CoherenceRole
    listKind: CoherenceRoleList
    plural: coherenceroles
    shortNames:
    - cohrole
    singular: coherencerole
  scope: Namespaced
```
