### ISSUE TITLE
Getting error while creating a basic operator. 

### ISSUE THREAD

**Issue by chowmean** [operator-framework/operator-sdk#2371]
## Type of question

**Help around the operator-sdk, facing issue while creating one**

## Question

**What did you do?**
Creating a basic operator. When I tried to deploy the application for operator. It gives below error. 
`Error from server (NotFound): error when creating "test.yaml": the server could not find the requested resource (post redises.ice.example.com)`

**What did you expect to see?**
Resource should be redis.ice.example.com. Why it says redises? Operator is running but not able to deploy app of kind Redis. 

**Environment**
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.4 darwin/amd64"

  insert release or Git SHA here

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-18T20:30:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

**Additional context**
**Below is the CRD**
```apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redis.ice.example.com
spec:
  group: ice.example.com
  names:
    kind: Redis
    listKind: RedisList
    plural: redis
    singular: redis
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Redis is the Schema for the redis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RedisSpec defines the desired state of Redis
          type: object
        status:
          description: RedisStatus defines the observed state of Redis
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
```

**YAML to create application**
```apiVersion: ice.example.com/v1alpha1
kind: Redis
metadata:
  name: example-redis
spec:
  # Add fields here
  size: 3
```

**YAML for Operator**
```apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-operator
  template:
    metadata:
      labels:
        name: redis-operator
    spec:
      serviceAccountName: redis-operator
      containers:
        - name: redis-operator
          # Replace this with the built image name
          image: chowmean/redis-operator
          command:
          - redis-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "redis-operator"
```

**Comment by camilamacedo86** [comment]
Hi @chowmean, 

The error shows that you are trying to apply/create a CR which has not its definition in the cluster.

> error when creating "test.yaml": the server could not find the requested resource (post redises.ice.example.com) 

So, have you applied the CRD which defines it? 
Also, note that your CR is missing the apiVersion:

> kind: Redis
> metadata:
>   name: example-redis
> spec:
>   # Add fields here
>   size: 3

See an example of a valid CR [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/deploy/crds/cache.example.com_v1alpha1_memcached_cr.yaml#L1).

Also, since shows that you are getting started with, I'd like to share with you the following links which I hope that helps you. 

- [Getting Started Tutorial](https://github.com/operator-framework/getting-started)
- [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/)
- [Samples Repo (examples)](https://github.com/operator-framework/operator-sdk-samples)

Please, let us know if the information provided help you with and we can close this one.

**Comment by chowmean** [comment]
Sorry I missed the line
This is the CR that I used.
```
apiVersion: ice.olacabs.com/v1alpha1
kind: Redis
metadata:
  name: example-redis
spec:
  # Add fields here
  size: 3
```

This is the CRD that I applied to kubernetes server. 
```
kind: CustomResourceDefinition
metadata:
  name: redis.ice.example.com
spec:
  group: ice.example.com
  names:
    kind: Redis
    listKind: RedisList
    plural: redis
    singular: redis
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Redis is the Schema for the redis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RedisSpec defines the desired state of Redis
          type: object
        status:
          description: RedisStatus defines the observed state of Redis
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
```

I am trying to create a redis kind of object but it is showing plural error like redises is not found.

**Comment by camilamacedo86** [comment]
Hi @chowmean, 

If you check the plural metadata in the CRD needs to be gen with the Kind in the plural. See: https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml#L10

I did a local test with SDK and it was gen as your example `plural: redis`.

What is the k8s vendor and version that you are using? I am setting up minikube locally to check the data gen by SDK as well and I will let you know.

**Comment by chowmean** [comment]
Yes and that is not happening. Below is the env info. 
**operator-sdk version**: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.4 darwin/amd64"

**Kubernetes version information:**
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-18T20:30:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by camilamacedo86** [comment]
Hi @chowmean, 

Following the analyse and tests performed.

I did the following steps to create a CR/CRD with the same group and kind by SDK in order to ensure that the data on them as been generated successfully and will be accepted by k8s API.  

1. Create the project and resources

```
$ operator-sdk new app-operator 
$ cd app-operator

# Add a new API for the custom resource Redis
$ operator-sdk add api --api-version=redis.ice.example.com/v1 --kind=Kind
```

2. Applying in the Minikube

```
$ kubectl apply -f deploy/crds/ice.example.com_redis_crd.yaml 
customresourcedefinition.apiextensions.k8s.io/redis.ice.example.com created

$ kubectl apply -f deploy/crds/ice.example.com_v1_redis_cr.yaml 
redis.ice.example.com/example-redis created
```

**See that all worked well which lead to guess that you have an issue your project.**

Following the CR and CRD gen by SDK.

- $ cat deploy/crds/ice.example.com_redis_crd.yaml 

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redis.ice.example.com
spec:
  group: ice.example.com
  names:
    kind: Redis
    listKind: RedisList
    plural: redis
    singular: redis
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Redis is the Schema for the redis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RedisSpec defines the desired state of Redis
          type: object
        status:
          description: RedisStatus defines the observed state of Redis
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
```

- $ cat deploy/crds/ice.example.com_v1_redis_cr.yaml 

```yaml
apiVersion: ice.example.com/v1
kind: Redis
metadata:
  name: example-redis
spec:
  # Add fields here
  size: 3
```

**NOTE** The plural of this kind is `plural: redis`

So, I'd recommend you remove this resource and re-gen then with the SDK. Probably, it suffered some manual change which is causing the issue. Also, you can check all their data and try to find out what is wrong and fix it. 

In this way, I am closing this issue since by using the same data I could not find any issue with the resources gen by the SDK. However, please feel free to re-open if you still needing some help.
