### ISSUE TITLE
Ansible operator support for abort reconcile loops on failure

### ISSUE THREAD

**Issue by TristanCacqueray** [operator-framework/operator-sdk#2431]
## Feature Request

**Is your feature request related to a problem? Please describe.**
This is a followup from https://github.com/operator-framework/operator-sdk/issues/2372 , where that issue was actually quite convenient during development where the reconcile loop stops when Ansible fails unexpectedly.

**Describe the solution you'd like**
It would be nice if the watches.yaml file would let us toggle that behavior, for example by using a `strict` or `any_errors_fatal` attribute. By default this would be false, and when it is true, the reconcile stops on ansible failure.

**Comment by camilamacedo86** [comment]
Hi @TristanCacqueray, 

See that it already exists. You can use the ` ignore_errors: true` in order to flag that if some error in your task is faced then, it should be ignored. 
 
``` yaml
---
- name: set example-memcached namespace to {{ state }}
  k8s:
    api_version: v1
    kind: Namespace
    name: example-memcached
    state: "{{ state }}"
  ignore_errors: true
```

This information is the [user_guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/developer_guide.md), however, please feel free to contribute with its docs if you see that it could be better addressed. 

I am closing this one since all shows sorted out. Feel free to re-open if you see that something still required.
