### ISSUE TITLE
Support for tags for ansible based operators

### ISSUE THREAD

**Issue by jpigottj** [operator-framework/operator-sdk#2444]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an existing playbook which requires tags when invoked and would like to invoke the playbook with an 'install' tag when a CR is created and with 'uninstall' tag when CR is removed.

**Describe the solution you'd like**
Perhaps watches file can be extended to provide support for tags, e.g.
```
- version: v1alpha1
  group: app.example.com
  kind: Database
  playbook: /opt/ansible/playbook.yml
  args: 
    tags:
    - install  
  finalizer:
    name: finalizer.app.example.com
    args:
      tags:
      - uninstall
```
