### ISSUE TITLE
Ansible operator overwrites entire status key

### ISSUE THREAD

**Issue by Cerebus** [operator-framework/operator-sdk#2482]
## Bug Report
**What did you do?**
If an operator updates a CR status field, this change is overridden by the ansible operator when it exits.

E.g.:
```yaml
- name: get resource
  k8s_info:
    api_version: foo.bar/v1alpha1
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    kind: FooBar
  register: resource

- set_fact:
    foo:
      status:
        foobar: some data

- set_fact:
    spec: "{{ resource.resources[0] | combine(foo, recursive=True) }}"

- debug:
    msg: "{{ spec }}"

- name: patch spec with new status data
  k8s:
    state: present
    definition: "{{ spec }}"
```

**What did you expect to see?**
I should see:
```yaml
...
status:
  foobar: some data 
  conditions: 
  - ...
```

**What did you see instead? Under which circumstances?**
The new key:value is lost.

Adding a debug to dump `spec` before the play ends shows the status key and value are present in the new definition, but when getting the resource from `kubectl` the status key contains only the conditions list.

**Environment**
* operator-sdk version:
operator-sdk version: "v0.15.0", commit: "21a93ca379b887ab2303b0d148a399bf205c3231", go version: "go1.13.6 darwin/amd64"

* go version:
N/A

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Docker Desktop/macOS 

* Are you writing your operator in ansible, helm, or go?
ansible

**Possible Solution**
N/A 

**Additional context**
N/A
