### ISSUE TITLE
How to read use a secret in ansible-operator

### ISSUE THREAD

**Issue by MrBasset** [operator-framework/operator-sdk#2510]
## Type of question

Help with Ansible Operator-SDK

## Question

**What did you do?**
I need to pass a secret to my ansible operator that can then be used in the playbook, I have tried passing it both as an environment variable or a file to be ready by the playbook, for example

Operator.yaml
```
    spec:
      serviceAccountName: my-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: my-image:latest
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deployer-secrets
                  key: admin_password
```

ansible-playbook.yaml
```
- hosts: all
  vars:
    admin_user: admin
    admin_password: "{{ lookup('env', 'ADMIN_PASSWORD') }}"
  tasks:
  - name: do stuff
    debug:
      msg: "password is {{ admin_password }}"
```

**What did you expect to see?**
I would expect to see the value passed via the secret used by ansible. If I exec into the container this value is show when I echo ${ADMIN_PASSWORD}, but ansible does not use it. I suspect because ansible is running in a different user session.

I tried to mount the secret and reading it using a lookup "file" but this also didn't work.

**What did you see instead? Under which circumstances?**
As above, the password variable is empty and the play fails.

**Environment**
* operator-sdk version:

0.15.1

* Kubernetes version information:

kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Azure AKS

**Additional context**
Add any other context about the question here.
