### ISSUE TITLE
Ansible: is concurrent execution possible during reconcile loop?

### ISSUE THREAD

**Issue by tomsucho** [operator-framework/operator-sdk#2561]
## Type of question
how to implement a specific feature

## Question
From what I can see in my testing it would appear that playbook execution is serialized for all the related resources. Would it be possible to run playbook in parallel for each of the resources, during reconciliation loop run? The reason I'm asking is, it may take some time to execute a playbook for each and every resource and so we would have to make sure the reconcile interval is long enough to allow playbooks to finish for all the many resources we can have configured? On the other hand long reconcile intervals would make it less "responsive" to changes like new resources apply/delete.

**Comment by djzager** [comment]
Quick aside, in Go-based operators this would be referred to as [`MaxConcurrentReconciles`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L32) and equates to the "maximum number of concurrent Reconciles which can be run. Defaults to 1".

Ansible based operators use this mechanism too, but under the name `MaxWorkers`. You can set via the command line with the `max-workers` argument with something like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-operator
spec:
...
  template:
    metadata:
      labels:
        name: app-operator
    spec:
      serviceAccountName: app-operator
      containers:
        - name: app-operator
          command:
          - app-operator --max-workers 4
```

... and then this is when I found it in the documentation and stopped thinking :sunglasses: 

https://github.com/operator-framework/operator-sdk/blob/7b69502e2f877bc04419e44498d3eff28bf034d4/doc/ansible/dev/advanced_options.md#max-workers
