### ISSUE TITLE
Controller fails on empty manifest files from a Helm Chart

### ISSUE THREAD

**Issue by mphammer** [operator-framework/operator-sdk#2622]
## Bug Report

**What did you do?**
For each of the following cases I did these steps:
1. Created an Operator from a local helm chart:
`$ operator-sdk new my-operator --type=helm --helm-chart <local_helm_chart_path>`
2. Deployed the CRD
`$ kubectl create -f deploy/crds/<resource>_crd.yaml`
3. Started local operator
`$ operator-sdk run --local`
4. Create the CR
`kubectl create -f deploy/crds/<resource>_cr.yaml`

Case 1: A file containing a resource is empty due to a conditional
* myvalue is not set
```
{{ if .Values.myvalue }}
# entire resource goes here
# ...
{{ end }}
```

Case 2: There is an empty manifest from `---` markers
```
---

---
# valid resources go here
# ...
```

**What did you expect to see?**
* The controller ignores the empty resources

**What did you see instead? Under which circumstances?**
Some of the resources were deployed but I saw the following error messages repeatedly printed...
Case 1:
```
{"level":"error",
"ts":1583340099.203393,
"logger":"helm.controller",
"msg":"Release failed",
"namespace":"default",
"name":"example-product",
"apiVersion":"domain.com/v1alpha1",
"kind":"Product",
"release":"example-product",
"error":"failed to install release: no objects visited",
"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/pkg/helm/controller/reconcile.go:194\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
```

Case 2:
```
{"level":"error",
"ts":1583340147.234184,
"logger":"helm.controller",
"msg":"Failed to run release hook",
"namespace":"default",
"name":"example-product",
"apiVersion":"domain.com/v1alpha1",
"kind":"Product",
"release":"example-product",
"error":"no matches for kind \"\" in version \"\"",
"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/pkg/helm/controller/reconcile.go:308\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
```

**Environment**
* operator-sdk version:

```
$ operator-sdk version
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.8 darwin/amd64"
```

* go version:

```
$ go version
go version go1.13.8 darwin/amd64
````

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:43:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.9", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T22:35:02Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Are you writing your operator in ansible, helm, or go?
```
$ helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Possible Solution**
* If a manifest is empty then do not attempt to reconcile it in the cluster

**Additional context**

**Comment by camilamacedo86** [comment]
Hi @mphammer, 

Could you please provide and `-helm-chart <local_helm_chart_path>` which we can use to reproduce your scenario in order to make it more clear? Have you any example from the [stable](https://github.com/helm/charts/tree/master/stable/memcached) repo which would allow us to check/reproduce it? Also, what do you mean with `https://github.com/helm/charts/tree/master/stable/memcached`? Could you please elaborate more?

**Comment by joelanford** [comment]
@mphammer 

Case 1 is actually pretty common in Helm charts. In fact, we coincidentally test this case in the SDK's helm-operator e2e test (check out the ingress template generated from [this command](https://github.com/operator-framework/operator-sdk/blob/5104f530ea7bbfb50f4d2d5888cbdc2f26786906/hack/tests/e2e-helm.sh#L129-L133) in the test).

So I'm fairly certain the Helm operator supports disabling entire resources. Your error seems to indicate that the release contained no resources at all. And in that case, it would make sense to fail an installation.

For case 2, this looks like a legitimate bug. My guess is that it is originating from [here](https://github.com/operator-framework/operator-sdk/blob/ad1d4d1953abf22c336f67198fc23a489c0f4fdb/pkg/helm/controller/controller.go#L127).

We parse each YAML document in the release manifest and assume that we'll find the object meta. In the case of your chart it looks like there are some empty documents, which parse "successfully", but result in an empty object.

Any chance you would be interested in submitting a PR to add some extra sanity checks in that function to make sure that we have a non-empty GVK?

**Comment by mphammer** [comment]
> Hi @mphammer,
> 
> Could you please provide and `-helm-chart <local_helm_chart_path>` which we can use to reproduce your scenario in order to make it more clear? Have you any example from the [stable](https://github.com/helm/charts/tree/master/stable) repo which would allow us to check/reproduce it? Also, what do you mean with `If a manifest is empty then do not attempt to reconcile it in the cluster`? Could you please elaborate more?

Hi @camilamacedo86, 

Sorry for the late response. These errors were not from the stable repo but from a custom helm chart. Here are examples of the Charts:
**Case 1:**
Chart.yaml:
```
apiVersion: v1
name: my-helm-chart
description: A helm chart for me
type: application
version: 1.0.0
appVersion: 2.3.0
```
Values.yaml:
```
resourceProvided: true
```
templates/resource.yaml:
```
{{ if .Values.resourceProvided }}
apiVersion: v1
kind: Service
metadata:
  labels:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port-8443
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    name: {{ .Release.Name }}
  type: ClusterIP
{{ end }}
```

**Case 2:**
Chart.yaml:
```
apiVersion: v1
name: my-helm-chart
description: A helm chart for me
type: application
version: 1.0.0
appVersion: 2.3.0
```
Values.yaml:
```
exposeService: true
```
templates/resource.yaml:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-label
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port-8443
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    name: {{ .Release.Name }}-label
  type: ClusterIP
---
{{ if .Values.exposeService }}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-exposed-label
  name: {{ .Release.Name }}-service-exposed
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port-8443
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    name: {{ .Release.Name }}-exposed-label
  type: LoadBalancer
{{ end }}
---
```
