### ISSUE TITLE
Invalid CRD generated when using pkg/status.Conditions

### ISSUE THREAD

**Issue by kraman** [operator-framework/operator-sdk#2658]
**What did you do?**
* Built operator-sdk from master
* Used `pkg/status.Conditions` in my CRD

**What did you expect to see?**
A valid CRD with status.conditions as a array of condition objects

**What did you see instead? Under which circumstances?**

```
The CustomResourceDefinition "..." is invalid: spec.validation.openAPIV3Schema.properties[status].properties[conditions].items: Required value: must be specified
```

The CRD has an `additionalProperties` under the `conditions` object instead of `items`.

**Environment**
* operator-sdk version: `"v0.15.0-80-g373ebf37", commit: "373ebf3751b61a37f3589687043b0eda095cf156"`

* go version: `go1.14 darwin/amd64`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: kubeadm 1.17

* Are you writing your operator in ansible, helm, or go?

Go

**Comment by camilamacedo86** [comment]
The K8s API is warning you that the syntax used in your CRD is invalid.

`The CustomResourceDefinition "..." is invalid: spec.validation.openAPIV3Schema.properties[status].properties[conditions].items: Required value: must be specified`

I understand that you change it manually and not via the tool. It is recommended define the validations via annotations in the *_types.go and then, gen the CRDS. See : https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#openapi-validation.

Please, let us know if we can close this one and if not please let us know what is missing as provide the snipe code of you CRD and _type.go.

**Comment by kraman** [comment]
@camilamacedo86 I did not modify the CRD directly. I used `operator-sdk generate crds` to do so.
Within my go types file I import `"github.com/operator-framework/operator-sdk/pkg/status` and the status struct has

 ```go
	// Conditions
	// +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors=true
	// +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors.displayName="Conditions"
	Conditions status.Conditions `json:"conditions"`
```

I think something is wrong with how operator-sdk is generating the CRD for this type.

**Comment by camilamacedo86** [comment]
Hi @kraman,
 
>    // Conditions
>    // +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors=true
>    // +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors.displayName="Conditions"
>    Conditions status.Conditions `json:"conditions"`

The above annotations are used to just gen the CSV spec fields and not the CRD. 
The error faced is over the `openAPIV3Schema` in your CRD. I think you are looking in the wrong place.

1. What is the CR applied which is facing the error? 
2. Can you share the full error log? 
3. Can you share its type.go definition? 
4. Can you share its CRD used?

**Comment by joelanford** [comment]
@kraman Can you try adding this comment annotation in your _types.go file:
https://github.com/operator-framework/operator-sdk/blob/14e209e85ba6edf39377bdec55877e6d620f6788/pkg/status/conditions.go#L87

That annotation is declared on the `Conditions` type in the SDK, but maybe there's something weird going on where it needs to be re-declared in `_types.go`.

I'll try to reproduce this myself as well.

**Comment by joelanford** [comment]
Hmm, I'm unable to reproduce.

I did:
1. `operator-sdk new status-operator --repo=example.com/status-operator`
2. `operator-sdk add api --api-version=example.com/v1 --kind=MyApp`
3. Updated `myapp_types.go` to include the `Conditions` field in the `Status` struct with the same comments and `+operator-sdk` annotations
4. Ran `operator-sdk generate k8s` and `operator-sdk generate crds` successfully.

Here's the CRD produced:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: myapps.example.com
spec:
  group: example.com
  names:
    kind: MyApp
    listKind: MyAppList
    plural: myapps
    singular: myapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MyApp is the Schema for the myapps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MyAppSpec defines the desired state of MyApp
          type: object
        status:
          description: MyAppStatus defines the observed state of MyApp
          properties:
            conditions:
              additionalProperties:
                description: "Condition represents an observation of an object's state.
                  Conditions are an extension mechanism intended to be used when the
                  details of an observation are not a priori known or would not apply
                  to all instances of a given Kind. \n Conditions should be added
                  to explicitly convey properties that users and components care about
                  rather than requiring those properties to be inferred from other
                  observations. Once defined, the meaning of a Condition can not be
                  changed arbitrarily - it becomes part of the API, and has the same
                  backwards- and forwards-compatibility concerns of any other part
                  of the API."
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    description: ConditionReason is intended to be a one-word, CamelCase
                      representation of the category of cause of the current status.
                      It is intended to be used in concise output, such as one-line
                      kubectl get output, and in summarizing occurrences of causes.
                    type: string
                  status:
                    type: string
                  type:
                    description: "ConditionType is the type of the condition and is
                      typically a CamelCased word or short phrase. \n Condition types
                      should indicate state in the \"abnormal-true\" polarity. For
                      example, if the condition indicates when a policy is invalid,
                      the \"is valid\" case is probably the norm, so the condition
                      should be called \"Invalid\"."
                    type: string
                required:
                - status
                - type
                type: object
              description: Conditions
              type: array
          required:
          - conditions
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
```

**Comment by joelanford** [comment]
It may also be a Kubernetes version issue. I successfully created that CRD in a Kubernetes 1.16 server. I'll try 1.17 as well.

**Comment by kraman** [comment]
@joelanford if you run the CRD above through openapi validator it will tell you that conditions is of `type: array` and so should have an `items` property in it. `additionalProperties` is only valid for `type: object`

**Comment by kraman** [comment]
also, adding `// +kubebuilder:validation:Type=array` to my go types file did not change anything.

**Comment by camilamacedo86** [comment]
HI @kraman, 

Could you please provide? Note that the annotations used by you have no relation with open API issue faced and/or the values gen in the CR. 

1. What is the CR applied which is facing the error?
2. Can you share the full error log?
3. Can you share its type.go definition?
4. Can you share its CRD used?

**Comment by kraman** [comment]
@camilamacedo86 yes I realize. I don't think I need to create any annotations on my types go file because the issue is related to annotations in the `pkg/status/conditions.go` file. 

Based on what I see in  https://github.com/operator-framework/operator-sdk/issues/2658#issuecomment-599591747, @joelanford has already recreated the problem.

K8s 1.16 doesn't error on this but 1.17 does.

full error:
```sh
sample-operator ➤ kubectl apply -f deploy/crds/sample.example.com_samplecluster_crd.yaml
The CustomResourceDefinition "sampleclusters.sample.example.com" is invalid: spec.validation.openAPIV3Schema.properties[status].properties[conditions].items: Required value: must be specified
```

I am reluctant to share my types file due to IP issues right now but since it has already been repro'd above it may no longer be necessary to do so. I will work on clean recreation if @joelanford 's repro above is insufficient.

**Comment by joelanford** [comment]
@kraman Thanks for confirming that it seems to be an issue with tighter validations in Kubernetes 1.17.

This may be something we can fix in the operator-sdk repo, by adding more kubebuilder annotations to the `pkg/status/conditions.go` file, but I need to experiment to know for sure. In the meantime, you may be able to work around it by adding validation annotations in your types.go file.

It's also possible that there is a missing feature and/or bug in the controller-tools project that we'll need. As you can see, the `Conditions` type is not _actually_ a slice of conditions, so it seems like the go types parser isn't quite handling this case properly.

**Comment by kraman** [comment]
Thanks @joelanford Ive worked around the problem by patching the CRD for now.

**Comment by camilamacedo86** [comment]
HI @kraman and @joelanford, 

I am testing it with 1.17. Following the steps and SDK 0.16. 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:40:44Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```


On top of the Memcached Go Sample I added the following spec:

```go
type MemcachedSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html

	// Size is the size of the memcached deployment
	Size int32 `json:"size"`

	Conditions status.Conditions `json:"conditions"`
}
```

Then, run : 

- Run the command `operator-sdk generate k8s` to ensure that your resources will be updated
- Run the command `operator-sdk generate crds` to regenerate CRDs
- Run the command `operator-sdk build $IMAGE` and `docker push $IMAGE` to test it

The error faced when the CR is applied is: 

> The Memcached "example-memcached" is invalid: spec.conditions: Required value

**Which is expected since the  `spec.conditions` was not added in the CR.** 

Then, if I add the status conditions in the CR. See:

```
apiVersion: cache.example.com/v1alpha1
kind: Memcached
metadata:
  name: example-memcached
spec:
  # Add fields here
  size: 3
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-03-19T12:47:25Z"
      status: "True"
      type: Initialized

```

It is applied with success. 

> kubectl apply -f deploy/crds/cache.example.com_v1alpha1_memcached_cr.yaml -n memcached
> memcached.cache.example.com/example-memcached created

So, I still unable to reproduce the issue raised here.Also, it is important to highloght: 

**The `operator-sdk:gen-csv` will NOT affect change the CRD since they are used to gen the CSV (has no relation with it at all)**

// +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors=true
// +operator-sdk:gen-csv:customresourcedefinitions.statusDescriptors.displayName="Conditions"

**The `// +kubebuilder:validation:Type=array` will NOT affect and change the CRD. 

The `// +kubebuilder:validation:` is not valid for SDK. It is ignored. 

<img width="1553" alt="Screenshot 2020-03-19 at 12 41 34" src="https://user-images.githubusercontent.com/7708031/77068745-fd353400-69de-11ea-854c-66286230105b.png">

- So, could you please describe what was done to reproduce the `is invalid: spec.validation.openAPIV3Schema.properties[status].properties[conditions].items: Required value: must be specified`? 

- Could you please upgrade your project to use the SDK version 0.16 and let us know ?  See: The Memcached GO sample PR to upgrade to use 0.16: https://github.com/operator-framework/operator-sdk-samples/pull/116 and the Migration guide for it: https://github.com/operator-framework/operator-sdk/blob/3e211aa365510b7e33be72e5ba481d375abf6d66/doc/migration/version-upgrade-guide.md#v016x.

PS.: I tried the same by adding it in the STATUS and did not see the issue as well.

**Comment by camilamacedo86** [comment]
The POC is here: https://github.com/camilamacedo86/operator-sdk-samples/tree/test-issue

**Comment by camilamacedo86** [comment]
The POC is here: https://github.com/camilamacedo86/operator-sdk-samples/tree/test-issue/go/memcached-operator

**Comment by camilamacedo86** [comment]
Hi @kraman, 

It is important to highlight that @joelanford was unable to reproduce your issue too. See:

<img width="970" alt="Screenshot 2020-03-19 at 13 50 00" src="https://user-images.githubusercontent.com/7708031/77074360-ab91a700-69e8-11ea-820f-6944bf69d9d2.png">
<img width="917" alt="Screenshot 2020-03-19 at 13 49 56" src="https://user-images.githubusercontent.com/7708031/77074368-acc2d400-69e8-11ea-8903-1ac1a18c6716.png">

PS.: I checked it with him as well. He tested it 1.16 and all worked but he did not try in 1.17 as I did above. However, note that I am unable to reproduce it in 1.17 or 1.16.

So, could you please provide the following information for we are able to help you with:

- The _type.go implementation of this CRD
- The CRD that you are using and facing this issue. 

Thank you for your attention.

**Comment by joelanford** [comment]
This looks like the change the made the tighter validations in 1.17: https://github.com/kubernetes/kubernetes/pull/85223

**Comment by joelanford** [comment]
To me, it's pretty clearly a bug on our side somewhere (either in controller-tools or our annotations on the `status.Conditions` type).

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

Thank you for share. I still unable to reproduce it with SDK features and I will check it in Kubebuilder/controller-tools as well. 

Because of this, IMO would be very needed and helpful the user provides their _type implementation as CRD as requested at the first moment. Otherwise, we need to try to find out and discover what they are using, what was done and etc as guessing by the error their output which makes the things very harder unnecessarily. 

Also, note that we deprecated the openapi. See: 

- https://github.com/operator-framework/operator-sdk/blob/762b0d44af6e0db61b9e8fda09cea3cddaae2ae8/CHANGELOG.md#deprecated-4 

I am working on it in order to try to find out anyway.

**Comment by joelanford** [comment]
Hmm. I was finally able to also test on 1.17 and like @camilamacedo86, I'm not able to reproduce. The CRD from [here](https://github.com/operator-framework/operator-sdk/issues/2658#issuecomment-599591747) applies cleanly on a minikube 1.17.3 cluster.

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by joelanford** [comment]
Okay, progress!

@camilamacedo86 was able to reproduce the issue by adding an additional, unrelated field to the status.


<details>
    <summary>Here's a CRD that reproduces the issue</summary>

```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: memcacheds.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: Memcached
    listKind: MemcachedList
    plural: memcacheds
    singular: memcached
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Memcached is the Schema for the memcacheds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MemcachedSpec defines the desired state of Memcached
          properties:
            size:
              description: Size is the size of the memcached deployment
              format: int32
              type: integer
          required:
          - size
          type: object
        status:
          description: MemcachedStatus defines the observed state of Memcached
          properties:
            conditions:
              additionalProperties:
                description: "Condition represents an observation of an object's state.
                  Conditions are an extension mechanism intended to be used when the
                  details of an observation are not a priori known or would not apply
                  to all instances of a given Kind. \n Conditions should be added
                  to explicitly convey properties that users and components care about
                  rather than requiring those properties to be inferred from other
                  observations. Once defined, the meaning of a Condition can not be
                  changed arbitrarily - it becomes part of the API, and has the same
                  backwards- and forwards-compatibility concerns of any other part
                  of the API."
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    description: ConditionReason is intended to be a one-word, CamelCase
                      representation of the category of cause of the current status.
                      It is intended to be used in concise output, such as one-line
                      kubectl get output, and in summarizing occurrences of causes.
                    type: string
                  status:
                    type: string
                  type:
                    description: "ConditionType is the type of the condition and is
                      typically a CamelCased word or short phrase. \n Condition types
                      should indicate state in the \"abnormal-true\" polarity. For
                      example, if the condition indicates when a policy is invalid,
                      the \"is valid\" case is probably the norm, so the condition
                      should be called \"Invalid\"."
                    type: string
                required:
                - status
                - type
                type: object
              description: Conditions is a set of Condition instances.
              type: array
            nodes:
              description: Nodes are the names of the memcached pods
              items:
                type: string
              type: array
              x-kubernetes-list-type: set
          required:
          - conditions
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
```
</details>

The issue can be resolved by either:
1. Replacing `additionalProperties` with `items` in the `conditions` validation (this seems like the correct fix)
2. Removing `nodes` entirely from the validation (this seems like it shouldn't matter, so probably a bug in the kubernetes component that validates CRDs)
