### ISSUE TITLE
`generate crds` generates crd not compatible with kube 1.11

### ISSUE THREAD

**Issue by itdove** [operator-framework/operator-sdk#2659]
## Bug Report

**What did you do?**
Run `operator-sdk generate crds`

**What did you expect to see?**
If the status is defined, the type: object shouldn't.

```
properties:
  apiVersion: ...
  kind: ...
  metadata: ...
  spec: ...
  status: ...
```

**What did you see instead? Under which circumstances?**
```
properties:
  apiVersion: ...
  kind: ...
  metadata: ...
  spec: ...
  status: ...
  type: object
```

if I apply that crd I get the error: 
```
...xternalDocs:(*apiextensions.ExternalDocumentation)(nil), Example:(*apiextensions.JSON)(nil)}: must only have \"properties\", \"required\" or \"description\" at the root if the status subresource is enabled"}

```

**Environment**
* operator-sdk version: 0.15.2

* Kubernetes version information:

*  kubernetes: 1.11

* Kubernetes cluster kind: OCP 3.11

* Are you writing your operator in ansible, helm, or go? go

**Possible Solution**
Remove the extra `type: object` 
or
Upgrade to OCP 4.x
