### ISSUE TITLE
arrayFieldGroups require [0] in path for correct form display in OKD

### ISSUE THREAD

**Issue by ParFlesh** [operator-framework/operator-sdk#2700]
## Bug Report

**What did you do?**
```golang
type MemcachedSpec struct {
	Volumes []MemcachedVolume `json:"volumes"`
}

type MemcachedVolume struct {
	// Persistent Volume Claim
	// +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors=true
	// +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.displayName="Persistent Volume Claim"
	// +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.x-descriptors="urn:alm:descriptor:com.tectonic.ui:arrayFieldGroup:volumes,urn:alm:descriptor:io.kubernetes:PersistentVolumeClaim"
	// +optional
	Claim string `json:"claim,omitempty"`
}
```

**What did you expect to see?**
```yaml
      specDescriptors:
      - description: Persistent Volume Claim
        displayName: Persistent Volume Claim
        path: volumes[0].claim
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:arrayFieldGroup:volumes
        - urn:alm:descriptor:io.kubernetes:PersistentVolumeClaim
```

**What did you see instead? Under which circumstances?**
```yaml
      specDescriptors:
      - description: Persistent Volume Claim
        displayName: Persistent Volume Claim
        path: volumes.claim
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:arrayFieldGroup:volumes
        - urn:alm:descriptor:io.kubernetes:PersistentVolumeClaim
```

**Environment**
* operator-sdk version:

```
operator-sdk version: "v0.16.0-dirty", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
```

* go version:

```
go version go1.14.1 linux/amd64
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"2576e48", GitTreeState:"clean", BuildDate:"2020-03-05T14:38:53Z", GoVersion:"go1.13.4", Compiler:"gc"
, Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1", GitCommit:"e18216f", GitTreeState:"clean", BuildDate:"2020-03-20T07:55:19Z", GoVersion:"go1.13.8", Compiler:"gc", Platform
:"linux/amd64"}
```

```
Client Version: 4.4.0-0.okd-2020-03-21-112849
Server Version: 4.4.0-0.okd-2020-03-21-112849
Kubernetes Version: v1.17.1
```

* Kubernetes cluster kind: `OKD 4.4.0-0.okd-2020-03-21-112849`

* Are you writing your operator in ansible, helm, or go? `go`
