### ISSUE TITLE
Ansible operator PVC creation and neverending reconcile loop

### ISSUE THREAD

**Issue by odra** [operator-framework/operator-sdk#2788]
## Bug Report

**What did you do?**
I am creating a PVC resource in ansible using its native `k8s` module.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:kojihub
  labels:
    app: koji-hub
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: "koji-hub"
```

**What did you expect to see?**
The CR condition status to be finished and waiting for the next reconcile loop/event.

**What did you see instead? Under which circumstances?**

The reconcile loop never finishes and stays on "running" state forever even though both PVC and PV status are set as `Bound`. 

**Environment**
* operator-sdk version: operator-sdk version: 

`operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.6 linux/amd64"`

* go version:

`go version go1.13.6 linux/amd64`

* Kubernetes version information: 

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}/
```
* Kubernetes cluster kind: minikube and local sdk test environment

* Are you writing your operator in ansible, helm, or go?

Ansible
