### ISSUE TITLE
Helm Operator's status.deployedRelease.manifest output formatting

### ISSUE THREAD

**Issue by mikeshng** [operator-framework/operator-sdk#2796]
## Type of question

The Helm Operator status.deployedRelease.manifest output formatting changed from version `0.12` to `0.16`

Is this because of different `helm` import versions and this is WAD?

## Question

**What did you do?**
Using version `0.16`, I created a helm operator
```
$ operator-sdk new nginx-ingress-operator \
    --api-version=example.com/v1alpha1 \
    --kind=NginxIngress \
    --type=helm \
	--helm-chart stable/nginx-ingress
$ cd nginx-ingress-operator/
$ kubectl apply -f deploy/crds/example.com_nginxingresses_crd.yaml 
$ kubectl apply -f deploy/crds/example.com_v1alpha1_nginxingress_cr.yaml 
$ operator-sdk run --local
```

**What did you expect to see?**
After a successful deployment, when I run `kubectl get NginxIngress -o yaml` I see the formatting is now:
```
 deployedRelease:       manifest: "---\n# Source: nginx-ingress/templates/default-backend-poddisruptionbudget.yaml\napiVersion:         policy/v1beta1\nkind: PodDisruptionBudget\nmetadata:\n  labels:\n    app:         nginx-ingress\n    chart: nginx-ingress-1.26.0\n    component: \"default-backend\"\n         \   heritage: Helm\n    release: nginx-ingress\n  name: nginx-ingress-default-backend\nspec:\n
```

**What did you see instead? Under which circumstances?**
In version `0.12`, it used to be more human readable
```
    deployedRelease:
      manifest: |2-

        ---
        # Source: nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
        apiVersion: policy/v1beta1
        kind: PodDisruptionBudget
        metadata:
          labels:
            app: nginx-ingress
            chart: nginx-ingress-1.26.0
```

**Environment**
* operator-sdk version:
```
$ operator-sdk version
operator-sdk version: "v0.16.0-dirty", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
```

* Kubernetes version information:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2020-01-14T01:25:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
```
$ kind version
kind v0.7.0 go1.13.6 linux/amd64
```

**Additional context**
Thanks.

**Comment by bharathi-tenneti** [comment]
@mikeshng Not able to reproduce , please see below log
```
$ kubectl get NginxIngress -o yaml
apiVersion: v1
items:
- apiVersion: example.com/v1alpha1
  kind: NginxIngress
  metadata:
    annotations:
```

**Comment by mikeshng** [comment]
@bharathi-tenneti Thanks for your reply. I am only referring to the `status.deployedRelease.manifest` field. Please see below.

```
$ kubectl get NginxIngress -o yaml
...
          type: kubernetes.io/tls
      reason: InstallSuccessful
      status: "True"
      type: Deployed
    deployedRelease:
      manifest: "---\n# Source: nginx-ingress/templates/controller-serviceaccount.yaml\napiVersion:
        v1\nkind: ServiceAccount\nmetadata:\n  labels:\n    app: nginx-ingress\n    chart:
        nginx-ingress-1.29.5\n    heritage: Helm\n    release: example-nginxingress\n
        \ name: example-nginxingress-nginx-ingress\n---\n# Source: nginx-ingress/templates/default-backend-serviceaccount.yaml\napiVersion:
        v1\nkind: ServiceAccount\nmetadata:\n  labels:\n    app: nginx-ingress\n    chart:
        nginx-ingress-1.29.5\n    heritage: Helm\n    release: example-nginxingress\n
...
```

**Comment by bharathi-tenneti** [comment]
Please see
```
reason: InstallSuccessful
      status: "True"
      type: Deployed
    deployedRelease:
      manifest: |
        ---
        # Source: nginx-ingress/templates/controller-serviceaccount.yaml
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          labels:
            app: nginx-ingress
            chart: nginx-ingress-1.31.0
            heritage: Helm
            release: example-nginxingress
          name: example-nginxingress-nginx-ingress
        ---
        # Source: nginx-ingress/templates/default-backend-serviceaccount.yaml
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          labels:
            app: nginx-ingress
            chart: nginx-ingress-1.31.0
            heritage: Helm
            release: example-nginxingress
          name: example-nginxingress-nginx-ingress-backend
```
