### ISSUE TITLE
Helm operator errors: failed to get API Group-Resources and create a new manager

### ISSUE THREAD

**Issue by cagrev** [operator-framework/operator-sdk#2895]
Using project "whcs-cag" on server "https://api.brief-macaque.purple-chesterfield.com:6443"

I'm running a helm operator using the operator-sdk 0.16.0. I'm struggling to get the correct reconciliation of the various image versions included in my custom resource when the custom resource is updated.

I recently added a new api version as a delta to the v1alpha1 which I had been using to see if that helped. Once that version was added, I started getting these errors and the operator pod will not start. Not sure if it's related or how, but hoping someone can help me debug what's happening.

Chriss-MacBook-Pro2:whcs-service-clinical-data-annotator-bundle-tc-icp cagrev$ oc logs whcs-acd-operator-69547b75fd-ttpwn -n whcs-cag
{"level":"info","ts":1587673083.5200763,"logger":"cmd","msg":"Go Version: go1.13.8"}
{"level":"info","ts":1587673083.5201018,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1587673083.5201063,"logger":"cmd","msg":"Version of operator-sdk: v0.16.0"}
{"level":"info","ts":1587673083.5203946,"logger":"cmd","msg":"Watching single namespace.","Namespace":"whcs-cag"}
{"level":"error","ts":1587673083.535982,"logger":"controller-runtime.manager","msg":"Failed to get API Group-Resources","error":"Unauthorized","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/manager.go:238\ngithub.com/operator-framework/operator-sdk/pkg/helm.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/helm/run.go:109\ngithub.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint.newRunHelmCmd.func1\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint/helm.go:38\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/main.go:39\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.8.linux.amd64/src/runtime/proc.go:203"}
{"level":"error","ts":1587673083.5360653,"logger":"cmd","msg":"Failed to create a new manager.","Namespace":"whcs-cag","error":"Unauthorized","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/helm.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/helm/run.go:111\ngithub.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint.newRunHelmCmd.func1\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint/helm.go:38\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/main.go:39\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.8.linux.amd64/src/runtime/proc.go:203"}
Error: Unauthorized
Usage:
  operator-sdk exec-entrypoint helm [flags]

**Comment by cagrev** [comment]
watches.yaml 
------------------------------------------------
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: ibm-whcs-service-acd-operator
    app.kubernetes.io/managed-by: ibm-whcs-service-acd-operator
    app.kubernetes.io/name: ibm-whcs-service-acd-operator
    release: v1
  name: acds.acdoperator.wh-acd.ibm.com
spec:
  group: acdoperator.wh-acd.ibm.com
  names:
    kind: Acd
    listKind: AcdList
    plural: acds
    singular: acd
  scope: Namespaced
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
      labelSelectorPath: .status.labelSelector
      #  validation:
      #    openAPIV3Schema:
      #      type: object
      #      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1alpha202004231932
    served: true
    storage: true

**Comment by cagrev** [comment]
watches.yaml

```
- version: v1alpha1
  group: acdoperator.wh-acd.ibm.com
  kind: Acd
  chart: /opt/helm/charts/ibm-whcs-service-acd-chart
- version: v1alpha202004231932
  group: acdoperator.wh-acd.ibm.com
  kind: Acd
  chart: /opt/helm/charts/ibm-whcs-service-acd-chart
```

**Comment by cagrev** [comment]
acdoperator_v1alpha1_acdbinding_cr.yaml
```
apiVersion: acdoperator.wh-acd.ibm.com/v1alpha202004231932
kind: Acd
metadata:
  labels:
    app.kubernetes.io/instance: ibm-whcs-service-acd-operator
    app.kubernetes.io/managed-by: ibm-whcs-service-acd-operator
    app.kubernetes.io/name: ibm-whcs-service-acd-operator
    release: v1
  name: whcs-acd
  .
  .
  .
```

**Comment by cagrev** [comment]
Once installed, my CRD shows two stored versions (the v1alpha1, which I had previously been using, and the new one). That looks correct to me.
```
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: acds.acdoperator.wh-acd.ibm.com
  selfLink: >-
    /apis/apiextensions.k8s.io/v1/customresourcedefinitions/acds.acdoperator.wh-acd.ibm.com
  uid: 552117b9-2ec7-4659-8a80-1e66f4ee01c3
  resourceVersion: '14434711'
  generation: 3
  creationTimestamp: '2020-04-13T16:18:27Z'
  labels:
    app.kubernetes.io/instance: ibm-whcs-service-acd-operator
    app.kubernetes.io/managed-by: ibm-whcs-service-acd-operator
    app.kubernetes.io/name: ibm-whcs-service-acd-operator
    release: v1
spec:
  group: acdoperator.wh-acd.ibm.com
  names:
    plural: acds
    singular: acd
    kind: Acd
    listKind: AcdList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: false
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
          labelSelectorPath: .status.labelSelector
    - name: v1alpha202004232105
      served: true
      storage: true
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
          labelSelectorPath: .status.labelSelector
  conversion:
    strategy: None
  preserveUnknownFields: true
status:
  conditions:
    - type: NamesAccepted
      status: 'True'
      lastTransitionTime: '2020-04-13T16:18:27Z'
      reason: NoConflicts
      message: no conflicts found
    - type: Established
      status: 'True'
      lastTransitionTime: '2020-04-13T16:18:27Z'
      reason: InitialNamesAccepted
      message: the initial names have been accepted
  acceptedNames:
    plural: acds
    singular: acd
    kind: Acd
    listKind: AcdList
  storedVersions:
    - v1alpha1
    - v1alpha202004232105
```

**Comment by cagrev** [comment]
When I go through the installed operator via the GUI and try to do a create of the CR, the yaml is prepopulated with this version (before I press the Create button). Note that it loads the v1alpha1 apiVersion, when this version of the operator was built with the v1alpha202004232105 apiVersion.
```
apiVersion: acdoperator.wh-acd.ibm.com/v1alpha1
kind: Acd
metadata:
  labels:
    app.kubernetes.io/instance: ibm-whcs-service-acd-operator
    app.kubernetes.io/managed-by: ibm-whcs-service-acd-operator
    app.kubernetes.io/name: ibm-whcs-service-acd-operator
    release: v1
  name: whcs-acd
  namespace: whcs-cag
spec:
  replicas: 1
  acd:
    deployment:
      updateStrategy:
        type: Recreate
      context: clinical_data_annotator
    probes:
      livenessProbe:
        exec:
          command:
            - /staging/whcs-devops-ucd/docker/docker_liveness.sh
        initialDelaySeconds: 180
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 10
      readinessProbe:
        exec:
          command:
            - /staging/whcs-devops-ucd/docker/docker_readiness.sh
        initialDelaySeconds: 30
        periodSeconds: 60
        timeoutSeconds: 10
        failureThreshold: 3
    image:
      tag: '20200402.1556'
      repository: us.icr.io/cdt-ls-acd-rns/clinical-data-annotator
      containerHttpsPort: 9443
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  .
  .
  .
```

**Comment by cagrev** [comment]
When I go directly to the CR by searching for it in the GUI and open up a window to do a create there, I see it loads with this version, the one that I would expect.
```
apiVersion: acdoperator.wh-acd.ibm.com/v1alpha202004232105
kind: Acd
metadata:
  name: example
  namespace: default
spec: {}
```
