### ISSUE TITLE
Ansible not working as expected with include_vars

### ISSUE THREAD

**Issue by js-max** [operator-framework/operator-sdk#2934]
## Bug Report

**What did you do?**
Given a JSON file that it's imported with `include_vars` ansible operator is not behaving as expected and returns only filename instead of loaded vars (as per [documented](https://docs.ansible.com/ansible/latest/modules/include_vars_module.html) in `include_vars`)

Now I don't know if it's working as expected or not... need you to clarify please

**What did you expect to see?**
Expecting to use `include_vars` as expected inside operator.

**What did you see instead? Under which circumstances?**
Output of filename everytime

**Code/Tests**
Stored a JSON file on a public s3 bucket with content. 

_JSON content_
```json
{
  "name": "test",
  "version": "0.0.1",
  "type": "full"
}
```

_TASKS content_
```yaml
- name: Create tempfolder
  tempfile:
    state: directory
  register: temp_folder_tar

- name: Download JSON file
  get_url:
    url: "{{ urlpath }}"
    dest: "{{ temp_folder_tar.path }}/my.json"

- name: Include JSON
  include_vars:
    file: "{{ temp_folder_tar.path }}/my.json"
    name: jsonvars

- debug:
    var: jsonvars

- name: Delete tempfolder
  file:
    path: "{{ temp_folder_tar.path }}"
    state: absent
  when: temp_folder_tar.path is defined
```
**Local run output**
```log
TASK [debug] **********************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "jsonvars": {
        "name": "test",
        "version": "0.0.1",
        "type": "full"
    }
}
```

**Operator run output**
```log
--------------------------- Ansible Task StdOut -------------------------------

 TASK [debug] ********************************
ok: [localhost] => {
    "jsonvars": "my.json"
}
```

**Environment**
* operator-sdk version:

```log
$ operator-sdk version
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "v1.17.2", go version: "go1.14.2 darwin/amd64"
```

* Kubernetes cluster kind: 
```log
$ minikube version
minikube version: v1.9.2
commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393
```

* Are you writing your operator in ansible, helm, or go?
Ansible
