### ISSUE TITLE
Multiple CR Versions in watches.yaml results in duplicate Ansible reconciliations

### ISSUE THREAD

**Issue by jessebye** [operator-framework/operator-sdk#2950]
## Bug Report

**What did you do?**
Created a CRD with two versions:
```yaml
...
  versions:
    - name: v1
      served: true
      storage: false
    - name: v2
      served: true
      storage: true
```
Created a `watches.yaml` with:
```yaml
- version: v1
  group: aws.rsk.io
  kind: IAMRole
  reconcilePeriod: 24h
  role: /opt/ansible/roles/iam-role/v1
- version: v2
  group: aws.rsk.io
  kind: IAMRole
  reconcilePeriod: 24h
  role: /opt/ansible/roles/iam-role/v2
```

Created a CR on v2:
```yaml
apiVersion: aws.rsk.io/v2
kind: IAMRole
metadata:
  name: test
spec:
  dependentQueues:
    - name: test
```

**What did you expect to see?**
Only the v2 role should have been invoked.

**What did you see instead? Under which circumstances?**
Both the v1 and v2 roles are invoked simultaneously. Here were the operator logs:
```
operator TASK [v2 : Fetch AWS config values from k8s ***********************************
operator task path: /opt/ansible/roles/iam-role/v2/tasks/main.yml:1
operator -------------------------------------------------------------------------------
operator {"level":"info","ts":1588290111.9663565,"logger":"logging_event_handler","msg":"[playbook task","name":"pronode","namespace":"defensive-yards","gvk":"aws.rsk.io/v2, Kind=IAMRole","event_type":"playbook_on_task_start","job":"6032467244848876436","EventData.Name":"v2 : Fetch AWS config values from k8s"}
operator {"level":"info","ts":1588290111.9859517,"logger":"logging_event_handler","msg":"[playbook task","name":"pronode","namespace":"defensive-yards","gvk":"aws.rsk.io/v1, Kind=IAMRole","event_type":"playbook_on_task_start","job":"907430288210826867","EventData.Name":"v1 : Fetch AWS config values from k8s"}
operator --------------------------- Ansible Task StdOut -------------------------------
operator
operator TASK [v1 : Fetch AWS config values from k8s ***********************************
operator task path: /opt/ansible/roles/iam-role/v1/tasks/main.yml:1
operator -------------------------------------------------------------------------------
operator {"level":"info","ts":1588290112.0637093,"logger":"logging_event_handler","msg":"[playbook task","name":"pronode","namespace":"defensive-yards","gvk":"aws.rsk.io/v2, Kind=IAMRole","event_type":"playbook_on_task_start","job":"6032467244848876436","EventData.Name":"v2 : Fetch AWS configuration from Kubernetes"}
operator --------------------------- Ansible Task StdOut -------------------------------
operator
operator TASK [v2 : Fetch AWS configuration from Kubernetes ****************************
operator task path: /opt/ansible/roles/common/aws-config.yml:2
operator -------------------------------------------------------------------------------
operator {"level":"info","ts":1588290112.0763645,"logger":"logging_event_handler","msg":"[playbook task","name":"pronode","namespace":"defensive-yards","gvk":"aws.rsk.io/v1, Kind=IAMRole","event_type":"playbook_on_task_start","job":"907430288210826867","EventData.Name":"v1 : Fetch AWS configuration from Kubernetes"}
operator --------------------------- Ansible Task StdOut -------------------------------
```
**Environment**
* operator-sdk version:

v0.17.0

* go version:

n/a

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

EKS

* Are you writing your operator in ansible, helm, or go?

Ansible

**Possible Solution**
n/a

**Additional context**
n/a
