### ISSUE TITLE
Consider refactoring internal/scorecard tests to use mocked data in the tests vs testdata directories

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#2955]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently the tests in https://github.com/operator-framework/operator-sdk/tree/master/internal/scorecard/alpha/tests are duplicating bundles in testdata. https://github.com/operator-framework/operator-sdk/tree/master/internal/scorecard/alpha/testdata

It is difficult to see what change caused a test to pass/fail. Also, we're duplicating a lot of code.
```
$ fdupes -r testdata/
testdata/bundle/metadata/annotations.yaml
testdata/crdvalidation/error_bundle/metadata/annotations.yaml
testdata/crdvalidation/invalid_spec_bundle/metadata/annotations.yaml
testdata/crdvalidation/invalid_status_bundle/metadata/annotations.yaml
testdata/crdvalidation/invalid_version_kind_check/metadata/annotations.yaml

testdata/bundle/manifests/cache.example.com_memcacheds_crd.yaml
testdata/crdvalidation/error_bundle/manifests/cache.example.com_memcacheds_crd.yaml
testdata/crdvalidation/invalid_spec_bundle/manifests/cache.example.com_memcacheds_crd.yaml
testdata/crdvalidation/invalid_status_bundle/manifests/cache.example.com_memcacheds_crd.yaml
testdata/crdvalidation/invalid_version_kind_check/manifests/cache.example.com_memcacheds_crd.yaml
```
**Describe the solution you'd like**
After chatting with @camilamacedo86, I think we could minimize the duplication in the testdata by creating some of the values in the code for the things we need do negative testing, etc.

For example, in a statusDescriptor test we could mock out a simple CSV with just the values that need changing:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: memcacheds.cache.example.com
spec:
  group: cache.example.com 
      statusDescriptors:
      - description: Nodes are the names of the memcached pods
        displayName: Nodes
        path: nodes
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:nodes' 
```
