### ISSUE TITLE
Ansible task checking available api-groups giving WARNING Failure method (v2_runner_on_ok) in callback plugin

### ISSUE THREAD

**Issue by slopezz** [operator-framework/operator-sdk#2968]
## Bug Report

**What did you do?**

I need to create  not default k8s objects (like prometheus `ServiceMonitor`), and in order to not have a failing task, I first check if the api-group is available on the cluster:

```yaml
- name: Get information about existing api-groups in the cluster
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"
```

Then if api-group exists, it creates the `ServiceMonitor`:
```yaml
- name: Manage ServiceMonitor (if monitoring.coreos.com api-group exists) 
  k8s:
    state: "{{ service_monitor_state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.api_exists | default(True)
  loop:
    - name: servicemonitor.yml.j2
      api_exists: "{{ True if 'monitoring.coreos.com' in api_groups else False }}"
```

**What did you expect to see?**

Task finishing with OK (and no WARNING message).

**What did you see instead? Under which circumstances?**

This task is working fine (so it only creates `ServiceMonitor` objects if api-groups is available in the cluster), but giving a WARNING `[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin`:
```
TASK [prometheusexporter : Get information about existing api-groups in the cluster] *** [1;30mtask path: /opt/ansible/roles/prometheusexporter/tasks/resources.yml:11[0m [1;30m[ [1;35m[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin[0m [1;35m(<ansible.plugins.callback.awx_display.CallbackModule object at[0m [1;35m0x7f60b8267898>): Object of type 'set' is not JSON serializable[0m [1;35m[
```

So I wonder if the WARNING is correct, or I need to check available apis using a different command, just to make sure that this `WARNING` won't become an `ERROR` in future operator-sdk releases.

Maybe there is a better way to check available APIs in the cluster? I didn't find it on the documentation.

**Environment**
* operator-sdk version:
```
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"
```

* Kubernetes version information:

```
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"1fce0fd", GitTreeState:"clean", BuildDate:"2020-02-17T19:44:53Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: OCP 4.3

* Are you writing your operator in ansible, helm, or go? `Ansible`
