### ISSUE TITLE
e2e test fails with additionalPrinterColumns in v1 CRDs

### ISSUE THREAD

**Issue by IBMRob** [operator-framework/operator-sdk#3005]
## Bug Report

**What did you do?**
Create v1 CRDs which include additionalPrinterColumns i.e. 

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dashboards.appconnect.ibm.com
spec:
  group: appconnect.ibm.com
  names:
    categories:
    - all
    - ace
    - cp4i
    kind: Dashboard
    listKind: DashboardList
    plural: dashboards
    singular: dashboard
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.versions.reconciled
      name: ResolvedVersion
      type: string
    - jsonPath: .status.replicas
      name: Replicas
      type: integer
    - jsonPath: .status.customImages
      name: CustomImages
      type: boolean
    - jsonPath: .status.conditions[0].type
      name: Status
      type: string
    - jsonPath: .status.conditions[0].lastTransitionTime
      name: LastUpdate
      type: date
.......
```
These were generated using `operator-sdk generate crds --crd-version v1`. These CRDs will deploy fine. When running e2e test, it fails. If I switch the CRDs to use the v1beta1 API then the e2e runs without issue. 

**What did you expect to see?**

The e2e test to run as normal

**What did you see instead? Under which circumstances?**

Running e2e results in an error being thrown
```
Robs-MBP-3:ibm-appconnect convery$ operator-sdk test local ./test/e2e --operator-namespace ace-rob --verbose --up-local
DEBU[0000] Debug logging is set                         
INFO[0000] Testing operator locally.                    
DEBU[0000] Running []string{"go", "test", "./test/e2e/...", "-namespacedMan", "/var/folders/6g/crzgld9x4wg_5sysdlp5l0nh0000gn/T/empty.yaml936751762", "-globalMan", "/var/folders/6g/crzgld9x4wg_5sysdlp5l0nh0000gn/T/global-manifest.yaml021941961", "-root", "/Users/convery/Documents/GitHub-IBM/ACEcc/ibm-appconnect-operator/stable/ibm-appconnect-bundle/operators/ibm-appconnect", "-parallel=1", "-localOperator", "-skipCleanupOnError=false"} 
time="2020-05-11T15:46:19+01:00" level=fatal msg="failed to create resource(s) in global resource manifest: CustomResourceDefinition.apiextensions.k8s.io \"dashboards.appconnect.ibm.com\" is invalid: [spec.additionalPrinterColumns[0].JSONPath: Required value, spec.additionalPrinterColumns[1].JSONPath: Required value, spec.additionalPrinterColumns[2].JSONPath: Required value, spec.additionalPrinterColumns[3].JSONPath: Required value, spec.additionalPrinterColumns[4].JSONPath: Required value]"
FAIL	github.ibm.com/Cloud-Integration/ibm-appconnect-operator/test/e2e	15.078s
?   	github.ibm.com/Cloud-Integration/ibm-appconnect-operator/test/e2e/testcontentserver	[no test files]
?   	github.ibm.com/Cloud-Integration/ibm-appconnect-operator/test/e2e/testcontentserver/contentserver	[no test files]
FAIL
FATA[0020] Failed to build test binary: failed to exec []string{"go", "test", "./test/e2e/...", "-namespacedMan", "/var/folders/6g/crzgld9x4wg_5sysdlp5l0nh0000gn/T/empty.yaml936751762", "-globalMan", "/var/folders/6g/crzgld9x4wg_5sysdlp5l0nh0000gn/T/global-manifest.yaml021941961", "-root", "/Users/convery/Documents/GitHub-IBM/ACEcc/ibm-appconnect-operator/stable/ibm-appconnect-bundle/operators/ibm-appconnect", "-parallel=1", "-localOperator", "-skipCleanupOnError=false"}: exit status 1 
```

**Environment**
* operator-sdk version: 0.17.0
* go version: 0.13.5
* Kubernetes version information: v1.17.1
* Kubernetes cluster kind: OCP 4.4
* Are you writing your operator in ansible, helm, or go? Go

**Possible Solution**

**Additional context**

**Comment by estroz** [comment]
@IBMRob did you modify the generated CRD manifest by hand? Looks like your validation schema syntax is invalid:
```yaml
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.versions.reconciled
      name: ResolvedVersion
      type: string
```
should be:
```yaml
  versions:
  - schema:
      openAPIV3Schema:
  		additionalPrinterColumns:
    	- jsonPath: .status.versions.reconciled
      	  name: ResolvedVersion
      	  type: string
```
according to [CRD versioning docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions).

/triage support

**Comment by IBMRob** [comment]
@estroz - According to that page I think our CRD is valid. It shows the example of 
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cronSpec:
                type: string
              image:
                type: string
              replicas:
                type: integer
    additionalPrinterColumns:
    - name: Spec
      type: string
      description: The cron spec defining the interval a CronJob is run
      jsonPath: .spec.cronSpec
    - name: Replicas
      type: integer
      description: The number of jobs launched by the CronJob
      jsonPath: .spec.replicas
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp\
```

This shows that additionalPrinterColumns comes under versions. 

Using `operator-sdk generate crds` and the e2e test works
Using `operator-sdk generate crds --crd-version v1` and the e2e test fails.  We don't manually edit and of the files CRDs
