### ISSUE TITLE
v0.18.0 generated v1 CRD fails to install due to additionalPrinterColumns spec

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-sdk#3147]
## Bug Report

**What did you do?**

We took a working `v0.17.0` project with `v1beta1` CRD apiVersion, and upgraded to `v0.18.0` OSDK following the [migration guide](https://sdk.operatorframework.io/docs/migration/v0.18.0/) to move to `v1` CRDs. Upon regenerating our CRD, the the CRD fails to install in an OCP 4.4 cluster.

**What did you expect to see?**

Working `v1` CRD installation.

**What did you see instead? Under which circumstances?**

>Error: failed to install CRD crds/company.com_examples_crd.yaml: CustomResourceDefinition.apiextensions.k8s.io "examples.company.com" is invalid: [spec.additionalPrinterColumns[0].JSONPath: Required value, spec.additionalPrinterColumns[1].JSONPath: Required value, spec.additionalPrinterColumns[2].JSONPath: Required value, spec.additionalPrinterColumns[3].JSONPath: Required value, spec.additionalPrinterColumns[4].JSONPath: Required value]

I notice that in the regenerated `apiextensions.k8s.io/v1` CRD, the `additionalPrinterColumns` appear under a `versions` array, whereas the above is stating there is a required value at `spec.additionalPrinterColumns`.

Example snippet from our CRD (post-generation at `v1`):

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  ...
spec:
  ...
  versions:
  - additionalPrinterColumns:
    - JSONPath: .status.conditions[?(@.type=="Ready")].status
      description: readiness status
      name: Ready
      type: string
    - JSONPath: .status.conditions[?(@.type=="Ready")].message
      description: readiness summary
      name: Summary
      type: string
    - JSONPath: .status.versions.reconciled
      description: reconciled version
      name: Version
      type: string
    - JSONPath: .status.conditions[?(@.type=="ReconcileError")].message
      description: reconcile error
      name: Error
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
```

The above does show the `JSONPath` values are all set, so I'm not sure where the issue is.

These are all set by markers on our CRD type def:

```go
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=".status.conditions[?(@.type==\"Ready\")].status",description="readiness status"
// +kubebuilder:printcolumn:name="Summary",type=string,JSONPath=".status.conditions[?(@.type==\"Ready\")].message",description="readiness summary"
// +kubebuilder:printcolumn:name="Version",type=string,JSONPath=".status.versions.reconciled",description="reconciled version"
// +kubebuilder:printcolumn:name="Error",type=string,JSONPath=".status.conditions[?(@.type==\"ReconcileError\")].message",description="reconcile error"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
```

**Environment**
* operator-sdk version:

```
operator-sdk version: "v0.18.0", commit: "921c33982687d6e9219fe0a1a326515fb37ae040", kubernetes version: "v1.18.2", go version: "go1.13.10 linux/amd64"
```

* go version:

```
go version go1.13.8 linux/amd64
```

* Kubernetes version information:

```
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.4.3
Kubernetes Version: v1.17.1
```

* Kubernetes cluster kind: OCP 4.4

* Are you writing your operator in ansible, helm, or go? Go operator

**Possible Solution**

**Additional context**

**Comment by estroz** [comment]
This might be a bug on our end with conversion, need to investigate.

/triage support

**Comment by kraman** [comment]
@estroz this seems related to https://github.com/operator-framework/operator-sdk/issues/3005. I tested local e2e test and its failing with the same error

**Comment by estroz** [comment]
Closing in favor of #3005, seems to be the same bug.

**Comment by estroz** [comment]
@aharbis I'm actually unable to reproduce this issue using the markers you posted.

Using some dummy types, running `generate crds --crd-version v1beta1` gives me:
```yaml
spec:
  additionalPrinterColumns:
    - JSONPath: .status.conditions[?(@.type=="Ready")].status
      description: readiness status
      name: Ready
      type: string
    - JSONPath: .status.conditions[?(@.type=="Ready")].message
      description: readiness summary
      name: Summary
      type: string
    - JSONPath: .status.versions.reconciled
      description: reconciled version
      name: Version
      type: string
    - JSONPath: .status.conditions[?(@.type=="ReconcileError")].message
      description: reconcile error
      name: Error
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
```

Without changing anything in my Go types, running `generate crds --crd-version v1` gives me:
```yaml
spec:
  versions:
    - additionalPrinterColumns:
      - description: readiness status
        jsonPath: .status.conditions[?(@.type=="Ready")].status
        name: Ready
        type: string
      - description: readiness summary
        jsonPath: .status.conditions[?(@.type=="Ready")].message
        name: Summary
        type: string
      - description: reconciled version
        jsonPath: .status.versions.reconciled
        name: Version
        type: string
      - description: reconcile error
        jsonPath: .status.conditions[?(@.type=="ReconcileError")].message
        name: Error
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
```

I assume you only ran the following to migrate?
```sh
$ operator-sdk generate crds
```
