### ISSUE TITLE
Best way to flexible configure an Ansible operator

### ISSUE THREAD

**Issue by stiller-leser** [operator-framework/operator-sdk#3176]
Hi everybody,

I am looking for best-practice advise to create a flexible ansible operator. I am working on an operator that can create certain resources in K8s via Crs - bit surprise ;) In the playbooks I am using some variables that I don't want the users to re-specify everytime in the CR, i.e. a cloud project or a certain command. Currently I am using the `defaults/main.yml` for general best practice variables and `vars/main.yml` for special variables (overwriting those in `defaults/main.yml`) based on my use case.

However, since I am planning to share the operator later with other people, I feel like it would be bad practice to hardcode my requirements in the playbooks themselves (using `vars/main.yml`).

Hence, I thought about using a configmap instead of `vars/main.yml`. I am not sure though, how to best integrate it into my operator. Should I use the `operator.yml` and create environment variables from the configmap, or should I create an entry in the `watches.yml` and let it watch for changes in configmaps? For the latter, I would receive any change on any configmap though, so that seems sub-optimal.

Any advice is appreciated,
stiller-leser

**Comment by fabianvf** [comment]
@stiller-leser ideally the configuration you'd like to expose to the user is done via a CR, and any variables specified in the CR are passed as extra_vars (which I believe have top precedence), so  you could continue the pattern you have (with `defaults/` and `vars/`)  and anything the user chooses to set would clobber what you have in defaults/vars.

If that doesn't work for your use case, you could also have the user just specify a configmap in the CR, and manually inject an ownerReference into it when you run the main reconciliation (this should cause the operator to begin watching that specific configmap, as long as the operator is configured to watch dependent resources).

I think those are your two best options if you are trying to use variables that can be set before the initial run. If the intention is instead to allow users to modify the variables after the CR has already been created, you could also have your operator create a configmap if it doesn't already exist, which will cause the operator to set up a dependent watch. You could then report the configmap to the user via the CR status, and they could then edit it to their heart's content (just remember to skip modifying that resource on subsequent reconciliations, to avoid clobbering the user's changes)

**Comment by fabianvf** [comment]
Closing because I believe the question has been answered, feel free to reopen (or ask on #kubernetes-operators in the kubernetes slack) if you have additional questions.

**Comment by stiller-leser** [comment]
Just as reference if somebody stumbles over this issue. This is what I ended up doing:

```
- name: 'Reading defaults from configmap'
  community.kubernetes.k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: '{{ meta.namespace }}'
    name: 'my-cr-defaults'
  register: cm

- name: 'Setting cm config'
  set_fact:
    cm_config: "{{ cm.resources[0].data.config | from_yaml }}"
  when: cm.resources[0].data.config is defined

- name: 'Overwrite defaults'
  set_fact: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ cm_config }}"
  when: "cm_config is defined and {{ item.key }} is undefined"
```

This is run before any of the variables are accessed and the check for `{{ item.key }} is undefined` when setting the variable makes sure that the defaults are overwritable by a configuration in the CR during runtime. The drawback here is that the configmap needs to be deployed together with the operator and isn't automatically removed when the operator is removed, which is fine in our case.
