### ISSUE TITLE
Newly created Go APIs should have a mandatory Spec.

### ISSUE THREAD

**Issue by lisa** [operator-framework/operator-sdk#3183]
# Feature Request

**Is your feature request related to a problem? Please describe.**

By default, when a new Go API is created (`operator-sdk add api --kind Funky --api-version=k8s.thedoh.dev/v1alpha1`), the resulting Go shows the `Spec` for that as `omitempty`. In conjunction with the rest of the generated code, I don't think this is a good user experience and can lead to unexpected behaviour with malformed YAML.

**Describe the solution you'd like**

Newly generated Go APIs should not have the spec `omitempty`. The auto-generated code should force implementation of the `Spec` (it is provided, after all) and allow advanced users to implement an `omitempty` if they choose.

The reasoning is that when the code is generated, the associated spec struct is also generated. For people who may be new to ecosystem, this could lead to unexpected behaviour with certain YAML cases (see below). I believe adopting this feature request supports a "least surprise" principle.

Consider a minimal case:

```go
// pkg/apis/v1alpha1/funky_types.go
package v1alpha1

type Funky struct {
  Spec FunkySpec `json:"spec,omitempty"`
}

type FunkySpec struct {
  ImportantStructure `json:"importantInfo"`
}

type ImportantStructure struct {
  Enabled bool   `json:"enabled"`
  Name    string `json:"name"`
  Purpose string `json:"purpose"`
}
```

The following YAML document is syntactically correct YAML but doesn't look like a `Funky` object (it lacks a `spec` section). The API server will accept this document and associated controllers watching Funky objects will attempt to process it. Thus when such a controller makes a reference to `instance.Spec.Enabled`, for example, it will default to `false`, because that's Go's default for a boolean.

```yaml
# deploy/crds/k8s.thedoh.dev_v1alpha1_funky_cr.yaml
apiVersion: k8s.thedoh.dev/v1alpha1
kind: Funky
metadata:
  name: example-funky
importantInfo:
  name: funky
  purpose: confusion
  enabled: true
```

**Comment by estroz** [comment]
Having `omitempty` as a JSON tag option is quite common, see the [`v1.Pod`](https://godoc.org/k8s.io/api/core/v1#Pod) type as an example. I'm not sure why necessarily but I think it has to do with reducing the amount of bytes transmitted over the wire when (de)serializing objects, although I'm not sure.

Side note: your YAML will actually evaluate to:
```yaml
apiVersion: k8s.thedoh.dev/v1alpha1
kind: Funky
metadata:
  name: example-funky
spec:
  importantInfo:
    enabled: true
    name: funky
    purpose: confusion
```

Because this is a widely accepted idiom, I don't think we want to do this in the SDK.
