### ISSUE TITLE
type in spec.template.spec.volumes.configMap is required

### ISSUE THREAD

**Issue by shenkonghui** [operator-framework/operator-sdk#3198]
## Bug Report

when I create my cr . it prompt 
type in spec.template.spec.volumes.configMap is required
```
apiVersion: app.harmonycloud.cn/v1
kind: ActiveStandbyApp
metadata:
  name: as-test
  labels:
    app: as-test
  annotations:
    maxFailNum: "2"
spec:
  selector:
    matchLabels:
      app: as-test
  serviceName: "as-test"
  replicas: 2
  template:
    metadata:
      labels:
        app: as-test
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: aa
        configMap:
          name: test
          items:
          - key: "aaa"
            path: "aaa"
      containers:
        - name: as-test
          image: registry.cn-hangzhou.aliyuncs.com/xxx/active-standby-test:0.8
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 9000
              name: tcp
```
I citation statefulset.spec in my crd
```
type ActiveStandbyApp struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   apps.StatefulSetSpec   `json:"spec,omitempty"`
	Status ActiveStandbyAppStatus `json:"status,omitempty"`
}
```
I use operator-sdk version=v0.16.0
I fount this question  on version k8s 1.12/1.13
I not fount this question on version k8s 1.17/1.18
other version not test

I need change "configMap" to "configmap" can be success.
why ?

I see this in file of crd is "configMap"  and no required in "configMap"

**What did you do?**
create cr

**What did you expect to see?**
create success

**What did you see instead? Under which circumstances?**
 it prompt 
type in spec.template.spec.volumes.configMap is required

**Environment**
* operator-sdk version:
v0.16.0

* go version:

1.13.8

* Kubernetes version information:

v1.12/1.13

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**
1. maybe change operator-sdk version 

**Additional context**
