### ISSUE TITLE
declaring operator as dependent on another where that manages multiple CRDs

### ISSUE THREAD

**Issue by ryandawsonuk** [operator-framework/operator-sdk#3242]
In the ClusterServiceVersion we can mark one operator as depending on another with a `required` section. The required operator is then installed together with the main operator if it isn't already present. I've used this in case where the dependent operator has just a single CRD (it was the seldon core operator) and it worked fine. But then I tried to [depend on the service mesh operator](https://github.com/Maistra/istio/issues/119#issuecomment-644831653), which owns three CRDs:
```
    required:
      - kind: ServiceMeshControlPlane
        name: servicemeshcontrolplanes.maistra.io
        version: v1
        displayName: Istio Service Mesh Control Plane
        description: An Istio control plane installation
      - kind: ServiceMeshMemberRoll
        name: maistra.io
        version: v1
        displayName: Istio Service Mesh Member Roll
        description: A list of namespaces in Service Mesh
      - kind: ServiceMeshMember
        name: servicemeshmembers.maistra.io
        version: v1
        displayName: Istio Service Mesh Member
        description: Marks the containing namespace as a member of the referenced Service
```
But I'm not able been able to get that working and I don't get any error. It just doesn't install the ClusterServiceVersion. I'm thinking it doesn't work in the case where there's multiple CRDs managed by a single operator or perhaps there's something else special about this operator.
