### ISSUE TITLE
e2e testing with github actions and minikube

### ISSUE THREAD

**Issue by f41gh7** [operator-framework/operator-sdk#3256]
## Type of question

 e2e testing

## Question

**What did you do?**

I'm trying to setup e2e tests with minikube at Github actions. It works well at the local machine but fails at action with a timeout error.

 Minikube setups good, I can run some kubectl commands and observe its status:

```bash
Kubernetes master is running at https://172.17.0.2:8443
KubeDNS is running at https://172.17.0.2:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

part of my GitHub actions config:

```yaml
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - name: Code checkout
        uses: actions/checkout@master

      - uses: opsgang/ga-setup-minikube@v0.1.1
        name: start minikube
        with:
          minikube-version: 1.11.0
          k8s-version: 1.16.1
      - name: Setup Go
        uses: actions/setup-go@master
        with:
          go-version: 1.13
        id: go
      - name: Dependencies
        env:
          GO111MODULE: on
        run: |
          go get  golang.org/x/lint/golint
          go get github.com/kisielk/errcheck
          go get  github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0
      - name: run e2e tests
        env:
          GO111MODULE: on
        run: |
          export SHELL=/bin/bash
          export PATH=$PATH:$(go env GOPATH)/bin
          export PATH=$PATH:`pwd`
          set -e
          minikube config set kubernetes-version v1.16.1
          minikube start
          minikube update-context
          kubectl cluster-info
          kubectl get nodes
          curl -L -o operator-sdk "https://github.com/operator-framework/operator-sdk/releases/download/v0.17.0/operator-sdk-v0.17.0-x86_64-linux-gnu"
          chmod +x operator-sdk
          make e2e-local
```
 

**What did you see instead? Under which circumstances?**

 connect and timeout errors

```bash
--- FAIL: TestApps (10.05s)
    main_test.go:38:  failed to build the dynamic client: timed out waiting for the condition
```

And a lot of errors:

```bash
E0616 00:39:19.196251   13687 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v1.App: Get https://172.17.0.2:8443/apis/app.dot.com/v1/namespaces/default/apps?limit=500&resourceVersion=0: stream error: stream ID 245; INTERNAL_ERROR
```

**Environment**
* operator-sdk version:

0.17.0

* Kubernetes version information:

1.16.1

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.
