### ISSUE TITLE
Default values for livenessProbe shows too much aggressive 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3267]
## Bug Report

**What did you do?**
Create an ansible operator with 0.18.1 with more than one Kind

**What did you expect to see?**
All worked fine

**What did you see instead? Under which circumstances?**

```
5m27s       Warning   Unhealthy           pod/pricelist-operator-58c4467966-nf9wn    Liveness probe failed: Get http://10.130.2.69:6789/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
When I run the operator with many kinds in the OCP the default values for the livenessProbe values shows too much aggressive. 

**Environment**
* operator-sdk version: 0.18.1
* Kubernetes cluster kind:  OCP 4.3.3
* Are you writing your operator in ansible, helm, or go? Ansible

**Possible Solution**

So changing the livenessProbe to this worked...

```
         livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
```

**Additional context**
Came from: https://github.com/operator-framework/operator-sdk/issues/3216 
PS.: Raised a new issue to make clear because many other points/issues were discussed in the original 

Users that faced it and checked that the above values solve are: @christianh814  and @madorn

**Comment by camilamacedo86** [comment]
@madorn
@christianh814

**Comment by camilamacedo86** [comment]
Currently it is: 

```yaml
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
```
I think would be ok update it with the suggestion made.

**Comment by camilamacedo86** [comment]
Just to supplement:  in the issue where it was originated, we could check that the client-go was raising warnings because the latency was too high in their env with OCP. See: https://github.com/operator-framework/operator-sdk/issues/3216#issuecomment-642915278

**Comment by camilamacedo86** [comment]
The OCP docs are using : 

```
      initialDelaySeconds: 15  
      timeoutSeconds: 1 
```

And;

```
    livenessProbe:
      exec:
        command:
          - /bin/bash
          - '-c'
          - timeout 60 /opt/eap/bin/livenessProbe.sh 
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
```

See: https://docs.openshift.com/container-platform/4.4/applications/application-health.html
