### ISSUE TITLE
Create Custom Resource Failed when suffix of resource kind is 's'

### ISSUE THREAD

**Issue by jojohappy** [operator-framework/operator-sdk#331]
## Bug Report
**What did you do?**

According to the `Quick Start`, I create and build a operator example with commands 

```
operator-sdk new app-operator --api-version=app.example.com/v1alpha1 --kind=Prometheus
cd app-operator
operator-sdk build my-registry.example.com/library/app-operator
docker push my-registry.example.com/library/app-operator:latest
```
After that, I deployed operator in my kubernetes cluster, and got follow errors

```
Error from server (NotFound): error when creating "cr.yml": the server could not find the requested resource (post prometheuses.app.example.com)
```

The crd yaml definition
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prometheuss.app.example.com
spec:
  group: app.example.com
  names:
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheuss
    singular: prometheus
  scope: Namespaced
  version: v1alpha1
```

The cr yaml definition
```yaml
apiVersion: "app.example.com/v1alpha1"
kind: "Prometheus"
metadata:
  name: "example"

```

If I change the `plural` from `prometheuss` to `prometheuses` in CustomResourceDefinition, the custom resource will be created.

I also test to create operator with `kind=Class`, the error will be replicated.

**Environment**

* Kubernetes version:
        kubernetes-v1.8.7

* Operator-sdk version:
	operator-sdk version 0.0.5+git
