### ISSUE TITLE
Golang example on OpenShift 4.3 cannot produce deployments (finalizer RBAC error)

### ISSUE THREAD

**Issue by a-roberts** [operator-framework/operator-sdk#3477]
## Bug Report

**What did you do?**
Followed https://sdk.operatorframework.io/docs/golang/quickstart/

**What did you expect to see?**

Memcached pods appearing

**What did you see instead? Under which circumstances?**

```

2020-07-21T08:47:07.870Z        INFO    controllers.Memcached   Creating a new Deployment       {"memcached": "default/memcached-sample", "Deployment.Namespace": "default", "Deployment.Name": "memcached-sample"}
2020-07-21T08:47:07.877Z        ERROR   controllers.Memcached   Failed to create new Deployment {"memcached": "default/memcached-sample", "Deployment.Namespace": "default", "Deployment.Name": "memcached-sample", "error": "deployments.apps \"memcached-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```

No new pods. Above error comes from the logs of my operator.

**Environment**
* operator-sdk version:
0.19

* go version:
1.14.5

* Kubernetes version information:

```

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

OpenShift 4.3

* Are you writing your operator in ansible, helm, or go?

Go

**Possible Solution**

Missing rbac in role.yaml surely, missing annotations somewhere to allow finalizer permissions?

Here's my generated role.yaml:

```

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
```

My reconcile method as per the example:

```
// +kubebuilder:rbac:groups=cache.example.com,resources=memcacheds,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=cache.example.com,resources=memcacheds/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=pods,verbs=get;list;

func (r *MemcachedReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
```

**Comment by estroz** [comment]
@a-roberts can you try adding the following marker and running `make deploy` again?
```
// +kubebuilder:rbac:groups=apps,resources=deployments/finalizers,verbs=get;create;update;patch;delete
```

**Comment by camilamacedo86** [comment]
HI @a-roberts, 

It shows duplicated of https://github.com/operator-framework/operator-sdk/issues/3590. See my comment in https://github.com/operator-framework/operator-sdk/issues/3590#issuecomment-665645542. 

I am closing this one and I'd like to ask for you follow up the  https://github.com/operator-framework/operator-sdk/issues/3590 if possible. However, if you do you think that it should be re-opened for any reason please feel free to ping and let us know.

**Comment by hasbro17** [comment]
Reopening after I hit the same error while testing on Openshift 4.5.6:
```
ERROR   controllers.Memcached   Failed to create new Deployment {"memcached": "default/memcached-sample", "Deployment.Namespace": "default", "Deployment.Name": "memcached-sample", "error": "deployments.apps \"memcached-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```

The fix for me was to give the operator's ClusterRole permissions to update the memcached CR's finalizers, with the following marker in the controller:
```
// +kubebuilder:rbac:groups=cache.example.com,resources=memcacheds/finalizers,verbs=get;update;patch
```
```YAML
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds/finalizers
  verbs:
  - get
  - patch
  - update
```



@estroz @camilamacedo86 @joelanford  Sorry if I missed it but did we discuss why we don't have the above in our docs and [sample memcached controller](https://github.com/operator-framework/operator-sdk/blob/a9d6b1bb561e22a6a78996ca86acbd6a59cc24c3/example/memcached-operator/memcached_controller.go.tmpl#L41-L44) to make the quickstart guide work by default on openshift (or any cluster with [OwnerReferencesPermissionsEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) set).

https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#specify-permissions-and-generate-rbac-manifests

I know there's similar discussion for the same bug for Helm operators in https://github.com/operator-framework/operator-sdk/issues/3767#issuecomment-679123829 which I think is for the same reason.
