### ISSUE TITLE
Ansible Operator `undefined variable` using nested vars

### ISSUE THREAD

**Issue by alexandrsemak** [operator-framework/operator-sdk#3553]
Hey, I have error:
 `The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'tlsSecret'`

within Ansible jinja2 templete:

```
apiVersion: v1
kind: Template
metadata:
  name: "wxu-web"
  annotations:
    description: "Openshift a set of object"
labels:
{% for k, v in default.items() %}
{% if v is not none %}
  {{ k }}: {{ v }}
{% endif %}
{% endfor %}
objects:
- apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: {{ default.release_name }}
  spec:
    rules:
    {% for hosts in ingress -%}
    {% for host in hosts.hosts -%}
    - host: {{ host }}
      http:
        paths:
        - backend:
            serviceName: {{ default.release_name }}
            servicePort: {{ service_port }}
          path: /
    {% endfor -%}
    {% endfor -%}
    tls:
    {% for hosts in ingress -%}
      - hosts:
      {% for host in hosts.hosts -%}
      - {{ host }}
      {% endfor -%}
      secretName: {{ hosts.tlsSecret }}
    {% endfor %}
```

and with following custrom_resources:

```
apiVersion: xxx.xxx.com/v1alpha1
kind: xxx
metadata:
  name: xxx-xxx
spec:

# Default Jinja2 Template
  namespace: tutorial
  default:
    release_name: xxx-stage
    app_name: xxx
    cluster: xxx-xxx
    region: xxx-xxx
    datacenter: xxx

  # Service Jinja2 Template
  service_port: xxx

  # Ingress Jinja2 Template
  ingress:
    - hosts:
        - xxx-stage.xxx.com
        - xxx-stage-xxx.xxx.com
        - xxx-stage-xxx-xxx.xxx.com
      tlsSecret: star-xxx-com
    - hosts:
        - xxx-stage.xxx.com
        - xxx-stage-xxx.xxx.com
        - xxx-stage-xxx-xxx.xxx.com
      tlsSecret: star-xxx-com 
```

I am not sure but looks like Operator-SDK not handling nested variables with Ansible Template
