### ISSUE TITLE
Generate Bundle Incorrect ClusterPermissions ServiceAccountName

### ISSUE THREAD

**Issue by ricfeatherstone** [operator-framework/operator-sdk#3600]
## Bug Report

Writing an Ansible Operator with namespace and cluster wide permissions, generate bundle appears to create an incorrect CSV file.

[Example project](https://github.com/ricfeatherstone/example-generator-issue-operator)

**What did you do?**

`operator-sdk new example-generator-issue-operator --api-version=issue.example.com/v1alpha1 --kind=Example --type=ansible`
Add deploy/clusterrole.yaml and deploy/clusterrole_binding.yaml
`operator-sdk generate bundle --version 0.0.1`

**What did you expect to see?**

```
clusterPermissions:
      - rules:
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        serviceAccountName: example-generator-issue-operator
```

**What did you see instead?**

```
clusterPermissions:
      - rules:
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        serviceAccountName: token-reviewer
```

**Environment**
* operator-sdk version:

`operator-sdk version: "v0.19.0", commit: "8e28aca60994c5cb1aec0251b85f0116cc4c9427", kubernetes version: "v1.18.2", go version: "go1.13.10 linux/amd64"`
