### ISSUE TITLE
Adding customresourcedefinitions to CSV fails bundle Validation

### ISSUE THREAD

**Issue by atef23** [operator-framework/operator-sdk#3604]
## Type of question

How to implement a Specific Feature

## Question

I am attempting to build, push and bundle validate my operator using the following commands:

```
docker build -f bundle.Dockerfile -t quay.io/aaziz/jupyterlab-operator:v1.0.0 .
docker push quay.io/aaziz/jupyterlab-operator:v1.0.0
operator-sdk bundle validate quay.io/aaziz/jupyterlab-operator:v1.0.0

```

where bundle.Dockerfile is as follows:

```
FROM scratch

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=jupyterlab-operator
LABEL operators.operatorframework.io.bundle.channels.v1=alpha
LABEL operators.operatorframework.io.bundle.channel.default.v1=alpha
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v0.19.0
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v2

COPY bundle/manifests /manifests/
COPY bundle/metadata /metadata/
```

This is successful when my customresourcedefinition is empty in my CSV but when I add the following:

```
customresourcedefinitions:
    owned:
    - description: Jupyterlab is the Schema for the jupyterlabs API
      displayName: Jupyterlab
      kind: Jupyterlab
      name: jupyterlabs.jupyter.example.com
      version: v1alpha1
```

I get this validation error:

```
[atefaziz@localhost jupyterlab-operator]$ operator-sdk bundle validate quay.io/aaziz/jupyterlab-operator:v1.0.0
INFO[0000] Unpacking image layers                       
INFO[0000] running docker create                        
INFO[0000] running docker cp                            
INFO[0000] running docker rm                            
INFO[0000] Found annotations file                        bundle-dir=/tmp/bundle-487506823 container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=/tmp/bundle-487506823 container-tool=docker
ERRO[0000] Error: Value jupyter.example.com/v1alpha1, Kind=Jupyterlab: owned CRD "jupyter.example.com/v1alpha1, Kind=Jupyterlab" not found in bundle "jupyterlab-operator.v1.0.0" 
WARN[0000] Warning: Value jupyter.example.com/v1alpha1, Kind=Jupyterlab: provided API should have an example annotation 
ERRO[0000] Error: Value /, Kind=: unsupported media type registry+v1 for bundle object 
[atefaziz@localhost jupyterlab-operator]$ opm index add --bundles quay.io/aaziz/jupyterlab-operator:v1.0.0 --tag quay.io/aaziz/jupyterlab-operator-index:v1.0.0
INFO[0000] building the index                            bundles="[quay.io/aaziz/jupyterlab-operator:v1.0.0]"
INFO[0000] resolved name: quay.io/aaziz/jupyterlab-operator:v1.0.0 
INFO[0000] fetched                                       digest="sha256:5c9299723e33461a7f1ce6ea90151ff2a02e60a65af2d0a1e4e41ef5066ca272"
INFO[0000] fetched                                       digest="sha256:ff71ccdfddf8542b771b48d142dc6c93da79a4421d5dde4c9a1ddecb07a9f88d"
INFO[0000] fetched                                       digest="sha256:6616f2d4c1220d95c334d45a18e3fee64abc8bcab95afb6cca44bc2c2fca0f87"
INFO[0000] fetched                                       digest="sha256:2554e33f59c393675b88209ee43c9f85113fa5253f108bb92cad781670f57cda"
INFO[0001] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:2554e33f59c393675b88209ee43c9f85113fa5253f108bb92cad781670f57cda 1984 [] map[] <nil>} 
INFO[0001] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:ff71ccdfddf8542b771b48d142dc6c93da79a4421d5dde4c9a1ddecb07a9f88d 354 [] map[] <nil>} 
INFO[0001] Could not find optional dependencies file     dir=bundle_tmp191899762 file=bundle_tmp191899762/metadata load=annotations
INFO[0001] found csv, loading bundle                     dir=bundle_tmp191899762 file=bundle_tmp191899762/manifests load=bundle
INFO[0001] loading bundle file                           dir=bundle_tmp191899762/manifests file=jupyter.example.com_jupyterlabs.yaml load=bundle
INFO[0001] loading bundle file                           dir=bundle_tmp191899762/manifests file=jupyterlab-operator.clusterserviceversion.yaml load=bundle
ERRO[0001] permissive mode disabled                      bundles="[quay.io/aaziz/jupyterlab-operator:v1.0.0]" error="error checking provided apis in bundle jupyterlab-operator.v1.0.0: couldn't find jupyter.example.com/v1alpha1/Jupyterlab (jupyterlabs) in bundle. found: map[]"
Error: error checking provided apis in bundle jupyterlab-operator.v1.0.0: couldn't find jupyter.example.com/v1alpha1/Jupyterlab (jupyterlabs) in bundle. found: map[]
```

Do I need to add something to my bundle/manifests or something else in my CSV?

**What did you expect to see?**
Successful passed validation

**What did you see instead? Under which circumstances?**

ERRO[0000] Error: Value jupyter.example.com/v1alpha1, Kind=Jupyterlab: owned CRD "jupyter.example.com/v1alpha1, Kind=Jupyterlab" not found in bundle "jupyterlab-operator.v1.0.0" 

**Environment**
* operator-sdk version:

"v0.19.0"

* Kubernetes version information:

openshift 4.3.1

* Kubernetes cluster kind: 

Openshift 

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment]
Hi @atef23, 

Could you please let us know the following info?

- Could you confirm that you are using Go-based operator?  
- Also, is it a new project or an old one? Are you using the new layout? Did you gen this project or upgraded it? 
- Could you please provide the tree of your project ($ tree)?
- Why you are updating the `customresourcedefinitions.owned` definitions manually?

**Comment by atef23** [comment]
@camilamacedo86 Sure, it's a Go lang based operator created with the new v 0.19 operator sdk commands:

```
operator-sdk init --domain=example.com --repo=github.com/atef23/jupyterlab-operator
operator-sdk create api --group=jupyter --version=v1alpha1 --kind=Jupyterlab

```

Here is the tree for my project:
```

[atefaziz@localhost jupyterlab-operator]$ tree
.
├── api
│   └── v1alpha1
│       ├── groupversion_info.go
│       ├── jupyterlab_types.go
│       └── zz_generated.deepcopy.go
├── bin
│   └── manager
├── bundle
│   ├── manifests
│   │   └── jupyterlab-operator.clusterserviceversion.yaml
│   └── metadata
│       └── annotations.yaml
├── bundle.Dockerfile
├── config
│   ├── certmanager
│   │   ├── certificate.yaml
│   │   ├── kustomization.yaml
│   │   └── kustomizeconfig.yaml
│   ├── crd
│   │   ├── bases
│   │   │   └── jupyter.example.com_jupyterlabs.yaml
│   │   ├── kustomization.yaml
│   │   ├── kustomizeconfig.yaml
│   │   └── patches
│   │       ├── cainjection_in_jupyterlabs.yaml
│   │       └── webhook_in_jupyterlabs.yaml
│   ├── default
│   │   ├── kustomization.yaml
│   │   ├── manager_auth_proxy_patch.yaml
│   │   ├── manager_webhook_patch.yaml
│   │   └── webhookcainjection_patch.yaml
│   ├── manager
│   │   ├── kustomization.yaml
│   │   └── manager.yaml
│   ├── manifests
│   │   ├── bases
│   │   │   └── jupyterlab-operator.clusterserviceversion.yaml
│   │   └── kustomization.yaml
│   ├── prometheus
│   │   ├── kustomization.yaml
│   │   └── monitor.yaml
│   ├── rbac
│   │   ├── auth_proxy_client_clusterrole.yaml
│   │   ├── auth_proxy_role_binding.yaml
│   │   ├── auth_proxy_role.yaml
│   │   ├── auth_proxy_service.yaml
│   │   ├── jupyterlab_editor_role.yaml
│   │   ├── jupyterlab_viewer_role.yaml
│   │   ├── kustomization.yaml
│   │   ├── leader_election_role_binding.yaml
│   │   ├── leader_election_role.yaml
│   │   ├── role_binding.yaml
│   │   └── role.yaml
│   ├── samples
│   │   ├── jupyter_v1alpha1_jupyterlab.yaml
│   │   └── kustomization.yaml
│   └── webhook
│       ├── kustomization.yaml
│       ├── kustomizeconfig.yaml
│       └── service.yaml
├── controllers
│   ├── jupyterlab_controller.go
│   ├── openshift_resources.go
│   └── ports.go
├── cover.out
├── Dockerfile
├── go.mod
├── go.sum
├── hack
│   └── boilerplate.go.txt
├── main.go
├── Makefile
└── PROJECT

```

**Comment by atef23** [comment]
It looks like my error is from line 223 here:

https://github.com/operator-framework/operator-registry/blob/5dd65cffcee2962569a21e98c7060dce4c7a05eb/pkg/registry/bundle.go

I'm not sure how to add my api as a provided API in the CSV. It looks like whatever element it is looking for the provided APIs in is empty since the error says:

couldn't find jupyter.example.com/v1alpha1/Jupyterlab (jupyterlabs) in bundle. found: map[]

**Comment by camilamacedo86** [comment]
Hi @atef23, 

In the new layout, you will find the following targets to work with bundle: 

```shel
# Generate bundle manifests and metadata, then validate generated files.
bundle: manifests
	operator-sdk generate kustomize manifests -q
	$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle -q --overwrite --version $(VERSION) $(BUNDLE_METADATA_OPTS)
	operator-sdk bundle validate ./bundle

# Build the bundle image.
bundle-build:
	docker build -f bundle.Dockerfile -t $(BUNDLE_IMG) .
```

Then, see that to generate the bundle you ought to use the `make bundle`. Note that, it will update the manifests as well. then, in this way the steps would be: 

- Run `make bundle`
- Run `bundle-build BUNDLE_IMG=<some-registry>/<project-name>:tag` // needs to be diff your project image, maybe the same name with the suffix `-bundle` for example. 
- Then, you will run `operator-sdk bundle validate bundle`

Could you please try that and let us know if it works for you? PS. I do not think that you ought requires to update the `customresourcedefinitions` manually.

**Comment by atef23** [comment]
@camilamacedo86 thanks, I ran make bundle and make bundle build with a new image name but the CSV it generated did not populate with my customresourcedefinition:

```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v0.19.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: jupyterlab-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Jupyterlab IDE for developing Jupyter Notebooks
  displayName: Jupyterlab
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAADUAAAAhCAIAAAD2w3SqAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEPSURBVFhH7ZbBEYMgEEXTjf1QjTer8GYH9OAMTXilAIvYrLAwxqiJfJnksG+4sIPjk/UrD/pv1A9D/TDUD0P9MO7ws4Y6Q5OXqTBS34S6zMvA/Ubq2KMhO0ohMrVSdxvva+B+PuzTsd+v9y/59YMUIo6bznVDsxTKqOZnQ7FrZVpKJb8D6etU8kuhwcLB1PGbB/HDwsHc57fOr4QXDQeD++21UsKLhoOB/Xa/czG8cDgY0O80vJsvdhFf+8krb8ilu87xDxuKL+/ZuuN+WeYGsi31Jq2/sLVf++U+vo/NySCH92Tkh/zElf7Ofjmq5D3g0bd7CU39jQvssDwAX1sEnI/KqB+G+mGoH4b6IRA9AfM03ocXOND7AAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - jupyter
  - ai
  - ml
  - ide
  links:
  - name: Jupyterlab Operator
    url: https://jupyterlab-operator.domain
  maturity: alpha
  provider:
    name: atef23
  version: 1.0.0

```

**Comment by estroz** [comment]
@atef23 effectively what's happening is the generator cannot find an API in `api/` corresponding to your `jupyter.example.com/v1alpha1, Kind=Jupyterlab` API and is not adding it to the CSV base. If you add it manually, the validator cannot find the CRD corresponding to that API in the bundle.

There might be a naming discrepancy or manifest issue somewhere. The line
```
ERRO[0000] Error: Value /, Kind=: unsupported media type registry+v1 for bundle object 
```
in your `bundle validate` output and the fact that no CRD is being copied to `bundle/`
```console
$ tree .
...
├── bundle
│   ├── manifests
│   │   └── jupyterlab-operator.clusterserviceversion.yaml
...
```
 supports this hypothesis.

Does your `PROJECT` file have any `resources` in it?

**Comment by atef23** [comment]
@estroz Thanks, I'm no longer getting the validation errors but my bundle CSV is generated without the customresourcedefinitions that are present in my manifests/bases/ clusterserviceversion.yaml

my PROJECT file has the following:

```
domain: example.com
layout: go.kubebuilder.io/v2
repo: github.com/atef23/jupyterlab-operator
resources:
- group: jupyter
  kind: Jupyterlab
  version: v1alpha1
version: 3-alpha
plugins:
  go.operator-sdk.io/v2-alpha: {}
```
