### ISSUE TITLE
Debugging "Operator not available for selected namespaces" error when Installing from Catalog

### ISSUE THREAD

**Issue by atef23** [operator-framework/operator-sdk#3726]
## Type of question

**Help Debugging an operator subscription creation**

## Question

**What did you do?**
I am trying to install my operator by creating a subscription to the catalog created from my catalog source in Openshift:

oc apply -f https://raw.githubusercontent.com/atef23/jupyterlab-operator/master/jupyterlab-operator-catalog-source.yaml

**What did you expect to see?**

I am hoping to be able to install the operator for all namespaces. It works if I install into a specific namespace.

**What did you see instead? Under which circumstances?**

An error saying "Operator not available for selected namespaces"
![Screenshot from 2020-08-11 20-33-59](https://user-images.githubusercontent.com/8210520/89962742-a80af080-dc13-11ea-8a32-d0b248d76e07.png)

**Environment**
* operator-sdk version:

"v0.19.0"

* Kubernetes version information:

 openshift 4.3.1

* Kubernetes cluster kind: 
Openshift

**Additional context**

I'm just wondering how I could go about debugging this. I'm not sure what causes the issue above so I don't know what to look into. I have the following installmodes in my CSV:

```
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
```

and I have the following operatorgroups on my cluster:

```
[atefaziz@localhost Jupyterlab-Operator-Work]$ oc get operatorgroup --all-namespaces
NAMESPACE                              NAME                           AGE
openshift-monitoring                   openshift-cluster-monitoring   163m
openshift-operator-lifecycle-manager   olm-operators                  163m
openshift-operators                    global-operators               163m
```

Any info would be greatly appreciated.
