### ISSUE TITLE
xDescriptors not functioning as documented

### ISSUE THREAD

**Issue by jlfowle** [operator-framework/operator-sdk#3742]
## Bug Report

**What did you do?**
1. `mkdir memcached-operator && cd memcached-operator`
2. `operator-sdk init --domain example.com --repo=github.com/example/memcached-operator --project-version 3-alpha --license apache2 --plugins go.kubebuilder.io/v2`
3. `operator-sdk create api --group=cache --version=v1alpha1 --kind=Memcached`
4. Add markers as in Step 2 in [API Markers example](https://sdk.operatorframework.io/docs/building-operators/golang/references/markers/#examples)
5. `make bundle`
   * fill in information

**What did you expect to see?**
ClusterServiceVersion should container
```yaml
specDescriptors:
  - description: Size is the size of the memcached deployment.
    displayName: Number of pods
    path: size
    x-descriptors:
      - urn:alm:descriptor:com.tectonic.ui:podCount
      - urn:alm:descriptor:io.kubernetes:custom
```

**What did you see instead? Under which circumstances?**
ClusterServiceVersion contains container
```yaml
specDescriptors:
  - description: Size is the size of the memcached deployment.
    displayName: Number of pods
    path: size
    x-descriptors:
      - urn:alm:descriptor:com.tectonic.ui:podCount,urn:alm:descriptor:io.kubernetes:custom
```

**Environment**
* operator-sdk version:

`operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"`

* go version:

`go version go1.14.6 linux/amd64`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3", GitCommit:"002a51f", GitTreeState:"clean", BuildDate:"2020-08-06T07:16:38Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:  OKD

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**
Update documentation to separate each descriptor by line

```
    // Size is the size of the memcached deployment.
    // +operator-sdk:csv:customresourcedefinitions:type=spec,displayName="Number of pods"
    // +operator-sdk:csv:customresourcedefinitions:type=spec,xDescriptors="urn:alm:descriptor:com.tectonic.ui:podCount"
    // +operator-sdk:csv:customresourcedefinitions:type=spec,xDescriptors="urn:alm:descriptor:io.kubernetes:custom"
    Size int32 `json:"size"`
```
