### ISSUE TITLE
How to get full Ansible log from Operator pod?

### ISSUE THREAD

**Issue by YanFenGuo** [operator-framework/operator-sdk#3755]
## Type of question
Previously we ask our customer to export Ansible logs with this command: `kubectl logs deployment/ibm-cp4a-operator -c ansible > Ansible.log`. But since operator-sdk:0.18.0, the side-car Ansible container is removed. While in operator container, the Ansible log doesn't have enough detail.
I know in documentation there is a variable `ANSIBLE_DEBUG_LOGS: True`, but even with it, still can't get the complete log as it shows in `/tmp/ansible-operator/runner/<group>/<version>/<kind>/<namespace>/<name>`, actually, I don't see a difference with or without  `ANSIBLE_DEBUG_LOGS: True`, maybe I'm not checking the right place?

**What did you expect to see?**
What I'm seeking is without going into operator pod, can get a complete Ansible log with detailed information.
For example the same task shows below in `/tmp/ansible-operator/runner/<group>/<version>/<kind>/<namespace>/<name>`:

```
TASK [prerequisites : set template initialization_configuration template] ******^M
^[[1;30mtask path: /opt/ansible/roles/prerequisites/tasks/pattern-aware/fncm-ban-initialization-detect.yaml:59^[[0m
Wednesday 19 August 2020  03:41:31 +0000 (0:00:00.160)       0:00:13.985 ******
^[[0;33mchanged: [localhost] => {"changed": true, "checksum": "*******", "dest": "/tmp/ansible-operator/runner/init/initialization_configuration.yaml", "gid": 0, "group": "root", "md5sum": "******", "mode": "0644", "owner": "1000570000", "size": 7378, "src": "/tmp/.ansible-/tmp/ansible-tmp-1597808491.3779387-189-236775360540360/source", "state": "file", "uid": 1000570000}^[[0m
```

But from the pod log console, with or without `ANSIBLE_DEBUG_LOGS: True`, it is always just this:
```
--------------------------- Ansible Task StdOut -------------------------------

TASK [prerequisites : set template initialization_configuration template] ******
[1;30mtask path: /opt/ansible/roles/prerequisites/tasks/pattern-aware/fncm-ban-initialization-detect.yaml:59[0m

-------------------------------------------------------------------------------
2020-08-19T03:29:45.352Z	INFO	logging_event_handler	[playbook task]	{"name": "automation", "namespace": "ecm-automation-43", "gvk": "icp4a.ibm.com/v1, Kind=ICP4ACluster", "event_type": "playbook_on_task_start", "job": "4037200794235010051", "EventData.Name": "prerequisites : set template initialization_configuration template"}
```

**Environment**
I'm using 0.17.2 but I'm assuming the higher version have similar result.

* operator-sdk version: 0.17.2

* Kubernetes version information: v1.16.2

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: OCP4.3

**Comment by camilamacedo86** [comment]
Hi @YanFenGuo, 

you need to add the ENV VAR in the operator.ymal and re-deploy it. See: [here](https://github.com/operator-framework/operator-sdk-samples/blob/v0.17.0/ansible/memcached-operator/deploy/operator.yaml#L40-L41) the example. 

All ansible logs will be output in the container logs. 

I am closing this one as sorted out. However, feel free to ping us to re-open if you need.

**Comment by YanFenGuo** [comment]
> Hi @YanFenGuo,
> 
> you need to add the ENV VAR in the operator.ymal and re-deploy it. See: [here](https://github.com/operator-framework/operator-sdk-samples/blob/v0.17.0/ansible/memcached-operator/deploy/operator.yaml#L40-L41) the example.
> 
> All ansible logs will be output in the container logs. Note that the Ansible logs will be outputted with the operator ones in the same way. It will increase the verbose which means output all ansible logs that we could find in the old versions in the ansible container.
> 
> I am closing this one as sorted out. However, feel free to ping us to re-open if you need.

Thank you for the quick response, your example is exactly what I did. But there is no difference, still can't get full log. Here is my deployment yaml file:
```
###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2019. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-cp4a-operator
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.3
spec:
****
    spec:
  ******
      containers:
        - name: icp4a-operator
          # Replace this with the built image name
          image: ****
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          - mountPath: /opt/ansible/share
            name: operator-shared-folder
          args:
          - '--zap-time-encoding=iso8601'
          - '--zap-encoder=console'
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-cp4a-operator"
            - name: WORKER_FOOSERVICE_CACHE_EXAMPLE_COM
              value: "10"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_DEBUG_LOGS
              value: "True"
            # - name: ANSIBLE_VERBOSITY
            #   value: "4"
            - name: dba_license
              value: accept
      imagePullSecrets:
      - name: "admin.registrykey.operator"
      volumes:
        - name: runner
          emptyDir: {}
        - name: "operator-shared-folder"
          persistentVolumeClaim:
            claimName: "operator-shared-pvc"
```
