### ISSUE TITLE
How to run operators built on latest version of operator SDK on older versions of Kubernetes 

### ISSUE THREAD

**Issue by santoshborse** [operator-framework/operator-sdk#3789]
## Type of question

Open question

## Question
CustomResourceDefinition's apiVersion `v1` is introduced in k8s v1.16 and prior version were supporting `v1beta1`.

The latest version of Operator SDK ( v0,18, v0.19 or v1.0 ) generates CRD with apiVersion `v1`.

Is it expected to use older version of Operator SDK which generates CRD with `v1beta1` to build operator for k8s version < v1.16?

Or operator generated using latest version of SDK should be able to run with CRD version `v1beta1`

#### What did you do?

Created sample Ansible operator using Operator SDK v0.18, and updated generated CRD from `v1` to `v1beta1`

`v1` CRD
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: v19tests.test.ibm.com
spec:
  group: test.ibm.com
  names:
    kind: V19Test
    listKind: V19TestList
    plural: v19tests
    singular: v19test
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}

```
Update the same to,
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: v19tests.test.ibm.com
spec:
  group: test.ibm.com
  names:
    kind: V19Test
    listKind: V19TestList
    plural: v19tests
    singular: v19test
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true

```

And created following CR… 

```
apiVersion: test.ibm.com/v1alpha1
kind: V19Test
metadata:
  name: example-v19test
spec:
  # Add fields here
  size: 3
```

#### What did you expect to see?

I was expecting operator should be able to run with CRD version `v1beta1`

#### What did you see instead? Under which circumstances?

Operator is not able to find the CR.

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

minikube

`$ operator-sdk version`

operator-sdk version: "v0.18.1", commit: "7bf7b6886d647dc202525daec16fab67dcc52a3d", kubernetes version: "v1.18.2", go version: "go1.14.3 darwin/amd64"

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context

**Operator Logs**

```{"level":"info","ts":1598455818.1968193,"logger":"cmd","msg":"Install prometheus-operator in your cluster to create ServiceMonitor objects","Namespace":"opr-ns","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1598455818.1990504,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1598455818.1996422,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"v19test-controller","source":"kind source: test.ibm.com/v1alpha1, Kind=V19Test"}
{"level":"info","ts":1598455818.2016184,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1598455818.301003,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"v19test-controller"}
{"level":"info","ts":1598455818.3011863,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"v19test-controller","worker count":1}
{"level":"error","ts":1598455818.3096166,"logger":"reconciler","msg":"Unable to update the status to mark cr as running","job":"4037200794235010051","name":"example-v19test","namespace":"opr-ns","error":"v19tests.test.ibm.com \"example-v19test\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/controller.(*AnsibleOperatorReconciler).Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/controller/reconcile.go:133\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}
{"level":"error","ts":1598455818.3099997,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"v19test-controller","request":"opr-ns/example-v19test","error":"v19tests.test.ibm.com \"example-v19test\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}
{"level":"error","ts":1598455818.3206878,"logger":"reconciler","msg":"Unable to update the status to mark cr as running","job":"3916589616287113937","name":"example-v19test","namespace":"opr-ns","error":"v19tests.test.ibm.com \"example-v19test\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/controller.(*AnsibleOperatorReconciler).Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/controller/reconcile.go:133\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}
```

$ kubectl get crd v19tests.test.ibm.com 
```
NAME                    CREATED AT
v19tests.test.ibm.com   2020-08-26T13:14:34Z
```

$ kubectl get v19tests.test.ibm.com 
```
NAME              AGE
example-v19test   5m2s
```
