### ISSUE TITLE
Ansible operator is missing resources limits

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3807]
## Feature Request

The Ansible projects scaffolds with SDK also should have resources limits because it ensures security. Common attacks take advantage of it. See; https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-7-limit-resources-memory-cpu-file-descriptors-processes-restarts

```
 resources:
          limits:
            cpu: 100m
            memory: 90Mi
          requests:
            cpu: 100m
            memory: 60Mi
```

PS. The default values are not enough for Ansible. So, the complexity here is to find what values should be appropriated.
