### ISSUE TITLE
Documentation - Annotation incorrect in Ansible Development Tips

### ISSUE THREAD

**Issue by imjoseangel** [operator-framework/operator-sdk#3833]
#### What did you do?

The following CR snipped is incorrect:

```yaml
apiVersion: "foo.example.com/v1alpha1"
kind: "Foo"
metadata:
  name: "foo-sample"
annotations:
  ansible.sdk.operatorframework.io/reconcile-period: "30s"
```

#### What did you expect to see?

It should be:

```yaml
apiVersion: "foo.example.com/v1alpha1"
kind: "Foo"
metadata:
  name: "foo-sample"
  annotations:
    ansible.sdk.operatorframework.io/reconcile-period: "30s"
```

Document `development-tips.md`
