### ISSUE TITLE
Ansible role was called over and over again

### ISSUE THREAD

**Issue by wzhanw** [operator-framework/operator-sdk#3846]
## Bug Report
I found the role was called again and again.  is it the right behavior?

In my ansible role, I have some tasks to create some resources including some CRs of my CRD.
An example of my ansible task for the CR creation:
```
- name: Create default ResourcePlans for XXX
  k8s:
    state: present
    definition:
          apiVersion: xxx.com/v1
          kind: ResourcePlan
          metadata:
            name: "zhuangxy"
            namespace: "zhuangxy"
            labels:
              parent: "root"
          spec:
            children:
            - name: sample-project
              share: 1
            parent: root
            parentNamespace: "{{ xxx.podSchedulerNamespace }}"
```
I expect this cr was created by the operator but I don't want them were watched by the operator. 
I don't want the later user's customization on the cr was rollback by the operator.
So I added it to the blacklist in watches.yaml:

```
  blacklist:
    - group: xxx.com
      version: v1
      kind: ResourcePlan
```
I checked the operator log, my blacklist configuration took effect:
```
{"level":"info","ts":1599116824.3462236,"logger":"proxy","msg":"Skipping, because gvk is blacklisted","GVK":"xxx.com/v1, Kind=ResourcePlan"}
{"level":"info","ts":1599116824.3462398,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":true,"Path":"/apis/xxx.com/v1/namespaces/zhuangxy/resourceplans/zhuangxy","Verb":"get","APIPrefix":"apis","APIGroup":"xxx.com","APIVersion":"v1","Namespace":"zhuangxy","Resource":"resourceplans","Subresource":"","Name":"zhuangxy","Parts":["resourceplans","zhuangxy"]}}
{"level":"info","ts":1599116824.3616679,"logger":"proxy","msg":"Skipping, because gvk is blacklisted","GVK":"xxx.com/v1, Kind=ResourcePlan"}
```
But I found the update on that CR was rollback by the operator soon.  I checked the operator log, I found my ansible role was called by the operator over and over again.  it will run the CR creation task again and patch the updated cr to the one bundled in the operator:

```
TASK [entrypoint : Create default ResourcePlans for XXX] **********************
task path: /opt/ansible/roles/entrypoint/tasks/resource-plan.yml:3
...
"resourceVersion": "21572199", "selfLink":changed: [localhost] => {**"changed": true,** "result": {"results": [{"changed": true, **"diff":** {"after": {"metadata": {"generation": 5, "resourceVersion": "21608013"}, "spec": {"children": [{"name": "sample-project", "share": 1}]}}, "before": {"metadata": {"generation": 4, "resourceVersion": "21607747"}, "spec": {"children": [{"name": "sample-projec2222t", "share": 1}, {"name": "sample-project", "share": 1}]}}}, "method": "patch", "result": {"apiVersion": 
...

TASK [entrypoint : Report errors if any] ***************************************
task path: /opt/ansible/roles/entrypoint/tasks/main.yml:27
skipping: [localhost] => {}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
localhost                  : ok=5    **changed**=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

#### What did you expect to see?

To my understanding, the ansible task should only run as once at the start time,  then watch the resources and don't watch any resource in the backlist, so the user can modify them after created by the operator.

#### What did you see instead? Under which circumstances?
blacklist doesn't take effect as the ansible role was called over and over again, it will rollback the user's update on some resources in the blacklist.

#### Environment
ansible operator v1.0.0
Openshift 3.11 and 4.3

**Kubernetes cluster type:**

OpenShift 3.11 and 4.3

`$ operator-sdk version`
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-09-12T23:41:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-07-16T18:50:14Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

No solution
