### ISSUE TITLE
I should be able to serve metrics over https

### ISSUE THREAD

**Issue by shawn-hurley** [operator-framework/operator-sdk#396]
Currently the `ExposeMetricsPort()` does not allow us to serve metrics over https.

I propose that we add an options struct, this will allow a user to specify the certs (maybe even they can generate with the TLS certs?) or if nothing is set, then this happens as it currently works.

We would need to introduce a breaking change to this function. We could just introduce a new function but my vote would be to break the API and have it accept an options struct.

**Comment by hasbro17** [comment]
@LiliC Do we need to reopen this? Don't think we have this yet.

**Comment by LiliC** [comment]
I am working on this right now.

/reopen

**Comment by LiliC** [comment]
# TLS metrics for operators deployed in Open Shift 4.x

The following is based on how kube-state-metrics secures TLS metrics endpoint in Open Shift. For Kubernetes we will add documentation to describe how to secure the metrics endpoints, this is because there is no native solution for this in kubernetes itself. [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/blob/41ed2259ae4cbb744a80033efbacd952bee2ed2d/pkg/scaffold/v1/metricsauth/kustomize_auth_proxy_patch.go) suggests using [kube-rbab-proxy ](https://github.com/brancz/kube-rbac-proxy)and [cert-manager](https://github.com/jetstack/cert-manager) for this, and they do not enable this by default but you have to opt in. We can provide docs and example manifests how to do this and users can follow that.

## TLS in Open Shift 4.x

We need to add the annotation to the service object before the operator is deployed, as we reference the created secret in the deployment itself. So all of these reasources need to be created before the operator starts. So the Service, ServiceMonitor objects will be created using manifest files instead of programitcly as we do right now, this is just for openshift right now. We need a new subcommand `operator-sdk generate openshift` This command can be useful to generate other openshift specific things later on. Right now what it would do is generate the `deploy-openshift` directory. 

The content of the deploy-openshift directory:
```
crds/          service-monitor.yaml  service.yaml       operator.yaml role.yaml            role_binding.yaml   service_account.yaml
```

Content of operator.yaml - deployment manifest file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-operator
  labels:
    name: memcached-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached-operator
  template:
    metadata:
      labels:
        name: memcached-operator
    spec:
      serviceAccountName: memcached-operator
      volumes:
      - name: memcached-operator
        secret:
          secretName: memcached-operator
      - emptyDir: {}
        name: volume-directive-shadow
      containers:
        - name: memcached-operator
          image: myimage:latest
          command:
          - operator-metrics-tls
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "memcached-operator"
        - args:
          - --logtostderr
          - -v=8
          - --secure-listen-address=:9393
          - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
          - --upstream=http://127.0.0.1:8383/
          - --tls-cert-file=/etc/tls/private/tls.crt
          - --tls-private-key-file=/etc/tls/private/tls.key
          image: quay.io/coreos/kube-rbac-proxy:v0.4.1
          name: kube-rbac-proxy-main
          ports:
          - containerPort: 9393
            name: op-metrics
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
          volumeMounts:
          - mountPath: /etc/tls/private
            name: operator-metrics-tls
            readOnly: false
        - args:
          - --logtostderr
          - -v=8
          - --secure-listen-address=:9696
          - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
          - --upstream=http://127.0.0.1:8686/
          - --tls-cert-file=/etc/tls/private/tls.crt
          - --tls-private-key-file=/etc/tls/private/tls.key
          image: quay.io/coreos/kube-rbac-proxy:v0.4.1
          name: kube-rbac-proxy-self
          ports:
          - containerPort: 9696
            name: cr-metrics
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
          volumeMounts:
          - mountPath: /etc/tls/private
            name: memcached-operator
            readOnly: false
```

content of the service.yaml file:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: memcached-operator
  labels:
    name: memcached-operator
  name: memcached-operator
  namespace: default
spec:
  ports:
  - name: cr-metrics
    port: 9696
    targetPort: cr-metrics
  - name: op-metrics
    port: 9393
    targetPort: op-metrics
  selector:
    name: memcached-operator
  type: ClusterIP
```

content of the service-monitor.yaml file:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: memcached-operator
  name: memcached-operator
  namespace: default
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 2m
    port: cr-metrics
    scheme: https
    scrapeTimeout: 2m
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: memcached-operator.default.svc
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 2m
    port: op-metrics
    scheme: https
    scrapeTimeout: 2m
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: memcached-operator.default.svc
  jobLabel: memcached-operator
  selector:
    matchLabels:
        name: memcached-operator
```

Those are the only changes to the files we need to make. 
## Open questions
1. Does this work the same way in 3.x versions of open shift?
2. We can also do work when a new operator is created, if the user knows it will be deployed on openshift only, as part of a flag of the `new` subcommand. The flag would be something like `operator-sdk new --openshift` and it would generate the same resources as above.
