### ISSUE TITLE
How to schedule controller on master nodes only? 

### ISSUE THREAD

**Issue by harche** [operator-framework/operator-sdk#4029]
## Type of question

How to implement a specific feature

#### What did you do?
Before 1.0 release, we could simply append nodeselector in the operator.yaml to make sure the controllers are only scheduled on the master nodes,

```yaml
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 120
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 120
      - effect: NoSchedule
        key: node.kubernetes.io/memory-pressure
        operator: Exists
```
https://github.com/openshift/kata-operator/blob/master/deploy/operator.yaml#L17

I am looking for a pointer on how this can be done for the operator based on sdk 1.0 as there is no explicit operator.yaml in there. 

Looking for steps, don't know how to make sure that controller is scheduled only on master nodes. 

#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`
