### ISSUE TITLE
Add `containerPort` in `webhookdefinitions` while scaffolding CSV

### ISSUE THREAD

**Issue by varshaprasad96** [operator-framework/operator-sdk#4120]
#### What did you do?
Generate package manifests using Operator-SDK `make packagemanifests` target. The `webhookConfig` in CSV appears to be:
```
  webhookdefinitions:
  - admissionReviewVersions:
    - v1beta1
    deploymentName: memcached-operator-controller-manager
    failurePolicy: Fail
    generateName: vmemcached.kb.io
    rules:
    - apiGroups:
      - cache.example.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - memcacheds
    sideEffects: None
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-cache-example-com-v1alpha1-memcached
  - admissionReviewVersions:
    - v1beta1
    deploymentName: memcached-operator-controller-manager
    failurePolicy: Fail
    generateName: mmemcached.kb.io
    rules:
    - apiGroups:
      - cache.example.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - memcacheds
    sideEffects: None
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-cache-example-com-v1alpha1-memcached
```

When I run the operator using olm, the install plan fails since `containerPort` is not specified:
```
Installation of the operator went through but there is an error in OLM operator
[webhooks[0].clientConfig.service.port: Invalid value: 0: port is not valid: must be between 1 and 65535, inclusive,
```

#### What did you expect to see?
Operator running successfully

#### What did you see instead? Under which circumstances?
Since the `ContainerPort` is not specified in CSV, the operator fails. SDK could scaffold the csv with [default webhook container port value](https://godoc.org/k8s.io/api/admissionregistration/v1#ServiceReference).

#### Environment

**Operator type:**

Golang

**Kubernetes cluster type:**

`$ operator-sdk version`
```
operator-sdk version: "v1.0.1", commit: "4169b318b578156ed56530f373d328276d040a1b", kubernetes version: "v1.18.2", go version: "go1.15.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"
```

#### Possible Solution
Scaffold csv with `containerPort` specified in webhookDescription.
