### ISSUE TITLE
Executing a command inside the pod in Reconciliation loop

### ISSUE THREAD

**Issue by psaini79** [operator-framework/operator-sdk#4302]
## Type of question

Best practices

## Question
What is the best way to run the command inside the Pod from the reconciliation loop?

#### What did you do?
I followed this https://github.com/halkyonio/hal/blob/78f0b5ee8e27117b78fe9d6d5192bc5b04c0e5db/pkg/k8s/client.go and implemented the same in reconciliation loop and it works but I am wondering is it the correct way as in my case user cannot pass the kubeconfig location:

```
        reqLogger := log.WithValues("Request.Namespace", request.Namespace, "Request.Name", request.Name)
        reqLogger.Info("Reconciling TestOP")
        var kubeConfig  clientcmd.ClientConfig
        var kubeClient  kubernetes.Interface
        // Kube Client Config Setup
        loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
        configOverrides := &clientcmd.ConfigOverrides{}
        kubeConfig = clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)
        config, err := kubeConfig.ClientConfig()
        if err != nil {
         return reconcile.Result{}, err
        }
        kubeClient, err = kubernetes.NewForConfig(config)
        if err != nil {
         return reconcile.Result{}, err
        }
```
Following is the function which is using remotecommand.NewSPDYExecutor to execute the command:
```
// ExecCMDInContainer execute command in first container of a pod
func ExecCommand(podName string, cmd []string, kubeClient kubernetes.Interface, kubeConfig  clientcmd.ClientConfig) (string) {

        var (
                execOut bytes.Buffer
                execErr bytes.Buffer
        )

        req := kubeClient.CoreV1().RESTClient().
                Post().
                Namespace("default").
                Resource("pods").
                Name(podName).
                SubResource("exec").
                VersionedParams(&corev1.PodExecOptions{
                        Command: cmd,
                        Stdin:   true,
                        Stdout:  true,
                }, scheme.ParameterCodec)

        config, err := kubeConfig.ClientConfig()
        if err != nil {
                return "Error"
        }

        // Connect to url (constructed from req) using SPDY (HTTP/2) protocol which allows bidirectional streams.
        exec, err := remotecommand.NewSPDYExecutor(config, "POST", req.URL())
        if err != nil {
                return "error"
        }

        err = exec.Stream(remotecommand.StreamOptions{
                Stdout: &execOut,
                Stderr: &execErr,
                Tty:    false,
        })

      return  "noerror"
}
```
#### What did you expect to see?

I wanted to what is the best way to read kubeconfig inside operator-sdk so that we can execute command inside the pod.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

Testing/Deployment

`$ operator-sdk version `

`operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"`

`$ go version` (if language is Go)

`go version go1.15.5 linux/amd64`

`$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"336ccfb2560ff170c7ad8aad56944e43e4f6a170", GitTreeState:"clean", BuildDate:"2020-06-09T22:13:31Z", GoVersion:"go1.13.8 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jmrodri** [comment]
@psaini79 I'd like to better understand what you're trying to accomplish. Based on the information above I see a few things.

1. You are trying to execute a command on a pod from your operator. I'm assuming you are trying to run it on the operand pod.
2. Why are you trying to execute a command on the pod? What is it you are trying to accomplish there?
3. You stated "I wanted to what is the best way to read kubeconfig inside operator-sdk so that we can execute command inside the pod." Which kubeconfig are you trying to read? The operator-sdk CLI will use the one you have configured on your system. And the operator-sdk command isn't usually run in the cluster.

If you'd like to chat real time we could chat on kubernetes slack #kubernetes-operators.

**Comment by psaini79** [comment]
@jmrodri 
Thanks for the reply. Below is my use case:
1) I have a number of statefulsets created using operators under a single CR as they all are part of my application.
E.g
```
apiVersion: example.com/v1
kind: ProvApp
metadata:
  name: provapp-sample
spec:
spec:
 myAppSpecs:
    - myAppName: testapp
      myAppSize: 1
      myAppSecretName: db-user-pass
    - myAppName: prodapp
      myAppStageSize: 50Gi
      myAppSize: 1
      myAppSecretName: secret-pass
 myRepoSpecs:
    - myRepoName: testrepo
      myRepoSecretName: secret-pass
```
2)  Whenever I delete testapp or any other stateful set from myAppSpecs , the operator login to myRepoSpecs and cleans all the records of statefulset testapp from myRepoSpecs in this case testrepo is the statefulset.

To achieve the same, I need to execute a command to delete the records on testapp statefulset pod which is testrepo0. What is the best way to achieve the above?

Sure, I will also connect with you on slack.

**Comment by coderanger** [comment]
Mentioned on Slack but overall this is not something OSDK or Kubernetes provides. `kubectl exec` exists for debugging and development, but it's not really suitable for this kind of production-ready use case. You'll need to build something into your tooling for it. If you really want remote execution, you can run `sshd` in a sidecar. Or you can build an HTTP (REST, gRPC, whatever you like) API into your service to handle this. A lot of it depends on your security and stability requirements.

**Comment by camilamacedo86** [comment]
Hi @psaini79,

Why not use the finalizers? The finalizer let you implement what actions/operations should be done to allow effectively delete your CR. See:  https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#handle-cleanup-on-deletion

Then, why you do not use the client provide in the controller to GET/LIST/DELETE/UPDATE all these resources as you wish before the CR be deleted, in the finalizers?

**Comment by psaini79** [comment]
@camilamacedo86 and @coderanger 

Thanks for the reply.

I discussed with @coderanger on the slack and it seems we can use the exec method from the operator but should not be used as the exec method is not the correct way to handle update and delete. Instead, I should use sidecar container or REST server specific to my app. Sidecar will not help in my case. The app running on testrepo stateful set, I need to login in the app and delete the record. However, REST server can do this job but it is extra work for me.

I am trying to understand how can I use the finalizer as I am not deleting CR but deleting a statefulset. For example: 
```
apiVersion: example.com/v1
kind: ProvApp
metadata:
  name: provapp-sample
spec:
spec:
 myAppSpecs:
    - myAppName: testapp
      myAppSize: 1
      myAppSecretName: db-user-pass
    - myAppName: prodapp
      myAppStageSize: 50Gi
      myAppSize: 1
      myAppSecretName: secret-pass
    - myAppName: devapp
      myAppStageSize: 50Gi
      myAppSize: 1
      myAppSecretName: secret-pass
 myRepoSpecs:
    - myRepoName: testrepo
      myRepoSecretName: secret-pass
```

Let us say as per the above conf, I have 4 statefulsets testapp, prodapp, devapp and testrepo are up running. User passes new CR like below:
```
apiVersion: example.com/v1
kind: ProvApp
metadata:
  name: provapp-sample
spec:
spec:
 myAppSpecs:
    - myAppName: testapp
      myAppSize: 1
      myAppSecretName: db-user-pass
 myRepoSpecs:
    - myRepoName: testrepo
      myRepoSecretName: secret-pass
```
Operator logic read the difference between previous statefulset configuration and new CR and perform delete on prodapp and testapp. However, before doing any deletion, operator connect to testrepo and execute a command to delete all the record and balance the data on testapp. Once that part is done then r.Client.Delete function is being called to delete the stateful set.

I am maintaining all the statefulset conf in status struct along with their name. i.e Whenever there is a successful create operation, I record the statefulset name in the status struct and when I found a difference between status struct and instance conf, I execute delete operation on missing statefulsets.

Please let me know if I can use finalizer per statefulset? if yes, how?
