### ISSUE TITLE
Raise the name of the tasks by default in the molecule tests

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4311]
#### Describe the problem you need a feature to resolve.

I'd like to know what task fails in the Molecule tests as it was possible before 1.0+.

#### Describe the solution you'd like.

Update the default `scaffold molecule/default/verify.yml` with : 

```yml
 - name: Re-emit failure
          vars:
            failed_task:
              name: '{{ ansible_failed_task.name }}' // this is the only line that needs to be added 
              result: '{{ ansible_failed_result }}'
          fail:
            msg: '{{ failed_task }}'
```

However, I think we cannot scaffold it in the init. The `ansible_failed_task` will only exist after we scaffold a task for molecule ( create api be executed ).

/language ansible
