### ISSUE TITLE
Query on role.yaml generated by operator-sdk with Go 

### ISSUE THREAD

**Issue by sagar-lonkar** [operator-framework/operator-sdk#4320]
We are using operator-sdk with Go 
Using **make manifest** command , role.yaml gets generated.

As per api marker documentation ( https://book.kubebuilder.io/reference/markers/rbac.html ) , we need to add namespaces value in api marker so that role.yaml have  Role instead of ClusterRole in controller.go files

Q1. How to pass dynamic namespace value to api-marker 

Q2. How to add lables under metadata in generated roles.yaml file  with api marker?

```
metadata:
  creationTimestamp: null
  name: xyz-operator
  labels:
    app.kubernetes.io/instance: xyz-operator
    app.kubernetes.io/managed-by: aaaa
    app.kubernetes.io/name: xyz-operator
```

Q3. For apiGroups security.openshift.io  , we need to add resouceNames in role.yaml

\- apiGroups:
 \- security.openshift.io
  resources:
  \- securitycontextconstraints
  **resourceNames:**
  **- 'restricted'**
  verbs:
  \- 'USE'

How to add resource names with api marker so that it will reflect in role.yaml file?
