### ISSUE TITLE
Operator-sdk  : Cluster Role creation Steps

### ISSUE THREAD

**Issue by psaini79** [operator-framework/operator-sdk#4352]
## Type of question

 Best practices

## Question
I am working on operator-sdk and kept on getting the following error:

```
leaderelection.go:324] error initially creating leader election record: configmaps is forbidden: User "system:serviceaccount:myapp-db:default" cannot create resource "configmaps" in API group "" in the namespace "myapp-db"
```
This operator is cluster scoped.
#### What did you do?

It was working fine but what I did I cleaned all the cluster roles and leader election role by using the files present under config/rbac/*.yaml

The above files are created during the operation compilation and run. Following are the files present in `config/rbac` directory:

```
rw------- 1 root root  429 Dec 20 18:16 leader_election_role.yaml
-rw------- 1 root root  263 Dec 20 18:16 leader_election_role_binding.yaml
-rw------- 1 root root  381 Dec 20 18:16 kustomization.yaml
-rw------- 1 root root  268 Dec 20 18:16 auth_proxy_service.yaml
-rw------- 1 root root  148 Dec 20 18:16 auth_proxy_client_clusterrole.yaml
-rw------- 1 root root  344 Dec 20 18:18 myapp_viewer_role.yaml
-rw------- 1 root root  387 Dec 20 18:18 myapp_editor_role.yaml
-rw------- 1 root root  286 Dec 25 23:03 role_binding.yaml
-rw------- 1 root root  305 Dec 25 23:05 auth_proxy_role.yaml
-rw------- 1 root root  282 Dec 25 23:07 auth_proxy_role_binding.yaml
-rw-r--r-- 1 root root 1048 Dec 25 23:33 role.yaml
```

leader_election_role.yaml
```
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
```

Binding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
```

#### What did you expect to see?

I am wondering what roles I need to assign to my app so that it will start working.

#### What did you see instead? Under which circumstances?

It kept on failing.

#### Environment

$ go version (if language is Go)

`go version go1.15.5 linux/amd64`

$ kubectl version

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"336ccfb2560ff170c7ad8aad56944e
```
$ operator-sdk version
```
operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"
```
