### ISSUE TITLE
enable scorecard to override image pull policy

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/operator-sdk#4423]
## Feature Request

in scorecard today, IfNotpresent is the default pull policy for test images, it would be useful to let users override this within the scorecard config.yaml file to specify for example a pull policy of Always.

https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/testpod.go#L54

#### Describe the solution you'd like.

retain the default perhaps, but allow this value to be overrode within the config.yaml

something like this:
```
kind: Configuration
apiversion: scorecard.operatorframework.io/v1alpha3
metadata:
  name: config
stages:
- tests:
  **- imagePullPolicy:  Always**
  - image: quay.io/operator-framework/tekton-scorecard-image:dev
    entrypoint:
    - tekton-scorecard-tests
    - customtest1
    labels:
      suite: tekton
      test: customtest1

```
