### ISSUE TITLE
k8s_exec

### ISSUE THREAD

**Issue by faust64** [operator-framework/operator-sdk#4561]
## Type of question

How to implement a specific feature

#### What did you do?

Trying to execute commands in Pod:

```
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
    ansible_operator_meta:
      name: kube
      namespace: ci
  tasks:
  - k8s_exec:
      namespace: ci
      pod: scalelite-postgres-kube-5c7866bd85-mscxz
      command: |
          echo "\\d" | psql "$POSTGRESQL_DATABASE" | grep public
    register: notfound
...
```

Also tried:

```
- hosts: localhost
  collections:
  - community.kubernetes
[...]
```

As well as calling `community.kubernetes.k8s_exec` instead of `k8s_exec`.

#### What did you expect to see?

Pod exec that works

#### What did you see instead? Under which circumstances?

k8s_exec is missing:

```
ERROR! couldn't resolve module/action 'community.kubernetes.k8s_exec'. This often indicates a misspelling, missing collection, or incorrect module path.
```

#### Environment

operator-sdk 1.4.0
kubernetes 1.18.3

/language ansible

#### Additional Notes

Apparently, this used to work:
https://github.com/operator-framework/operator-sdk/pull/2716/files#diff-9a6dd8ca707dd2199784617c305de614069d27615a203ab81736c755cfb93850

According to Ansible docs, the k8s_exec should ship with the community.kubernetes plugin, as of 0.10.0:
https://docs.ansible.com/ansible/latest/collections/community/kubernetes/k8s_exec_module.html

Checking modules in operator-sdk 1.4.0 image:

```
bash-4.4$ pip3.8 list
Package             Version  
...
kubernetes          10.1.0   
...
openshift           0.10.3   
...
$ find /usr/local/lib/python3.8 -name '*k8s*py'
/usr/local/lib/python3.8/site-packages/ansible/modules/clustering/k8s/_k8s_facts.py
/usr/local/lib/python3.8/site-packages/ansible/modules/clustering/k8s/_k8s_raw.py
/usr/local/lib/python3.8/site-packages/ansible/modules/clustering/k8s/k8s.py
/usr/local/lib/python3.8/site-packages/ansible/modules/clustering/k8s/k8s_auth.py
/usr/local/lib/python3.8/site-packages/ansible/modules/clustering/k8s/k8s_info.py
/usr/local/lib/python3.8/site-packages/ansible/modules/clustering/k8s/k8s_scale.py
/usr/local/lib/python3.8/site-packages/ansible/modules/clustering/k8s/k8s_service.py
/usr/local/lib/python3.8/site-packages/ansible/plugins/doc_fragments/k8s_auth_options.py
/usr/local/lib/python3.8/site-packages/ansible/plugins/doc_fragments/k8s_name_options.py
/usr/local/lib/python3.8/site-packages/ansible/plugins/doc_fragments/k8s_resource_options.py
/usr/local/lib/python3.8/site-packages/ansible/plugins/doc_fragments/k8s_scale_options.py
/usr/local/lib/python3.8/site-packages/ansible/plugins/doc_fragments/k8s_state_options.py
/usr/local/lib/python3.8/site-packages/ansible/plugins/filter/k8s.py
/usr/local/lib/python3.8/site-packages/ansible/plugins/inventory/k8s.py
/usr/local/lib/python3.8/site-packages/ansible/plugins/lookup/k8s.py
```

I can't find k8s_exec.

Should it be included?
How to proceed executing commands into containers managed by my operator?

Thanks
