### ISSUE TITLE
Are CSV paths for readinessProbe and livenessProbe reversed?

### ISSUE THREAD

**Issue by jwalcorn** [operator-framework/operator-sdk#4601]
## Bug Report

Looking at the generated CSV yaml, under spec.install.spec.deployments, there are two containers: `kube-rbac-proxy`
and `manager`.  The latter has a livenessProbe and a readinessProbe defined.  But the paths look swapped: the `/readyz` path is on the livenessProbe, not on the readinessProbe as you'd expect from a path named "readyz".  The path on the readinessProbe is `/healthz`.  I'm wondering if a copy/paste typo got made here, swapping the two paths.

#### What did you do?

Generated a helm-based operator and looked at the yaml for the CSV.

#### What did you expect to see?

```
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
```

#### What did you see instead? Under which circumstances?

```
                livenessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                readinessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
```

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

v1.4.0

`$ go version` (if language is Go)

`$ kubectl version`

v1.17.2

#### Possible Solution

Swap the paths for the readinessProbe and the livenessProbe

#### Additional context

If the values are somehow correct, perhaps at least generate a comment explaining the confusion
