### ISSUE TITLE
bug in alpha conversion 

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/operator-sdk#4716]
## Bug Report

I'm seeing the following error:

operator-sdk alpha config-3alpha-to-3
Error: unable to load the configuration: unable to create config for version "3-alpha": version 3-alpha is not supported
Usage:
  operator-sdk [flags]

Examples:
The first step is to initialize your project:
    operator-sdk init [--plugins=<PLUGIN KEYS> [--project-version=<PROJECT VERSION>]]

#### What did you do?

Here is the PROJECT file it is reading:

```yaml
domain: example.com
layout: go.kubebuilder.io/v3
projectName: sample-operator
repo: github.com/jmccormick2001/sample-operator
resources:
- crdVersion: v1
  group: cache
  kind: SampleOperand
  version: v1alpha1
version: 3-alpha
plugins:
  manifests.sdk.operatorframework.io/v2: {}
  scorecard.sdk.operatorframework.io/v2: {}
```

#### What did you expect to see?

I expected it to convert the PROJECT to the newest/latest format.

#### What did you see instead? Under which circumstances?

operator-sdk alpha config-3alpha-to-3
Error: unable to load the configuration: unable to create config for version "3-alpha": version 3-alpha is not supported
Usage:
  operator-sdk [flags]

Examples:
The first step is to initialize your project:
    operator-sdk init [--plugins=<PLUGIN KEYS> [--project-version=<PROJECT VERSION>]]

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

snoot:[~/sample-operator] kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

`$ operator-sdk version`

snoot:[~] operator-sdk version
operator-sdk version: "scorecard-kuttl/v2.0.0-43-g6b6c0214", commit: "6b6c021400894281b0d35033e83b5671e4c5f1ac", kubernetes version: "v1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
snoot:[~] go version
go version go1.15.5 linux/amd64

`$ kubectl version`

#### Possible Solution

none

#### Additional context

none
