### ISSUE TITLE
Prometheus ServiceMonitor failing to scrape operator metrics served though kube-proxy HTTPS 8443 port

### ISSUE THREAD

**Issue by slopezz** [operator-framework/operator-sdk#4764]
## Bug Report

I'm using operator-sdk 1.5.0 and I'm trying to gather operator metrics without success.

#### What did you do?

Deployed default operator-sdk v1.5.0 with prometheus metrics enabled at kustomize config level (`config/default/kustomization.yaml`). I'm using `kube-rbac-proxy:v0.5.0` because of issue https://github.com/operator-framework/operator-sdk/issues/4684, but I don't think it affects.
- It is being created the expected controller-manager deployment with kube-proxy metrics enabled at port 8443 (I just copy/paste the relevant parts of the deployed yaml):
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus-exporter-operator-controller-manager
  namespace: prometheus-exporter
   spec:
      containers:
        - name: kube-rbac-proxy
          image: 'gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0'
          args:
            - '--secure-listen-address=0.0.0.0:8443'
            - '--upstream=http://127.0.0.1:8080/'
            - '--logtostderr=true'
            - '--v=10'
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: manager
...
          env:
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'quay.io/3scale/prometheus-exporter-operator:v0.3.0'
          args:
            - '--metrics-addr=127.0.0.1:8080'
            - '--enable-leader-election'
            - '--leader-election-id=prometheus-exporter-operator'
...   
```
- It is being created the expected metrics Service:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: prometheus-exporter-operator-controller-manager-metrics-service
  namespace: prometheus-exporter
  labels:
    control-plane: controller-manager
    operators.coreos.com/prometheus-exporter-operator.prometheus-exporter: ''
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
  selector:
    control-plane: controller-manager
  clusterIP: 172.30.117.225
  type: ClusterIP
  sessionAffinity: None
```
- It is being created the expected ServiceMonitor:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-exporter-operator-controller-manager-metrics-monitor
  namespace: prometheus-exporter
  labels:
    control-plane: controller-manager
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      control-plane: controller-manager
```
#### What did you expect to see?

ServiceMonitor achieves to scrape operator metrics (an so, metric `up=1`).

#### What did you see instead? Under which circumstances?
Service monitor failing (metric `up=0`):
```json
up{container="kube-rbac-proxy",endpoint="https",instance="10.129.2.246:8443",job="prometheus-exporter-operator-controller-manager-metrics-service",namespace="prometheus-exporter",pod="prometheus-exporter-operator-controller-manager-669f6fbdcc2jbm7",prometheus="openshift-user-workload-monitoring/user-workload",service="prometheus-exporter-operator-controller-manager-metrics-service"} | 0
```

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:** Openshift v4.6

`$ operator-sdk version`

```
operator-sdk version: "v1.5.0", commit: "98f30d59ade2d911a7a8c76f0169a7de0dec37a0", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:27:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+bd9e442", GitCommit:"bd9e4421804c212e6ac7ee074050096f08dda543", GitTreeState:"clean", BuildDate:"2021-02-11T23:05:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution

N/A

#### Additional context

If I connect to the controller-manager, manager container, I can check the metrics served through manager protected port 8080 (only available at 127.0.0.1):
```bash
$ kubectl exec -it prometheus-exporter-operator-controller-manager-669f6fbdcc2jbm7 -c manager -- /bin/bash

bash-4.4$ curl 127.0.0.1:8080/metrics
# HELP ansible_operator_build_info Build information for the ansible-operator binary
# TYPE ansible_operator_build_info gauge
ansible_operator_build_info{commit="98f30d59ade2d911a7a8c76f0169a7de0dec37a0",version="v1.4.0+git"} 1
# HELP ansible_operator_reconcile_result Gauge of reconciles and their results.
# TYPE ansible_operator_reconcile_result gauge
ansible_operator_reconcile_result{GVK="monitoring.3scale.net/v1alpha1, Kind=PrometheusExporter",result="succeeded"} 6
# HELP ansible_operator_reconciles How long in seconds a reconcile takes.
# TYPE ansible_operator_reconciles histogram
ansible_operator_reconciles_bucket{GVK="monitoring.3scale.net/v1alpha1, Kind=PrometheusExporter",le="0.005"} 6
...
```

However, if I try to access to the port published through the kube-proxy port, it fails (both http/https schema), which I guess is what prometheus is trying to do with the deployed ServiceMonitor, so failing):

```bash
bash-4.4$ curl 127.0.0.1:8443/metrics
Client sent an HTTP request to an HTTPS server.


bash-4.4$ curl https://127.0.0.1:8443/metrics
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Maybe there are 2 problems?
- Current ServiceMonitor tries to scrape using HTTP schema, but the port is offering HTTPS?
- In addition, although ServiceMonitor uses HTTPS schema (not the case), the certificate is selfsigned, and maybe prometheus would refuse it anyway?

**Comment by criscola** [comment]
Hello, I had the exact same problem and it brought me **a lot of headache**. Try the following:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-exporter-operator-controller-manager-metrics-monitor
  namespace: prometheus-exporter
  labels:
    control-plane: controller-manager
spec:
  endpoints:
    - path: /metrics
      port: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: controller-manager
```
