### ISSUE TITLE
Defaults are not set if all fields are optional and unspecified

### ISSUE THREAD

**Issue by LCaparelli** [operator-framework/operator-sdk#4870]
#### What did you do?

Create a CRD where all fields in the spec are optional and configure defaults via `+kubebuilder:default` comments. These defaults are different from Go's 0 value, hence the need for this:

```go
// KafkaTopicSpec defines the desired state of KafkaTopic
type KafkaTopicSpec struct {
	// Replicas is the replication factor across the brokers
	//+kubebuilder:default=1
	//+optional
	Replicas int `json:"replicas"`
	// Partitions is the number number of partitions in the topic
	//+kubebuilder:default=1
	//+optional
	Partitions int `json:"partitions"`
}
```

With CRDs generated and installed, I applied the following manifest:

```yaml
apiVersion: kafka.gympass.com/v1alpha1
kind: KafkaTopic
metadata:
  name: kafkatopic-sample
spec:
#  replicas: 3
#  partitions: 3
```

#### What did you expect to see?

The default values for all fields within `.spec` are set.

#### What did you see instead? Under which circumstances?

`.spec` does not exist:

```yaml
❯ kubectl get -f config/samples/kafka_v1alpha1_kafkatopic.yaml -o yaml
apiVersion: kafka.gympass.com/v1alpha1
kind: KafkaTopic
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kafka.gympass.com/v1alpha1","kind":"KafkaTopic","metadata":{"annotations":{},"name":"kafkatopic-sample","namespace":"default"},"spec":null}
  creationTimestamp: "2021-05-04T19:33:46Z"
  generation: 1
  managedFields:
  - apiVersion: kafka.gympass.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-05-04T19:33:46Z"
  name: kafkatopic-sample
  namespace: default
  resourceVersion: "2401287"
  uid: 3fb5a081-2193-4c8b-8f00-a5f3e7447a8c
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

```
❯ minikube version
minikube version: v1.17.0
commit: 7e8b5a89575945ba8f8246bfe547178c1a995198
```

`$ operator-sdk version`

```
❯ operator-sdk version
operator-sdk version: "v1.7.1", commit: "c984b00c1a1f75871788bb082ee8226b5118e4da", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)

```
❯ go version
go version go1.15.6 linux/amd64
```

`$ kubectl version`

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

When I provide either field default setting kicks in for the other.

Currently wondering if this has to do with `.spec` being empty, perhaps the default setting logic only kicks in if the parent object in the manifest exists (so it doesn't if `.spec == null`). If that's the case, not sure if there is a way around this.

Specifying `.spec` but not creating any fields within doesn't really do anything, I suppose the API server still interprets it as `.spec == null` (I believe rightfully so).

Am I missing something here? Thanks! :-)

**Comment by estroz** [comment]
What does your CRD's validation scheme look like?

/triage support

**Comment by LCaparelli** [comment]
@estroz here's the entire CRD, please let me know if this is not what you were asking for

<details>
  <summary>CRD</summary>
  
```yaml

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: kafkatopics.kafka.gympass.com
spec:
  group: kafka.gympass.com
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    plural: kafkatopics
    singular: kafkatopic
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KafkaTopic is the Schema for the kafkatopics API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KafkaTopicSpec defines the desired state of KafkaTopic
            properties:
              partitions:
                default: 1
                description: Partitions is the number number of partitions in the
                  topic
                type: integer
              replicas:
                default: 1
                description: Replicas is the replication factor across the brokers
                type: integer
            required:
            - partitions
            type: object
          status:
            description: KafkaTopicStatus defines the observed state of KafkaTopic
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

```
  
</details>

I suppose we can easily work around this with a mutating webhook, but I was wondering if it was possible using OpenAPI only.
