### ISSUE TITLE
Ansible debug task not working in a loop in ansible-operator

### ISSUE THREAD

**Issue by fridim** [operator-framework/operator-sdk#4872]
#### What did you do?

Please consider the following debug tasks in:

```yaml
- hosts: localhost
  gather_facts: false
  vars:
    lines:
    - 1
    - 2
    - 3
  tasks:

    - name: Debug without loop
      debug:
        msg: "{{ lines }}"

    - name: Debug with loop
      loop: "{{ lines }}"
      debug:
        msg: "{{ item }}"
```

Running locally, with ansible, the 2 `debug` tasks work and print the lines.

When running in quay.io/operator-framework/ansible-operator:v1.7.0, only the task `Debug without loop` task appears in logs.

Output:

```
--------------------------- Ansible Task StdOut -------------------------------

 TASK [Debug without loop] ********************************
ok: [localhost] => {
    "msg": [
        1,
        2,
        3
    ]
}

-------------------------------------------------------------------------------
{"level":"info","ts":1620205414.6191092,"logger":"logging_event_handler","msg":"[playbook debug]","name":"gpte-agnosticv","namespace":"agnosticv-operator","gvk":"gpte.redhat.com/v1, Kind=AgnosticVRepo","event_type":"runner_on_ok","job":"6129484611666145821","EventData.TaskArgs":""}
```

The  task `Debug with loop` doesn't appear in log. I don't know if it was executed or not.

#### What did you expect to see?

I expect the `debug` task to work with a `loop` too.

#### Workaround

Use `include_tasks` and put the `debug` task in another task file:

```yaml
    - name: Debug with loop + include_tasks
      loop: "{{ lines }}"
      include_tasks: print_error.yaml
```

```yaml
---
- debug:
    msg: "{{ item }}"
```

#### Environment

**Operator type:**  quay.io/operator-framework/ansible-operator:v1.7.0

Also tried: ansible-operator:v1.6.2

/language ansible

**Kubernetes cluster type:** OpenShift 4.6.22
