### ISSUE TITLE
feature: dynamic inventory of resources created by a CR of an ansible operator

### ISSUE THREAD

**Issue by jobcespedes** [operator-framework/operator-sdk#4887]
## Feature Request
Dynamic inventory of resources created by a CR of an ansible operator

#### Describe the problem you need a feature to resolve.
Operating or running ansible tasks over pods generated by a CR of an ansible operator is kind of cumbersome. One could use kubectl connection plugin and add them dynamically during each reconciliation loop using variables. The existing dynamic k8s inventory plugin could be a better fit. However, adding it to an ansible operator requires some steps. In addition, when done, it shows all the pods and services the operator has access and groups them in a way, in my opinion, not intuitive for operator scope. They could not be filter

#### Describe the solution you'd like.

The operator sdk to already include a dynamic inventory ansible plugin that groups and adds only the pods, and optionally other kind of resources, of the CR the reconciliation loop is running. I would like to run some complementary ansible tasks over some of those pods. How it groups them should be intuitive in order to reference hosts, or groups more probably, in playbooks inside the operator. For instance: the name of a default group of all pods of a CR could be used as: `hosts: {{ ansible_operator_meta.namespace }}__{{ ansible_operator_meta.namespace }}`. In addition, it would be helpful to define custom group formats using labels and add extra ansible variables using annotations. The following example shows a posible pod definition to be considered as part of a CR inventory, to define a custom group membership and extra ansible variables:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    # Define a variable for this pod only
    ansible.sdk.operatorframework.io/inventory_variable: '{"ansible_remote_tmp": "/var/tmp/.ansible"}'
  labels:
    # Define a label to be included in an specific inventory.  
    ansible.sdk.operatorframework.io/inventory: "mynamespace/mysample"  
    # A default group for all pods could be <mynamespace>__<mysample>__pods
    # Define a custom group membership to <mynamespace>__<mysample>__<mygroup>__pods could be defined with:
    ansible.sdk.operatorframework.io/inventory_group: "mygroup"
```
The custom CR could be:
```yaml
apiVersion: sample.example.com/v1alpha1
kind: Sample
metadata:
  name: mysample
  namespace: mynamespace
  annotations:
    # Define which label selector to use and specific inventory for this CR.  
    ansible.sdk.operatorframework.io/inventory: "mynamespace/mysample"  
    # Define a variable for all resources
    ansible.sdk.operatorframework.io/inventory_variable: '{"ansible_python_interpreter": "/usr/libexec/platform-python"}'
```
> Using ansible to manage pods could be considered an anti-patter for k8s. 

However, it could complement k8s where some functionality is lacking or to add some logic to an operator. 

/language ansible
