### ISSUE TITLE
Operator-sdk doesn't install operator controller pod

### ISSUE THREAD

**Issue by psaini79** [operator-framework/operator-sdk#4965]
#### What did you do?

Build the docker images for the operator and bundle. Push the images to the repo. Execute the following command to pull the bundle and it command went fine:
```
operator-sdk run bundle <bundle_img>
```

The operator-sdk doesn't install operator and showing the following:
```
# kubectl logs -f pod/ub-region-internalcloud-myappcorp-com-myapp-database-operator-bundle-0-0-1 -n myapp-db
time="2021-06-04T00:20:18Z" level=info msg="adding to the registry" bundles="[myapppack-docker-images.dockerhub-region.internalcloud.myappcorp.com/myapp/database-operator-bundle:0.0.1]"
time="2021-06-04T00:20:19Z" level=info msg="Could not find optional dependencies file" dir=bundle_tmp469698613 file=bundle_tmp469698613/metadata load=annotations
time="2021-06-04T00:20:19Z" level=info msg="found csv, loading bundle" dir=bundle_tmp469698613 file=bundle_tmp469698613/manifests load=bundle
time="2021-06-04T00:20:19Z" level=info msg="loading bundle file" dir=bundle_tmp469698613/manifests file=myapp-database-operator.clusterserviceversion.yaml load=bundle
time="2021-06-04T00:20:19Z" level=info msg="Keeping server open for infinite seconds" database=/database/index.db port=50051
time="2021-06-04T00:20:19Z" level=info msg="serving registry" database=/database/index.db port=50051


# kubectl get all -n myapp-db
NAME                                                                  READY   STATUS      RESTARTS   AGE
pod/80258fe0202bdc623ffea3622e6c76d67c614e246b8e505e4cf09c63acmgt9j   0/1     Completed   0          43m
pod/ub-region-internalcloud-myappcorp-com-myapp-database-operator-bundle-0-0-1   1/1     Running     0          44m

NAME                                                                        COMPLETIONS   DURATION   AGE
job.batch/80258fe0202bdc623ffea3622e6c76d67c614e246b8e505e4cf09c63aca32b4   1/1           10s        43m
```

#### What did you expect to see?

It must install an operator controller pod but that is not created here.

#### What did you see instead? Under which circumstances?

We just see the operator bundle image and the following:
```
# kubectl -n myapp-db get subscription
NAME                                  PACKAGE                    SOURCE                             CHANNEL
myapp-database-operator-v0-0-1-sub   myapp-database-operator   myapp-database-operator-catalog   alpha
# kubectl -n myapp-db get csv
NAME                              DISPLAY                       VERSION   REPLACES   PHASE
myapp-database-operator.v0.0.1   MYApp distributed DB Operator   0.0.1                Succeeded
```
#### Environment

**Operator type:**

 /language go

**Kubernetes cluster type:**

Vanilla

`$ operator-sdk version`

```
operator-sdk version: "v1.8.0", commit: "d3bd87c6900f70b7df618340e1d63329c7cd651e", kubernetes version: "1.20.2", go version: "go1.16.4", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)

 `go version go1.16.3 linux/amd64` 

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10+3.el7", GitCommit:"e276f9329308bbb35a9f81bcfb945d49907d23c1", GitTreeState:"clean", BuildDate:"2021-01-14T23:30:22Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10+2.el8", GitCommit:"829f162e7aeba291f1ecaffb509f387d81f58273", GitTreeState:"clean", BuildDate:"2020-10-30T20:29:26Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by estroz** [comment]
If the CSV has a `Succeeded` phase then whatever was in the CSV was created. What's the output of `kubectl get pods --all-namespaces`?

/triage needs-information

**Comment by psaini79** [comment]
Following is the ouput:

```
[root@rwsoda210db1 ~]# kubectl get pods --all-namespaces
NAMESPACE              NAME                                                              READY   STATUS      RESTARTS   AGE
kube-system            coredns-8495db769c-btzzc                                          1/1     Running     0          28d
kube-system            coredns-8495db769c-sc5mz                                          1/1     Running     0          28d
kube-system            etcd-rwsoda210db1                                                 1/1     Running     0          40d
kube-system            etcd-rwsoda210db2                                                 1/1     Running     0          40d
kube-system            kube-apiserver-rwsoda210db1                                       1/1     Running     2          40d
kube-system            kube-apiserver-rwsoda210db2                                       1/1     Running     0          40d
kube-system            kube-controller-manager-rwsoda210db1                              1/1     Running     1          40d
kube-system            kube-controller-manager-rwsoda210db2                              1/1     Running     1          40d
kube-system            kube-flannel-ds-69hf7                                             1/1     Running     0          40d
kube-system            kube-flannel-ds-dspjd                                             1/1     Running     0          35d
kube-system            kube-flannel-ds-pfqwg                                             1/1     Running     0          40d
kube-system            kube-flannel-ds-qtxgn                                             1/1     Running     0          40d
kube-system            kube-flannel-ds-wzhlb                                             1/1     Running     0          40d
kube-system            kube-proxy-8dbhn                                                  1/1     Running     0          40d
kube-system            kube-proxy-rtqz4                                                  1/1     Running     0          35d
kube-system            kube-proxy-wnmjx                                                  1/1     Running     0          40d
kube-system            kube-proxy-xffb4                                                  1/1     Running     0          40d
kube-system            kube-proxy-xtb86                                                  1/1     Running     0          40d
kube-system            kube-scheduler-rwsoda210db1                                       1/1     Running     0          40d
kube-system            kube-scheduler-rwsoda210db2                                       1/1     Running     2          40d
kubernetes-dashboard   kubernetes-dashboard-667547dc97-dbht2                             1/1     Running     0          40d
olm                    catalog-operator-5b484889dc-98rtb                                 1/1     Running     0          2d
olm                    olm-operator-69c5ff9b78-7k7gp                                     1/1     Running     0          2d
olm                    operatorhubio-catalog-zzvl8                                       1/1     Running     0          2d
olm                    packageserver-7f4cc65767-9jb8s                                    1/1     Running     1          2d
olm                    packageserver-7f4cc65767-wgtfl                                    1/1     Running     0          2d
myapp-db              80258fe0202bdc623ffea3622e6c76d67c614e246b8e505e4cf09c63acmgt9j   0/1     Completed   0          24h
myapp-db              ub-phx-oci-myappcorp-com-myapp-database-operator-bundle-0-0-1   1/1     Running     0          24h

```

Is there anything I missed building the bundle?

**Comment by estroz** [comment]
Likely not. If your CSV `myapp-database-operator.clusterserviceversion.yaml` contains a Deployment for your controller-manager then a controller-manager pod will be created. Did `operator-sdk run bundle` actually fail, or did the CSV show `Succeeded` in command output? What's the output of
```sh
kubectl get events -n myapp-db
```

**Comment by psaini79** [comment]
# kubectl get events -n myapp-db
No resources found in myapp-db namespace.

**Comment by psaini79** [comment]
this our clusterserviceversion.yaml

```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: myapp-database-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: appauto is the Schema for the appautodatabases API
      displayName: appauto Database
      kind: appauto
      name: appautodatabases.database.myapp.com
      version: v1alpha1
    - description: Provdist is the Schema for the provdist API
      displayName: Prov dist
      kind: Provdist
      name: provdist.disting.myapp.com
      version: v1alpha1
  description: Operator to manage myapp disting
  displayName: myapp disting DB Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - myapp
  - disting
  - db
  links:
  - name: myapp Database Operator
    url: https://myapp-database-operator.domain
  maturity: alpha
  provider:
    name: Provdist
  version: 0.0.0
```
