### ISSUE TITLE
Not able to assign resources that is cpu request and limits and memory request and limits for operator pod containers. 

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-sdk#4974]
## Bug Report
I have added the resources that is cpu requests and limits and memory requests and limits to both the operator containers as shown in below CSV file. After the operator installation resources section is empty i.e. resources: { }.

Please find below attached CSV file operator deployment section:

```
install:
    spec:
      deployments:
      - name: <operator-name>  
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: <operator-name>  
          template:
            metadata:
              annotations:
                name: <operator-name>           
              labels:
                name: <operator-name>          
            spec:
              containers:
              - name: kube-rbac-proxy
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 50Mi
              - name: manager
                image: docker.io/<operator-name>@sha256:<sha-256-code>
                resources:
                  limits:
                    cpu: 900m
                    memory: 400Mi
                  requests:
                    cpu: 1500m
                    memory: 1000Mi
```
#### Environment

Ansible-based operator - operator-sdk v1.7.2 

Tested on OpenShift v4.7

Expected to show the resources defined in the CSV file in operator pod YAML file after the successful installtion.
