### ISSUE TITLE
Changes in the config/manifests/bases/<operator-name>.clusterserviceversion.yaml has been overwritten 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5000]
## Bug Report

Changes in the config/manifests/bases/<operator-name>.clusterserviceversion.yaml has been overwritten 

#### What did you do?

1. Update `spec.relatedImages` in `config/manifests/bases/<operator-name>.clusterserviceversion.yaml` and described in the doc https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html. 

```
...
spec:
  relatedImages: 
    - name: etcd-operator 
      image: quay.io/etcd-operator/operator@sha256:d134a9865524c29fcf75bbc4469013bc38d8a15cb5f41acfddb6b9e492f556e4 
    - name: etcd-image
      image: quay.io/etcd-operator/etcd@sha256:13348c15263bd8838ec1d5fc4550ede9860fcbb0f843e48cbccec07810eebb68
...
```
2. Run `make bundle` or `operator-sdk generate kustomize manifests --interactive=false -q`

#### What did you expect to see?

The bundle be generated using the updates for the CSV base

#### What did you see instead? Under which circumstances?

The changes made are lost:

https://user-images.githubusercontent.com/7708031/122774750-64582d00-d2a1-11eb-9994-efd1621627a4.mov

#### Environment

`$ operator-sdk version` SDK `1.5.0`

#### Additional context

See also: 
https://github.com/operator-framework/operator-sdk/issues/4992
