### ISSUE TITLE
Bundle yaml files generated by v1.8.0 and above fail to install on OpenShift 4.7

### ISSUE THREAD

**Issue by amisevsk** [operator-framework/operator-sdk#5033]
## Bug Report
Apologies if this bug belongs in https://github.com/operator-framework/operator-lifecycle-manager instead, I wasn't sure.

#### What did you do?
1. `operator-sdk generate bundle` after updating to operator-sdk v1.8.0 from v1.7.2. 
2. Build bundle image
3. `opm index add <args>`
4. register catalog source and install operator

Release v1.8.0 appears to change how bundle files are formatted, wrapping long strings (e.g. in descriptions) instead of leaving them on one line. Checking for semantic differences (i.e. ignoring formatting) the files are identical.

#### What did you expect to see?
Operator installs normally from OpenShift UI

#### What did you see instead? Under which circumstances?
Operator's InstallPlan hangs on `UpgradePending`, with conditions
```
  conditions:
  - message: bundle contents have not yet been persisted to installplan status
    reason: BundleNotUnpacked
    status: "True"
    type: BundleLookupNotPersisted
  - lastTransitionTime: "2021-06-30T18:59:47Z"
    message: unpack job not completed
    reason: JobIncomplete
    status: "True"
    type: BundleLookupPending
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**
OpenShift 4.7

`$ operator-sdk version`
operator-sdk v1.8.0 and v1.9.0

Does not reproduce in v1.7.2

`$ go version` (if language is Go)
go version go1.16.4 linux/amd64

`$ kubectl version`
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+bd9e442", GitCommit:"bd9e4421804c212e6ac7ee074050096f08dda543", GitTreeState:"clean", BuildDate:"2021-02-11T23:05:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution
If I force long strings back onto one line using
```
find . -name *.yaml -exec yq --indentless -i -y -w 1000000000 . {} \;
```
in the bundle/manifests dir, the install succeeds as normal.

#### Additional context
By no means a minimal reproducer, but if you register the following catalogsource and install the DevWorkspace Operator via UI, the issue should reproduce:

```yaml
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-devworkspace-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/amisevsk/devworkspace-operator-index:failed-install
  publisher: amisevsk
  displayName: DevWorkspace Operator Catalog
EOF
```
