### ISSUE TITLE
Controller manager's yaml

### ISSUE THREAD

**Issue by sqqqrly** [operator-framework/operator-sdk#5077]
#### What did you do?

Ran OSDK init.  Built and pushed my operator image using tag v2.1.0.

#### What did you expect to see?

Expected that when I make changes to the operator image and redeployed, that the changes would be in effect on the CRC cluster. 

#### What did you see instead? Under which circumstances?

The operator image silently never gets pulled again after the first time due to the imagePullPolicy of "ifNotFound.  The imagePullPolicy is not explicitly set in the manager's yaml.  I had to add a line as shown below.
```
# config/manager/manager.yaml
.....
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - --leader-elect
        - --leader-election-id=infinibox-operator
        image: controller:latest
        imagePullPolicy: Always               <------- Fix - Add new line to override default policy.
        name: manager
.....
```

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:**

OpenShift/CRC

╰─➤  operator-sdk version
operator-sdk version: "v1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "1.20.2", go version: "go1.16.5", GOOS: "linux", GOARCH: "amd64"

╰─➤  kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+75370d3", GitCommit:"75370d3fb99594d6f0263f3de0bd08237381b77d", GitTreeState:"clean", BuildDate:"2021-05-09T17:55:51Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

Set the controller-manager's imagePullPolicy to Always.
