### ISSUE TITLE
operator sdk ansible vault password not loaded

### ISSUE THREAD

**Issue by nielsvanderbeke** [operator-framework/operator-sdk#5091]
## Type of question

General operator-related help

#### What did you do?

We have a custom operator based on `quay.io/operator-framework/ansible-operator:v1.9.0` where we use secrets stored in ansible-vault. The ansibel-vault password is loaded using a vault password file that is mounted to the operator using Openshift Secret volume mounts.
We based the config for the k8s deployment on the documentation : https://sdk.operatorframework.io/docs/building-operators/ansible/reference/advanced_options/#using-ansible-vault

```yaml
kind: Deployment
apiVersion: apps/v1
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_VAULT_PASSWORD_FILE
              value: /etc/secrets/ansible-vault-password
            - name: OPERATOR_NAME
              value: springboot-operator
            - name: WATCH_NAMESPACE
              value: tribe-css
          args:
            - '--health-probe-bind-address=:6789'
            - '--metrics-bind-address=127.0.0.1:8080'
            - '--leader-elect'
            - '--leader-election-id=telenetmanagedapp-operator'
            - >-
              --ansible-args='--vault-password-file
              /etc/secrets/ansible-vault-password'
            - '--ansible-verbosity'
            - '0'
            - '--max-concurrent-reconciles'
            - '10'
```

#### What did you expect to see?

the vault variable file being decoded

#### What did you see instead? Under which circumstances?

vault variables not being decoded

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

Openshift 4.7

`$ operator-sdk version`

operator-sdk version: "v1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "1.20.2", go version: "go1.16.5", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.13.15 linux/amd64
