### ISSUE TITLE
Customize helm operator values on the fly based on user provided values

### ISSUE THREAD

**Issue by michallula** [operator-framework/operator-sdk#5147]
## Type of question

How to implement a specific feature

#### What did you do?

My team created helm based operator for the cluster scheduler purposes. Our chart depends on Airflow and PostgreSQL operator CRD sub-charts. We provided default values that configure these dependencies' interactions. Such values contain a lot of boilerplate code which needs to be provided by our end-users.

#### What did you expect to see?

Our goal is to require only providing scheduler name and dags source code. We would like to generate all boilerplate values on the fly and apply them during chart installation. Most of the dynamic values will depend on the scheduler name and namespace. We don't know if such customization is possible with the standard helm operator flow.

#### What did you see instead? Under which circumstances?

Here is the example of simplified values files that we have now:

```
airflow:
  externalDatabase:
    host: myteam-mydb-pgsql
    passwordSecret: "airflow.myteam-mydb-pgsql.credentials.postgresql.acid.zalan.do"
    passwordSecretKey: "password"
  ingress:
    web:
      host: mydb-mynamespace.mydomain.com

externalpostgres:
  teamId: myteam
  name: mydb
```

all these values need to be set by the user during CRD creation, but in fact, all these values are derived from `teamId`, and `name` values.

/language helm
