### ISSUE TITLE
CSV Field Markers are not collected if they are in subdirectory in nested substructure

### ISSUE THREAD

**Issue by adamdyszy** [operator-framework/operator-sdk#5166]
#### What did you do?

0. Its similar to this issue but the difference is that I have files in a subdirectory:
[CSV Field Markers are not collected if they are in another go file] https://github.com/operator-framework/operator-sdk/issues/3744

1. Add a new directory into the API structure of my operator:

https://github.com/IBM/ibm-licensing-operator/tree/operator_sdk_nested_struct_bug_showcase/api/v1alpha1/features

2. Add nested structures in the features directory:
- one that is redeclared in v1alpha1 directory but redeclaring the structure is not expected behavior, I just found out that it worked with such redeclaration
- one that is not

below commit comments show the problem perfectly:

https://github.com/IBM/ibm-licensing-operator/commit/fb7fd51a5a04d70454f7e915658a6b25bf3338f9

3. After using operator-sdk, CSV has no inner fields for structure someStruct2 that is not redeclared in v1alpha1.

```bash
operator-sdk generate kustomize manifests
```

```yaml
          - description: Set additional features under this field
            displayName: Features
            path: features
          - description: Some string
            displayName: SomeString
            path: features.someString
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Some struct
            displayName: SomeStruct
            path: features.someStruct
          - description: Some string
            displayName: SomeString
            path: features.someStruct.someString
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Some struct 2
            displayName: SomeStruct2
            path: features.someStruct2
```

#### What did you expect to see?

After step 3 so after using the generation command this is what I would want to see:

```yaml
          - description: Set additional features under this field
            displayName: Features
            path: features
          - description: Some string
            displayName: SomeString
            path: features.someString
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Some struct
            displayName: SomeStruct
            path: features.someStruct
          - description: Some string
            displayName: SomeString
            path: features.someStruct.someString
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Some struct 2
            displayName: SomeStruct2
            path: features.someStruct2
          - description: Some string
            displayName: SomeString
            path: features.someStruct2.someString
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
```

#### What did you see instead? Under which circumstances?

This part was not generated in CSV:

```yaml
          - description: Some string
            displayName: SomeString
            path: features.someStruct2.someString
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk v1.11.0 https://github.com/operator-framework/operator-sdk/releases/tag/v1.11.0

```bash
operator-sdk version: "v1.11.0", commit: "28dcd12a776d8a8ff597e1d8527b08792e7312fd", kubernetes version: "1.20.2", go version: "go1.16.7", GOOS: "darwin", GOARCH: "amd64"
```

`$ go version` (if language is Go)

```bash                         
go version go1.15.7 darwin/amd64
```

`$ kubectl version`

This is not important here
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
```
