### ISSUE TITLE
Operator stops reconciling and starts printing the level info message infinite times.

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-sdk#5179]
# Bug Report

In my ansible operator, I have the below task in one of the roles. The task is used to wait for a resource pod to get into ready status, before executing the other tasks.

I have tested the same task in my local machine, using the ansible-playbook command, It is working perfectly as expected.

When I added the same task into my operator code, I could see the infinite times the below message is getting printed, even after the pod is in a ready state within the given time.

After a certain amount of time, the Operator has started executing the tasks again and seen the desired behavior and the below lines are not displayed in the logs. When I tried to delete the resource again I could see the same logs infinite times even after the pod is ready. This kind of behavior is not seen when executed the same task using the ansible-playbook on my local machine.

{"level":"info","ts":1630485881.8993182,"logger":"proxy","msg":"Cache miss: /v1, Kind=Pod, test-setup-1/pod-name-6649985545-bmxjs"}
{"level":"info","ts":1630485881.9038098,"logger":"proxy","msg":"Cache miss: /v1, Kind=Pod, test-setup-1/pod-name-6649985545-bmxjs"}

# Task
```
- name: Waiting for component pod to get Ready
  community.kubernetes.k8s_info:
    kind: Pod
    label_selectors:
      - "app = {{ component_name }}"
    namespace: "{{ meta.namespace }}"
    wait: yes
    wait_sleep: 10
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: "True"
  when: component_size != 0
```

# Operator Type
Ansible Based

# Operator-SDK Version
1.8.2

# OpenShift Cluster 
Tested on OpenShift Cluster 4.6 and 4.7.4
