### ISSUE TITLE
Flags/Args for an Operator

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-sdk#519]
In an Operator we're building, objects to be deployed may depend on admin's choice. For example, an admin may not want to deploy a DB along with the main application, but rather use an existing one. Also, instead of generating passwords, there should be a way to define those. We may also need an admin to define some external endpoints for an app to connect to (Keycloak or Postgres DB for example).

The only thing I consider not is adding env variables to operator deployment yamls, and capture those envs  when creating objects.

Is there perhaps a better way to do that? I think it's possible to define flags to operator in the Dockerfile too, and capture those.

**Comment by hasbro17** [comment]
@eivantsov I'm not sure I fully understand but if you just want to define and be able to pass flags to your operator you should be just define those in `main.go` for your operator:
```Go
import "flag"

var DatabaseService string

func init() {
    flag.StringVar(&DatabaseService, "database-service", "", "Service for accessing database")
    flag.Parse()
}
func main() {
    if len(DatabaseService) > 0 {
        ...
    }
    ...
}
```

And then in your operator deployment manifest you can pass in the flag as part of the `command` to your operator's container:
```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached-operator
  template:
    metadata:
      labels:
        name: memcached-operator
    spec:
      containers:
        - name: memcached-operator
          image: quay.io/example/memcached-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - memcached-operator
          - --database-service=xyz
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "memcached-operator"
```
You can pass in the arguments to your operator in a number of different ways
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

Same thing with args. You can use os.Args to get the arguments to your program.

But the point is you can define the above as you like for your operator. Does that answer your question or were you thinking of something that the SDK would do by default for args/flags.
