### ISSUE TITLE
Running bundle creates "runAsNonRoot" error

### ISSUE THREAD

**Issue by tylerslaton** [operator-framework/operator-sdk#5213]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/

### Which section(s) is the issue in?

"Run your bundle. If your bundle image is hosted in a registry that is private and/or has a custom CA, these configuration steps must be complete."

### What needs fixing?

After running the `operator-sdk run bundle` command the pod seems to fail with the following error:

```yaml
state:
  waiting:
    message: 'container has runAsNonRoot and image will run as root (pod: "memcached-operator-controller-manager-677d7c7469-5wmp5_default(22ae39f5-9493-497d-a70b-f2d5c3c462fe)", container: manager)'
    reason: CreateContainerConfigError
```

Which was found by running the following on the pod that was created:

```bash
k get po memcached-operator-controller-manager-677d7c7469-5wmp5 -o yaml
```

#### Additional context

Here is the Dockerfile generated by the `operator-sdk init` command
```Dockerfile
# Build the manager binary
FROM golang:1.16 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]
```
