### ISSUE TITLE
Getting Ansible Operator Status with AdditionalPrinterColumns

### ISSUE THREAD

**Issue by piyat** [operator-framework/operator-sdk#5229]
## Type of question

Open question

## Question
I am using operator-sdk to make an ansible operator. I’m trying to customise the output of `oc get` on my custom resource with additionalPrinterColumns in the CRD. I would like to understand whether it is possible to format the output in the way that I would like or find out if there are other ways to achieve this. The two things I'm having trouble with are:

- Printing the last completed sync in date format
- Truncating, indenting, prettifying output of the message field

To get the value of last completed sync, I'm using the field: `.status.conditions[0].ansibleResult.completion`
To get the value of message, I'm using the field: `.status.conditions[-1].message`

#### What did you do?

I edited the CRD and added the following additionalPrinterColumns:
```
    - additionalPrinterColumns:
        - description: Time elapsed since last reconciliation.
          jsonPath: .status.conditions[0].ansibleResult.completion
          name: Last Sync
          type: date
        - description: Status of last reconciliation.
          jsonPath: .status.conditions[-1].reason
          name: Status
          type: string
        - description: Time elapsed since this configuration was created.
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - description: Last reconciliation message.
          jsonPath: .status.conditions[-1].message
          name: Message
          type: string
```

#### What did you expect to see?

I expected the output to resemble this:

```
NAME    LAST SYNC    STATUS       AGE   MESSAGE
team1   5m           Successful   36m   Awaiting next reconciliation
team2   1m           Failed       36m   The task includes an option with an undefined variable.
                                        The error appears to be in....
team3   5m           Successful   36m   Awaiting next reconciliation
```

#### What did you see instead? Under which circumstances?

I see the below, I think because:
- A datetime formatted like this 2021-09-21T11:19:56.816187 is not accepted by k8s (setting `type: string` in the crd printer columns results in that date being printed, but then I can't sort on this column).
- Unhandled ansible errors cause verbose output. This multiline string is not indented or truncated. 

```
NAME   LAST SYNC   STATUS      AGE   MESSAGE
team1  <invalid>   Successful  36m   Awaiting next reconciliation
team2  <invalid>   Failed      36m   The task includes an option with an undefined variable.
The error appears to be in '/opt/ansible/roles/hummus/tasks/main.yaml': line 31, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: Append created bindings to list
    ^ here
team3  <invalid>   Successful  36m   Awaiting next reconciliation
```

#### Environment

Operator type:
/language ansible

Kubernetes cluster type:
OpenShift 4.7.12

$ operator-sdk version

operator-sdk version: "v1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "1.20.2", go version: "go1.16.5", GOOS: "darwin", GOARCH: "amd64"

ansible-operator image
quay.io/operator-framework/ansible-operator:v1.9.0

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+df9c838", GitCommit:"df9c8387b2dc2308da01706ff89982c6b7ad9c48", GitTreeState:"clean", BuildDate:"2021-05-15T22:35:16Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context

I think I'm probably hitting the limitations of the k8s jsonPath implementation. I just wondered if others have seen similar and worked around this problem.

I might be using the wrong field for `Last Sync` but would like to know whether the date format can be changed to be compatible (avoid the <invalid> output).

Unhandled ansible errors cause verbose, multiline output in `.status.conditions[-1].message` which is not indented so looks a bit messy. I would still like to print the message but have it either indented or ideally truncated.
