### ISSUE TITLE
Helm operator selector does not pick updates in CR labels

### ISSUE THREAD

**Issue by tfluehmann** [operator-framework/operator-sdk#5256]
#### What did you do?

I am running two separate helm operators in a Kubernetes cluster. Both should look at the same type of custom resource but should look for different labels (or a label exists or not). I installed two different selectors in the watches.yml file for both operators, one should look at the label `operatorTest`, the other one should not:
`watches.yml`
Operator A:
```yaml
---
- version: v1alpha1
  group: example.org
  kind: Example
  chart: /opt/helm/helm-charts/example
  selector:
    matchExpressions:
     - {key: operatorTest, operator: In, values: ["true"]}
```

Operator B:
```yaml
---
- version: v1alpha1
  group: example.org
  kind: Example
  chart: /opt/helm/helm-charts/example
  selector:
    matchExpressions:
     - {key: operatorTest, operator: NotIn, values: ["true"]}
```
I installed a custom resource without a label and it was correctly picked up and installed by operator B:
```yaml
apiVersion: example.com/v1alpha1
kind: Example
metadata:
  name: example
  namespace: example
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: default-node-pool
            operator: In
            values:
            - "true"
```
A little later I added the `operatorTest` label with the value `"true"` to the created custom resource and I expected it to be picked up by operator A which did not happen.
```yaml
  labels:
    operatorTest: "true"
```
I had to restart both operators, Operator B to not track the resource anymore, and Operator A to track it.

#### What did you expect to see?

I expected Operator A to track the resource after I added the label and Operator B to leave the work to Operator A.

#### What did you see instead? Under which circumstances?

I actually saw Operator B continuing doing the work and Operator A doing nothing. Only after restarting both operators the behavior was as expected.

#### Environment

/language helm

**Kubernetes cluster type:**

Kubernetes GKE instance

`$ operator-sdk version`

```
"Version","Go Version":"go1.16.8","GOOS":"linux","GOARCH":"amd64","helm-operator":"v1.12.0","commit":"d3b2761afdb78f629a7eaf4461b0fb8ae3b02860"
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-16T02:41:51Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.9-gke.1001", GitCommit:"1fe18c314ed577f6047d2712a9d1c8e498e22381", GitTreeState:"clean", BuildDate:"2021-08-23T23:06:28Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution

Based on the observations I have made, I assume the resources are only checked for their labels once at the beginning. I would suggest to check the tracked custom resources constantly for label changes if there is a label selector in the watches file for a specific label.
