### ISSUE TITLE
Objects created without ownerReference injected when using force in k8s ansible module

### ISSUE THREAD

**Issue by Roia5** [operator-framework/operator-sdk#5257]
#### What did you do?

When attempting to use k8s module to deploy objects using operator-sdk,
I tried to change the ```apply: true``` parameter into ```force: true```.
When using force, the objects are all created without the CR owner.
As a result they are not deleted when the CR is deleted.

#### What did you expect to see?
A correct owner reference to the CR.

#### What did you see instead? Under which circumstances?

Objects without an owner. (including statefulsets, deployments...)

#### Environment

**Operator type:**

 /language ansible 

**Kubernetes cluster type:**

OpenShift 4.5

operator-sdk version: v0.17.1

kubernetes version v1.19

#### Additional context

Might be related to the fact force uses the wanted YAML as-is, without the owner injection.

**Comment by asmacdo** [comment]
After discussing with @fabianvf, it sounds like the problem is that `force: true` causes a `PUT` request. If a PUT comes through without an ownerReference present, the owner reference is removed. 

The proxy-cache needs to detect when PUT requests would result in a removed owner reference and add it back.

**Comment by fabianvf** [comment]
yeah. For the time being if using `force`/`PUT` you'll need to manually add the ownerreference to your resource to ensure it's maintained.

**Comment by flozzone** [comment]
Came across the same problem and worked around this according to @fabianvf suggestion and listing the changes here for those who are interested.

```
- name: "Get the existing deployments ownerReferences if they exist"
  community.kubernetes.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ base_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: existing_deployment

- name: "Update deployment"
  community.kubernetes.k8s:
    state: "{{ base_state }}"
    definition: "{{ lookup('template', './deployment.yaml') | from_yaml }}"
    force: yes
```

while the Deployment template `deployment.yaml` contains:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
  ownerReferences: {{ existing_deployment.resources[0].metadata.ownerReferences | default(omit) }}
spec:
  ...
```
