### ISSUE TITLE
Adding a flag for kube-rbac-proxy image

### ISSUE THREAD

**Issue by itroyano** [operator-framework/operator-sdk#5300]
#### Describe the problem you need a feature to resolve.

Hi,

When generating with Operator SDK, the image for `kube-rbac-proxy` sidecar is set to be pulled from `gcr.io`.
The Operator deployment fails when there is no access to Google Cloud,  or when images are being pulled from a private repository with no external access.

Current workaround - 

manually change the yaml and set the desired image & repo

For example from

```
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        **image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0**
```

To

```
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        **image: quay.io/brancz/kube-rbac-proxy:v0.5.0**
```

#### Describe the solution you'd like.

Provide an option to set the desired image,  during generation.

A few suggested options:

1)  A “customization yaml” / Kustomize to set the image.

Or

2) An annotation e.g. `+kubebuilder:metrics:proxy:image` or `+kubebuilder:scaffold:proxy:image`.

Or

3)  An SDK flag e.g. `operator-sdk init <args>  --rbac-proxy-image quay.io/brancz/kube-rbac-proxy:v0.5.0`.

/language go
