### ISSUE TITLE
watchDependentResources: true and selector with Helm (conflict)

### ISSUE THREAD

**Issue by jfgosselin** [operator-framework/operator-sdk#5371]
#### What did you do?

I've deployed two instance in of the Helm Operator (version 1.14.0) in the same namespace.

Helm Operator A , with the following watches.yaml:

```
- chart: helm-charts/foo
  group: foo.com
  kind: MyCR
  selector:
    matchExpressions:
    - key: release
      operator: In
      values:
      - a
  version: v1beta1
  watchDependentResources: true

```

Helm Operator B , with the following watches.yaml:

```
- chart: helm-charts/foo
  group: foo.com
  kind: MyCR
  selector:
    matchExpressions:
    - key: release
      operator: In
      values:
      - b
  version: v1beta1
  watchDependentResources: true
```

#### What did you expect to see?

- Helm install of my CR MyCR with label 'release=a', by the Helm Operator A 
- Helm install of my CR MyCR, with label 'release=b', by the Helm Operator B

#### What did you see instead? Under which circumstances?

I create a first MyCR (name:a) with the label 'release=a',  no issue , the Helm Operator A  performs the helm install.

I create a second MyCR (name:b) with the label 'release=b', but both instance of the Helm Operator are competing for the CR and I start to see these errors on both instances of the Helm Operator:

`{"level":"error","ts":1636676097.8349457,"logger":"controller.mycr-controller","msg":"Reconciler error","name":"b","namespace":"bar","error":"failed to install release: rendered manifests contain a resource that already exists. Unable to continue with install: PodDisruptionBudget \"b-my-cr\" in namespace \"bar\" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"b\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"bar\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227"}`

**BUT** ,  if I redo the same test with **watchDependentResources: false**,  everything works as expected !

Is this a bug or I didn't understand how watchDependentResources works ?

Thanks !

#### Environment

**Operator type:**

/language helm 

**Kubernetes cluster type:**

Azure

`$ operator-sdk version`

1.14.0

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"ed93e7ea8f833824d05578765c2ad3efbebbfebe", GitTreeState:"clean", BuildDate:"2021-10-21T03:31:08Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```
