### ISSUE TITLE
Not clear the usage of the flag option 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5435]
## Bug Report

I am unable to make the flag added in https://github.com/operator-framework/operator-sdk/pull/4826 works. I cannot see my extra SA added to the CSV. Am I doing something wrong? Where this option is documented? 

#### What did you do?

Following the steps to reproduce the issue scenario with [testdata/go/v3/memcached/](https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v3/memcached-operator)

1. Create the `testdata/go/v3/memcached-operator/config/rbac/service_account_pod.yaml`:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-pod-service-account
  # If we fixed here the ns then the following error is faced with operator-sdk bundle validate
  # operator-sdk bundle validate ./bundle
  # ERRO[0000] Error: Value my-pod-service-account: error validating object: metadata.namespace: Forbidden: not allowed on this type. &{map[apiVersion:v1 kind:ServiceAccount metadata:map[name:my-pod-service-account namespace:other-ns]]}
  namespace: other-ns 
```

2 - Update the Makefile to use the flag and my extra service account to the CSV:

```
.PHONY: bundle
bundle: manifests kustomize ## Generate bundle manifests and metadata, then validate generated files.
	operator-sdk generate kustomize manifests --interactive=false -q
	cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
	$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle -q --overwrite --version $(VERSION) $(BUNDLE_METADATA_OPTS) --extra-service-accounts "my-pod-service-account"
	# operator-sdk bundle validate ./bundle
````

3- Run `make bundle`  
#### What did you expect to see?

The extra SA in the CSV

#### What did you see instead? Under which circumstances?

Nothing changed 

#### Environment

`$ operator-sdk version`

1.19.0

`$ go version` 

1.16

#### Possible Solution

- The makefile has the information about the option and how to use it scaffolded via comments as we have other helpful info on this file to let user knows how to use the available options, e.g:

```
.PHONY: bundle
bundle: manifests kustomize ## Generate bundle manifests and metadata, then validate generated files.
	operator-sdk generate kustomize manifests --interactive=false -q
	cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
        # You can add the optional  --extra-service-accounts flag to the operator-sdk generate bundle command
        # to add extra ServiceAccounts to the CSV. CAVEATS: "When it is useful? Could this SA has an ns informed or not?"
        # is possible to add the extra SA that will get installed in another ns that is not the Operator ns?  
	$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle -q --overwrite --version $(VERSION) $(BUNDLE_METADATA_OPTS) --extra-service-accounts "my-pod-service-account"
	# operator-sdk bundle validate ./bundle

``` 

- The help for the command `operator-sdk generate bundle` has a better explanation with some basic examples of how to use it. See that it is not very clear: 

```
$ operator-sdk generate bundle --help
...
      --extra-service-accounts strings   Names of service accounts, outside of the operator's Deployment account, that have bindings to {Cluster}Roles that should be added to the CSV
...

What about amending it as an example as to when/why use this option? 

3 - Did we have a further and detailed explanation about this option in the SDK docs? 

#### Additional context

- When it is useful?
- Could this SA has an ns informed or not?
- Is possible to add the extra SA that will get installed in another ns that is not the Operator ns?
