### ISSUE TITLE
operator-sdk generate bundle: trim quotes

### ISSUE THREAD

**Issue by SudoBrendan** [operator-framework/operator-sdk#5499]
#### Describe the problem you need a feature to resolve.

When creating a bundle (`make bundle`), you are prompted for a few fields, including `Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required):` - this makes it look like you need to add single quotes, e.g. `'Brendan Bergen:foo@example.com'`, though, if you add these quotes, they are not trimmed and end up in the resulting YAML:

```yaml
  maintainers:
  - email: foo@example.com'
    name: '''Brendan Bergen'
```

#### Describe the solution you'd like.

Either a clearer description (`without quotes`), or automated trimming of leading/trailing quotes of the user's raw input.
