### ISSUE TITLE
prometheus role and rolebinding not created when deploying metrics

### ISSUE THREAD

**Issue by raffaelespazzoli** [operator-framework/operator-sdk#5522]
## Feature Request
This feature us about requesting the automatic creation of the needed role and rolebinding for the Prometheus service account in order for Prometheus to collect metrics from the operator.

#### Describe the problem you need a feature to resolve.
Assuming an operator is deployed in a namespace with this label: `openshift.io/cluster-monitoring="true"`
Assuming the operator declares to be metrics enabled by having this annotation in the csv: `operatorframework.io/cluster-monitoring: "true"`
Assuming an operator pod has the rbac-proxy side car to protect the metrics endpoint as per best practices,which should look like this:
```yaml
-     name: kube-rbac-proxy
      ports:
        - name: https
          containerPort: 8443
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: tls-cert
          mountPath: /etc/certs/tls
      terminationMessagePolicy: File
      image: >-
        quay.io/redhat-cop/kube-rbac-proxy@sha256:c68135620167c41e3d9f6c1d2ca1eb8fa24312b86186d09b8010656b9d25fb47
      args:
        - '--secure-listen-address=0.0.0.0:8443'
        - '--upstream=http://127.0.0.1:8080/'
        - '--logtostderr=true'
        - '--v=10'
        - '--tls-cert-file=/etc/certs/tls/tls.crt'
        - '--tls-private-key-file=/etc/certs/tls/tls.key'
```
and assuming a service monitor is deployed with the operator, then the metrics should be collected.
In reality metrics do not get collected because the Prometheus service account still needs permissions to talk to the metrics endpoint/

The role and rolebindig can be deployed as additional resources with the operator (my current workaround), but I think that OLM in this instance has enough information to create these resources automatically.
