### ISSUE TITLE
Helm charts with multiple dependencies of same type don't deploy

### ISSUE THREAD

**Issue by acceleratxr** [operator-framework/operator-sdk#5531]
#### What did you do?
Use the Operator SDK to create a Helm based operator using a chart with multiple aliased dependencies of the same image/type.
e.g.
```
apiVersion: v1
description: This is a test.
name: test
version: 1.0.0
dependencies:
- name: redis
  version: ~15.6.7
  repository: "@bitnami"
  tags:
    - cache
    - redis
  alias: cache
- name: redis
  version: ~15.6.7
  repository: "@bitnami"
  tags:
    - events
    - redis
  alias: events
- name: redis
  repository: "@bitnami"
  version: ~15.6.7
  tags:
    - dbs
    - redis
  alias: redis
```

#### What did you expect to see?

I expected to see three instances of the redis deployed.
e.g.
```
db-cache-master-0                               1/1     Running   0          28d
db-cache-replicas-0                             0/1     Pending   0          33d
db-events-master-0                              1/1     Running   0          28d
db-events-replicas-0                            0/1     Pending   0          33d
db-redis-master-0                               1/1     Running   0          28d
db-redis-replicas-0                             0/1     Pending   0          33d
```

#### What did you see instead? Under which circumstances?

After creating the custom resource only the last defined dependency in the chart file was deployed/created.

```
db-redis-master-0                           1/1     Running    0          19m
db-redis-replicas-0                         0/1     Pending    0          19m
```

#### Environment

**Operator type:**

 /language helm

**Kubernetes cluster type:**

Vanilla

`$ operator-sdk version`

operator-sdk version: "v1.13.1", commit: "1659ab58a073999463e6dcdf18bdc359a315e091", kubernetes version: "1.21", go version: "go1.16.8", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
