### ISSUE TITLE
Which operator-sdk version should I use with apiextensions.k8s.io/v1beta1

### ISSUE THREAD

**Issue by niaomingjian** [operator-framework/operator-sdk#5554]
## Type of question

 General operator-related help

#### What did you do?

I want to use helm operator in kubernetes v1.15.9 which has `apiextensions.k8s.io/v1beta1`, not `apiextensions.k8s.io/v1`.

```
[root@k8s-c1 ~]# kubectl api-versions | grep apiext
apiextensions.k8s.io/v1beta1
```
With operator-sdk v1.2.0,
`operator-sdk init` command generated crd with apiVersion `apiextensions.k8s.io/v1`.

Then I changed `apiextensions.k8s.io/v1` to `apiextensions.k8s.io/v1beta1`.
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nginxes.demo.example.com
spec:
  group: demo.example.com
  names:
    kind: Nginx
    listKind: NginxList
    plural: nginxes
    singular: nginx
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Nginx is the Schema for the nginxes API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Nginx
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of Nginx
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```
I got the following error.
```
* spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc014087bd0), Subresources:(*apiextensions.CustomResourceSubresources)(0xc012fa3eb0), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
* spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc014087bd0), Subresources:(*apiextensions.CustomResourceSubresources)(0xc012fa3eb0), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version subresources may not all be set to identical values (top-level subresources should be used instead)
```

I don't understand the meaning of the log, I guess there're different between v1 and v1beta1, then I removed `spec.versions[0].schemas` and ``spec.versions[0].`subresources` as follows:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nginxes.demo.example.com
spec:
  group: demo.example.com
  names:
    kind: Nginx
    listKind: NginxList
    plural: nginxes
    singular: nginx
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
```
This crd could be created with `make deploy`.

Though `kubectl apply -f config/samples/demo_v1alpha1_nginx.yaml` works, I got the following log in operator container.
`the server could not find the requested resource (put nginxes.demo.example.com nginx-sample)`

```
{"level":"error","ts":1645064177.8010716,"logger":"controller","msg":"Reconciler error","controller":"nginx-controller","name":"nginx-sample","namespace":"ychen","error":"the server could not find the requested resource (put nginxes.demo.example.com nginx-sample)","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90"}

{"level":"info","ts":1645064181.3993857,"logger":"helm.controller","msg":"Reconciled release","namespace":"ychen","name":"nginx-sample","apiVersion":"demo.example.com/v1alpha1","kind":"Nginx","release":"nginx-sample"}
```
At this time, I couldn't cleanup nginx resources with `kubectl delete -f config/samples/de
mo_v1alpha1_nginx.yaml`. This is also the case related to https://github.com/operator-framework/operator-sdk/issues/4383.

#### What did you expect to see?

How can I use operator sdk v1.2.0 to generate crds which can be used in kubernetes v1.15.9 which has `apiextensions.k8s.io/v1beta1`. How should I modify the crd  yaml generated by `operator-sdk init`? or which version should I use?

https://sdk.operatorframework.io/docs/overview/#kubernetes-version-compatibility
Though the doc states kubernetes version compatibility, I don't konw if I can use operator sdk v1.2.0 with kubernetes v1.15.9.

#### Environment

**Operator type:**

operator-sdk v1.2.0
/language helm

**Kubernetes cluster type:**

v1.15.9

`$ operator-sdk version`
helm-operator-v1.2.0
quay.io/operator-framework/operator-sdk:v1.2.0

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
