### ISSUE TITLE
The marker of KubeBuilder doesn't work if it is close to the code

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#5627]
#### What did you do?

The marker of KubeBuilder doesn't work if it is close to the code. And no doc announce that the marker should have the blank-line before and after them.

1. create one go operator memcached by https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/
2.  move the markers (see below), next to the `Reconcile` method in in `controllers/memcached_controller.go`.
```go
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=pods,verbs=get;list;"
```
```go
func (r *MemcachedReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
```
It should look like this:
```go
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=pods,verbs=get;list;
func (r *MemcachedReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
```
3. Run `make manifests`.

#### What did you expect to see?

Expected `role.yaml` to be created:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds/finalizers
  verbs:
  - update
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
```

#### What did you see instead? Under which circumstances?

The generated `config/rbac/role.yaml` doesn't have the apps,pods related content.

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds/finalizers
  verbs:
  - update
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds/status
  verbs:
  - get
  - patch
  - update
 ```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

N/A

`$ operator-sdk version`

`operator-sdk version: "v1.18.0-16-gb9443944", commit: "b94439446fa3790a589d9bc4ccb9171f31580cc7", kubernetes version: "v1.23", go version: "go1.17.5", GOOS: "linux", GOARCH: "amd64"`

`$ go version` (if language is Go)

N/A

`$ kubectl version`

N/A

#### Possible Solution

Add a new line after the rbac.

#### Additional context

upstream controller-tools issue: https://github.com/kubernetes-sigs/controller-tools/issues/551
downstream bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2061611
