### ISSUE TITLE
controller-manager-metrics-service warning with OCP 4.11 nightly

### ISSUE THREAD

**Issue by mbaldessari** [operator-framework/operator-sdk#5817]
#### What did you do?

Using operator-sdk v1.21 against an OCP 4.11 (4.11.0-0.nightly-2022-05-25-193227) test releases gives the following warning on the prometheus yaml:
```
make deploy
...
configmap/test-manager-config created
service/test-controller-manager-metrics-service created
W0530 15:03:10.580012  144970 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "kube-rbac-proxy" must set securityC
ontext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "kube-rbac-proxy", "manager" must set securityContext.capabilities.drop=["ALL"]), seccompProfile
 (pod or containers "kube-rbac-proxy", "manager" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/test-controller-manager created
```

The steps to create the test operator were the following:
```
operator-sdk init --domain example.com --repo github.com/example/memcached-operator
operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller
```

This warning is not observed with proper released versions of OCP (4.10 and lower). I presume this is somewhat related to https://github.com/openshift/enhancements/blob/master/enhancements/authentication/pod-security-admission-autolabeling.md

I could not find an existing bug to track this, if I missed it apologies and do close this one.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`
operator-sdk version: "v1.21.0", commit: "89d21a133750aee994476736fa9523656c793588", kubernetes version: "1.23", go version: "go1.17.10", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.17.9 linux/amd64

`$ kubectl version`

```
~/Bin/kubectl version -o=yaml
clientVersion:
  buildDate: "2022-05-24T12:26:19Z"
  compiler: gc
  gitCommit: 3ddd0f45aa91e2f30c70734b175631bec5b5825a
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.2
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-05-19T17:24:45Z"
  compiler: gc
  gitCommit: 6f5a5295923a614a4202a7ad274b38b69f9ca8c0
  gitTreeState: clean
  gitVersion: v1.23.3+ad897c4
  goVersion: go1.18
  major: "1"
  minor: "23"
  platform: linux/amd64
```
