### ISSUE TITLE
Definition of Hosts

### ISSUE THREAD

**Issue by caatclaudia** [operator-framework/operator-sdk#5827]
## Context
I'm creating a Kubernetes operator, through Ansible, that allows me to monitor the node's state from a Kubernetes Cluster, namely that allows me to copy a directory to a remote host. For this, my main.yml file executes the following commands:

```
- name: Copy files to Remote host
  hosts. <IP>
  tasks:
    - name: Copy
      become: true
      copy:
        src: ~/Downloads/files/
        dest: ~/Downloads/files/
        owner: <user>
        group: <group>        
        mode: 0777        
```

When I use these commands, the pod cannot execute the commands correctly, as it does not show output for these commands, since I didn't define any host and I can't use the ip directly in the file, am I right? 
```
make docker-build docker-push IMG=<DOCKER USER>/<REPOSITORY>:latest
make deploy IMG=<DOCKER USER>/<REPOSITORY>:latest
kubectl get deployment -n <NAMESPACE>
kubectl create -f config/samples/<FILE NAME>.yaml -n <NAMESPACE>
kubectl get pods -n <NAMESPACE>
kubectl logs --follow <POD ID> -n <NAMESPACE>
```

## Question
How can I resolve this issue? Where can I set this host? I can't find any operator directories that allow me to do this. Can I do it directly in this task file?
