### ISSUE TITLE
(/api bump) bundle validate does not fail on invalid env in deployment spec

### ISSUE THREAD

**Issue by itroyano** [operator-framework/operator-sdk#5888]
## Bug Report

Given a CSV yaml with the following spec

```
deployments:
- name: controller-manager
   spec:
   .....
     template:
     .....
       spec:
         containers:
         .....
           env:
           - name: MY_IMAGE
             image: docker.io/foo:bar
```

`operator-sdk bundle validate` is successful, despite {name. image} not being a valid `env` spec in Deployment.
it should be {name, value}.

#### What did you expect to see?

validation to fail on 

```
env:
           - name: MY_IMAGE
              image: docker.io/foo:bar
```

#### What did you see instead? Under which circumstances?

`INFO[0000] All validation tests have completed successfully`

#### Environment

N/A

`$ operator-sdk version`

v1.21.0

`$ go version` (if language is Go)

go1.18.3

`$ kubectl version`

v1.20.1-5-g76a04fc

#### Possible Solution

validate each of the nested `deployments` in CSV, as a k8s deployment object.    throw the underlying error (if any) to the validation output.
