### ISSUE TITLE
Best way to handle updating dependent resource on name change

### ISSUE THREAD

**Issue by jthomperoo** [operator-framework/operator-sdk#5926]
## Type of question

Best practices

#### What did you do?

I have an operator that has the following setup:

- Provisions a CR.
- Provisions a Pod for the CR, the Pod's name is based on a field in the CR.
- Pod ownership is set to the CR.
- When some part of the CR is updated it will then update the Pod (delete and recreate).

This works fine in all use cases except when you modify the field that defines the Pod's name, because then it has no way of linking it back to the original pod, so it will reconcile and see there is no existing Pod with the name it needs, so it will create a new one, without deleting the old one. This means that I now have two Pods rather than one.

Issue tracking this on my own project: jthomperoo/custom-pod-autoscaler-operator/issues/95

Basically my CR has a full PodTemplateSpec included in it, which allows you to manage the name of your Pod inside the template spec, like this:

```yaml
apiVersion: example/v1
kind: MyCustomResourceExample
metadata:
  name: my-custom-resource
spec:
  template:
    metadata:
      name: test-pod
    spec:
      containers:
      - name: my-container
        image: my-docker-image:latest
...
```

In the above scenario the Pod would be created with the name `test-pod`, but if I then went and updated it so it was like this:

```yaml
apiVersion: example/v1
kind: MyCustomResourceExample
metadata:
  name: my-custom-resource
spec:
  template:
    metadata:
      name: test-pod-modified
    spec:
      containers:
      - name: my-container
        image: my-docker-image:latest
...
```

Then it would end up just creating another Pod called `test-pod-modified` and leave `test-pod` hanging about.

#### What did you expect to see?

I would like to see if there's a way for me to somehow trigger reconciling the original Pod when the owner CR is affected in anyway, so then it could see that the CR field no longer matches the name that it has and it would then delete the old Pod.

#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

Vanilla

`$ operator-sdk version`

```
operator-sdk version: "v1.22.0", commit: "9e95050a94577d1f4ecbaeb6c2755a9d2c231289", kubernetes version: "1.24.1", go version: "go1.18.3", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)

```
go version go1.18.2 linux/amd64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

N/A
