### ISSUE TITLE
Validate the scorecard config file

### ISSUE THREAD

**Issue by asergienk** [operator-framework/operator-sdk#5964]
#### Describe the problem you need a feature to resolve.

CVP team would want the scorecard config.yaml file to be validated with `operator-sdk bundle validate` command.
The only two folders that are getting validated are _metadata_ and _manifests_, so, `tests/scorecard/config.yaml` is not validated.

Example:
`ocs-osd-deployer-operator-bundle-container-2.0.4-1` has an invalid config.yaml:
```
apiVersion: scorecard.operatorframework.io/v1alpha3
kind: Configuration
metadata:
  name: config
stages:
- parallel: true
  tests:
  - entrypoint:
    - scorecard-test
    - basic-check-spec
    image: quay.io/operator-framework/scorecard-test:v1.2.0
    labels:
      suite: basic
      test: basic-check-spec-test
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - scorecard-test
    - olm-bundle-validation
    image: quay.io/operator-framework/scorecard-test:v1.2.0
    labels:
      suite: olm
      test: olm-bundle-validation-test
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - scorecard-test
    - olm-crds-have-validation
    image: quay.io/operator-framework/scorecard-test:v1.2.0
    labels:
      suite: olm
      test: olm-crds-have-validation-test
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - scorecard-test
    - olm-crds-have-resources
    image: quay.io/operator-framework/scorecard-test:v1.2.0
    labels:
      suite: olm
      test: olm-crds-have-resources-test
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - scorecard-test
    - olm-spec-descriptors
    image: quay.io/operator-framework/scorecard-test:v1.2.0
    labels:
      suite: olm
      test: olm-spec-descriptors-test
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - scorecard-test
    - olm-status-descriptors
    image: quay.io/operator-framework/scorecard-test:v1.2.0
    labels:
      suite: olm
      test: olm-status-descriptors-test
    storage:
      spec:
        mountPath: {}
storage:
  spec:
    mountPath: {}
  - entrypoint:
      - /test.sh
      - test_1
    image: quay.io/apodhrad/scorecard-tests:0.9
    labels:
      cluster-product: ocp
      cluster-size: small
      phase: msp-main
      test: foo1
```

The `spec` block of the config.yaml should not contain 
```
 - entrypoint:
      - /test.sh
      - test_1
    image: quay.io/apodhrad/scorecard-tests:0.9
    labels:
      cluster-product: ocp
      cluster-size: small
      phase: msp-main
      test: foo1
 ```
 The above block should be inside `tests`. Also, the indentation of `image` and `labels` is not correct.

The error we got is:
```
--> message : while parsing a block mapping
14:14:52   in 'reader', line 69, column 3:
14:14:52        spec:
14:14:52        ^
14:14:52  expected <block end>, but found BlockEntry
14:14:52   in 'reader', line 71, column 3:
14:14:52        - entrypoint:
14:14:52        ^
```

#### Describe the solution you'd like.

CVP team would like the `operator-sdk bundle validate` command to validate `tests/scorecard/config/yaml`.
