### ISSUE TITLE
bundle validate does not fail on invalid minKubeVersion

### ISSUE THREAD

**Issue by eguzki** [operator-framework/operator-sdk#5995]
#### Describe the problem you need a feature to resolve.

`operator-sdk bundle validate` passes all tests when CSV's `spec.minKubeVersion` has invalid version like `1.21`

`spec.minKubeVersion` with value `1.21` is invalid because OLM refuses to deploy the CSV with the following **confusing** error `CSV version parsing error`:

```yaml
....
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
spec: {...}
status:
  cleanup: {}
  conditions:
    - lastTransitionTime: "2022-08-18T17:30:29Z"
      lastUpdateTime: "2022-08-18T17:30:29Z"
      message: requirements not yet checked
      phase: Pending
      reason: RequirementsUnknown
    - lastTransitionTime: "2022-08-18T17:30:29Z"
      lastUpdateTime: "2022-08-18T17:30:29Z"
      message: one or more requirements couldn't be found
      phase: Pending
      reason: RequirementsNotMet
  lastTransitionTime: "2022-08-18T17:30:29Z"
  lastUpdateTime: "2022-08-18T17:30:29Z"
  message: one or more requirements couldn't be found
  phase: Pending
  reason: RequirementsNotMet
  requirementStatus:
    - group: operators.coreos.com
      kind: ClusterServiceVersion
      message: CSV version parsing error
      name: limitador-operator.v0.3.0
      status: PresentNotSatisfied
      version: v1alpha1
```

When the field `spec.minKubeVersion` is updated to `1.21.0`, then OLM installs the CSV successfully.

#### Describe the solution you'd like.

CVP team would like the operator-sdk bundle validate command to validate CSV's `spec.minKubeVersion` when it is specified.
