### ISSUE TITLE
Add support for OpenShift's SCC

### ISSUE THREAD

**Issue by droopy4096** [operator-framework/operator-sdk#6004]
#### Describe the problem you need a feature to resolve.

as could be seen from [GitLab issue](https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/issues/762) - it is unnecessary hard to distribute operator as OLM bundle when one cannot include SCC (unlike `Roles`, `RoleBindings`, `ClusterRoles` and `ClusterRoleBindings` and `ServiceAccounts` that comprise RBAC stack in generic `k8s` cluster). 

Having additional steps negates simplicity that OLM has to offer in terms of distribution and management as now packaged operators depend on unpackaged features that require their own lifecycle management applied.

#### Describe the solution you'd like.

Allow `SecurityContextConstraints` to be part of CSV and distributed with OLM bundles.

**Comment by varshaprasad96** [comment]
OLM currently supports only specific types in which Openshift's SCC is not supported afaik. The new OLM bundle API (Rukpak) is working towards solving this. Probably @asmacdo @theishshah can provide more light on its adoption?

**Comment by asmacdo** [comment]
yes, RukPak will assist with this. a "plain bundle" does not care what the object types are.

I'm closing this issue-- could you please reopen against the operator-lifecycle-manager repo?

**Comment by camilamacedo86** [comment]
Hi @droopy4096, 

In OCP you just need additional SCC permissions if your workloads cannot run as restricted and require raising permissions, as described in: https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/1417

Note: You may can define this into the operator metadata bundle via the RBAC specified into the CSV which is used for the ServiceAccount managing the workloads. To know what is more appropriate SCC check its [documentation](https://docs.openshift.com/container-platform/4.11/authentication/managing-security-context-constraints.html) Also, for the purpose of the related changes on 4.12 see the item "If your solutions require escalated permissions" in the detailed information provided below.

Example:

```
 install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: default
```

c/c @asmacdo @varshaprasad96
