### ISSUE TITLE
Avoid to have object created when json:omitempty is defined

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#602]
When the object parsing the json or yaml custom resource is created, then it contains empty object even if the parameter `json="omitempty"` is declared or the field within the struct

Is there a trick to avoid that an object is created when it is absent from the yaml or json resource ?

```
...
	//
	Link Link `json:"omitempty"`
}

type Link struct {
	Name                string `json:"name,omitempty" yaml:"name,omitempty"`
	TargetComponentName string `json:"targetcomponentname,omitempty" yaml:"targetcomponentname,omitempty"`
	Kind                string `json:"kind,omitempty" yaml:"kind,omitempty"`
	Ref                 string `json:"ref,omitempty" yaml:"ref,omitempty"`
}
```

Yaml

```
apiVersion: component.k8s.io/v1alpha1
kind: Component
metadata:
  name: my-spring-boot-service
spec:
  services:
    - name: my-postgresql-db   # Name of the instance to be created within the namespace
      class: dh-postgresql-apb # Class or name of the service selected from the catalog
      plan: dev  
```

Result - see screenshot

![screenshot 2018-10-11 19 35 52](https://user-images.githubusercontent.com/463790/46823028-53835980-cd8d-11e8-95c0-c60f7e265065.png)
