### ISSUE TITLE
Generating Manifests and Metadata page `--kustomize` flag not available

### ISSUE THREAD

**Issue by Jaanki** [operator-framework/operator-sdk#6028]
I am trying to create a bundle for [submariner-operator](https://github.com/submariner-io/submariner-operator/) by following the official "[Generating manifests and metadata](https://v1-23-x.sdk.operatorframework.io/docs/olm-integration/generation/)" guide. The page describes about passing `--kustomize=false` to disable the interactive prompt. However, when running the command `generate kustomize manifests --kustomize=false`, it throws `an unknown flag` error.

```
$ ./bin/operator-sdk generate kustomize manifests --kustomize=false
Error: unknown flag: --kustomize
Usage:
  operator-sdk generate kustomize manifests [flags]

Examples:

  $ operator-sdk generate kustomize manifests

  Display name for the operator (required):
  > memcached-operator
  ...

  $ tree config/manifests
  config/manifests
  ├── bases
  │   └── memcached-operator.clusterserviceversion.yaml
  └── kustomization.yaml

  # After generating kustomize bases and a kustomization.yaml, you can generate a bundle or package manifests.

  # To generate a bundle:
  $ kustomize build config/manifests | operator-sdk generate bundle --version 0.0.1

  # To generate package manifests:
  $ kustomize build config/manifests | operator-sdk generate packagemanifests --version 0.0.1


Flags:
      --apis-dir string     Root directory for API type defintions
  -h, --help                help for manifests
      --input-dir string    Directory containing existing kustomize files
      --interactive         When set to false, if no kustomize base exists, an interactive command prompt will be presented to accept non-inferrable metadata
      --output-dir string   Directory to write kustomize files
      --package string      Package name
  -q, --quiet               Run in quiet mode

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution
      --verbose           Enable verbose logging

FATA[0000] unknown flag: --kustomize      
```

operator-sdk version: 1.23.0
```
$ ./bin/operator-sdk version                                       
operator-sdk version: "v1.23.0", commit: "1eaeb5adb56be05fe8cc6dd70517e441696846a4", kubernetes version: "1.24.2", go version: "go1.18.5", GOOS: "linux", GOARCH: "amd64"
```

kustomize version: 3.10.0
kubebuilder version: v3

**Comment by varshaprasad96** [comment]
@Jaanki `generate kustomize manifests` does not have `--kustomize` flag. You can use `--interactive=false` to skip the prompts. Here is more on the command: https://v1-23-x.sdk.operatorframework.io/docs/cli/operator-sdk_generate_kustomize_manifests/

**Comment by everettraven** [comment]
@Jaanki I took a look at this and using the `--interactive=false` flag this worked fine for me. I even cloned the [submariner-io/submariner-operator](https://github.com/submariner-io/submariner-operator) source. After updating the PROJECT config version to `3` instead of `3-alpha` I was able to successfully run `operator-sdk generate kustomize manifests --interactive=false`.

Since I was unable to replicate the issue, would you mind sharing all the steps to reproduce this issue? Thanks!

**Comment by Jaanki** [comment]
@everettraven hey, thanks for trying it. I have [this PR](https://github.com/submariner-io/submariner-operator/pull/2211) which updates the PROJECT config to v3 and the `operator-sdk` version to `1.23.0`. After these changes when I run `operator-sdk generate kustomize manifests --interactive=false` (there is also a `make kustomization` target for it), it runs indefinitely.

**Comment by Jaanki** [comment]
Also another doc related issue:
[kustomize files](https://v1-23-x.sdk.operatorframework.io/docs/olm-integration/generation/#kustomize-files) section in the official guide suggests that `kustomization.yaml` be under `config/manifests/bases/` but shouldn't it be under `config/manifests/`?

**Comment by Jaanki** [comment]
PROJECT config being different in these 2 scenarios might be a problem.

What I have is (generated by running `operator-sdk init --domain submariner.io --repo
github.com/submariner-io/submariner-operator` with sdk v1.21.1 (and then adding the APIs)
```
domain: submariner.io
layout:
- go.kubebuilder.io/v3
plugins:
  manifests.sdk.operatorframework.io/v2: {}
  scorecard.sdk.operatorframework.io/v2: {}
projectName: submariner-operator
repo: github.com/submariner-io/submariner-operator
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: submariner.io
  kind: Broker
  path: github.com/submariner-io/submariner-operator/api/v1alpha1
  version: v1alpha1
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: submariner.io
  kind: Submariner
  path: github.com/submariner-io/submariner-operator/api/v1alpha1
  version: v1alpha1
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: submariner.io
  kind: ServiceDiscovery
  path: github.com/submariner-io/submariner-operator/api/v1alpha1
  version: v1alpha1
version: "3"
```

and what `operator-sdk alpha config-3alpha-to-3` generates is
```
domain: submariner.io
layout: go.kubebuilder.io/v2
projectName: submariner
repo: github.com/submariner-io/submariner-operator
version: "3"
multigroup: true
plugins:
  go.sdk.operatorframework.io/v2-alpha: {}
```

`plugins` section is different.
