### ISSUE TITLE
automate user inputs in operator-sdk generate kustomize manifests

### ISSUE THREAD

**Issue by imperialguy** [operator-framework/operator-sdk#6048]
## Type of question

How to automate the user inputs in `operator-sdk generate kustomize manifests`

#### What did you do?

Ran this command from the operator dir:
```
operator-sdk generate kustomize manifests -q
```

#### What did you expect to see?

I expect to be able to automate user inputs via command-line parameters or some sort of config file

#### What did you see instead? Under which circumstances?

It asks six different questions. Below is an example of the fist question:
```
operator-sdk generate kustomize manifests -q

Display name for the operator (required):
>
```

I don't want to enter these user inputs manually. Can you provide some sorta command-line parameters?

#### Environment
Helm operator

**Kubernetes cluster type:**

Openshift or k8s. Doesn't matter. This is way before any deployment happens.

`$ operator-sdk version`

`operator-sdk version: "v1.23.0", commit: "1eaeb5adb56be05fe8cc6dd70517e441696846a4", kubernetes version: "1.24.2", go version: "go1.18.5", GOOS: "linux", GOARCH: "amd64"`

`$ go version` (if language is Go)

-na- 

This is for a helm operator

`$ kubectl version --output=yaml`

```
clientVersion:
  buildDate: "2022-08-02T07:42:46Z"
  compiler: gc
  gitCommit: 70750898e45ff4a349995b08e1d64a359e4c4880
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.4
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-08-19T00:38:59Z"
  compiler: gc
  gitCommit: 0a57f1f59bda75ea2cf13d9f3b4ac5d202134f2d
  gitTreeState: clean
  gitVersion: v1.24.0+b62823b
  goVersion: go1.18.4
  major: "1"
  minor: "24"
  platform: linux/amd64
```

#### Additional context

I just don't want to deal with those 6 user prompts. Can you provide the ability to pass those parameters via command line?
