### ISSUE TITLE
Additional status condition on CR

### ISSUE THREAD

**Issue by AllexVeldman** [operator-framework/operator-sdk#6097]
## Type of question

General operator-related help

#### What did you do?

With a recent release of Kiali, which uses the operator-sdk, I noticed an additional status condition reported in the CR:

```yaml
    - lastTransitionTime: "2022-10-17T16:16:17Z"
      message: ""
      reason: ""
      status: "False"
      type: Failure
```

Is this expected?

#### What did you expect to see?

```yaml
  status:
    conditions:
    - ansibleResult:
        changed: 19
        completion: 2022-10-17T16:16:17.070282
        failures: 0
        ok: 99
        skipped: 105
      lastTransitionTime: "2022-10-17T16:15:50Z"
      message: Awaiting next reconciliation
      reason: Successful
      status: "True"
      type: Running
    - lastTransitionTime: "2022-10-17T16:16:17Z"
      message: Last reconciliation succeeded
      reason: Successful
      status: "True"
      type: Successful
```

#### What did you see instead? Under which circumstances?

```yaml
  status:
    conditions:
    - ansibleResult:
        changed: 19
        completion: 2022-10-17T16:16:17.070282
        failures: 0
        ok: 99
        skipped: 105
      lastTransitionTime: "2022-10-17T16:15:50Z"
      message: Awaiting next reconciliation
      reason: Successful
      status: "True"
      type: Running
    - lastTransitionTime: "2022-10-17T16:16:17Z"
      message: Last reconciliation succeeded
      reason: Successful
      status: "True"
      type: Successful
    - lastTransitionTime: "2022-10-17T16:16:17Z"
      message: ""
      reason: ""
      status: "False"
      type: Failure
```

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

vanilla

`$ operator-sdk version`

I think it's 1.22.0, I'm not a Kiali dev.

`$ go version` (if language is Go)

?

`$ kubectl version`

```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

This additional condition causes the health check in argocd to mark the CR ad degraded.
related:
https://github.com/kiali/kiali/issues/5560
https://github.com/argoproj/argo-cd/pull/10995
