### ISSUE TITLE
[Helm-operator] How can we know which resource triggered the reconciliation

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-sdk#6213]
#### What did you do?

We are using a helm operator which has many dependency charts.
```
dependencies:
  - name: zookeeper
    version: 7.6.2
    repository: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    version: 4.4.0
    repository: https://kubernetes.github.io/ingress-nginx
    alias: ingressnginx
  - name: cert-manager
    version: 1.8.0
    repository: https://charts.jetstack.io/
  - name: kube-prometheus
    version: 6.13.3
    repository: https://charts.bitnami.com/bitnami
    alias: kubeprometheus
  - name: mariadb
    version: 11.0.9
    repository: https://charts.bitnami.com/bitnami
  - name: keycloak
    version: 15.1.0
    repository: https://codecentric.github.io/helm-charts
    condition: keycloak.enabled
  - name: rabbitmq
    version: 10.1.12
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: metrics-server
    version: 3.8.2
    repository: https://kubernetes-sigs.github.io/metrics-server
    alias: metricsserver
```

We observe after the operator is installed, the operator reconciliation happens continuously without any manual change in the custom resource. It also makes the post upgrade jobs repeatedly.

My guess is some dependency resources owned by the helm operator is updated by some other controllers (from the dependency charts).

Since there are tons of resources are created by the helm operator, it's hard for us to check which resource is the root cause, I am wondering if there is a method for us to know which resource triggering the helm upgrade.

#### What did you expect to see?

I expect my helm operator should be stable.

#### What did you see instead? Under which circumstances?

My helm operator keep upgrading.

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:**

`$ operator-sdk version`
helm-operator v1.11

`$ go version` (if language is Go)

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.13-3+cbc10c94808907", GitCommit:"cbc10c9480890724de6cfadc4c95aaa8d81cabdd", GitTreeState:"clean", BuildDate:"2022-06-08T09:56:13Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.13-3+cbc10c94808907", GitCommit:"cbc10c9480890724de6cfadc4c95aaa8d81cabdd", GitTreeState:"clean", BuildDate:"2022-06-08T09:53:55Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
