### ISSUE TITLE
annotation on deployment not present in bundle

### ISSUE THREAD

**Issue by maskarb** [operator-framework/operator-sdk#6249]
## Bug Report

<!--
Thanks for filing an issue! Before hitting the button, please answer these questions.
Fill in as much of the template below as you can. If you leave out information, we can't help you as well.

Note: Make sure to first check the prerequisites that can be found in the main README.md file!
-->

#### What did you do?

<!-- A clear and concise description of the steps you took (or insert a code snippet). -->

We have added an annotation to our Deployment in `manager.yaml` (see [here](https://github.com/project-koku/koku-metrics-operator/blob/main/config/manager/manager.yaml#L15-L17)):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: operator
  labels:
    control-plane: controller-manager
  annotations:
    ignore-check.kube-linter.io/minimum-three-replicas: This deployment uses
      1 pod as currently it supports only a single controller-manager
spec:
```

When we generate the bundle, this annotation is no longer present in the ClusterServiceVersion:
```
      deployments:
      - label:
          app: koku-metrics-operator
          control-plane: controller-manager
        name: koku-metrics-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: koku-metrics-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                app: koku-metrics-operator
                control-plane: controller-manager
```

During bundling, we run 
```
$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle --overwrite --version $(VERSION) $(BUNDLE_METADATA_OPTS)
```

The output of the `kustomize build config/manifests` is attached in [test_manifest.yaml.txt](https://github.com/operator-framework/operator-sdk/files/10428773/test_manifest.yaml.txt). This output still contains the Deployment annotation that we added.


#### What did you expect to see?

<!-- A clear and concise description of what you expected to happen (or insert a code snippet). -->
We expect to see the Deployment annotation contained in the ClusterServiceVersion.

#### What did you see instead? Under which circumstances?

<!-- A clear and concise description of what ACTUALLY happened (or insert a code snippet). -->

#### Environment

**Operator type:**

<!-- Uncomment one or more of the following lines corresponding to the language of the operator type -->

/language go
<!-- /language ansible -->
<!-- /language helm -->

**Kubernetes cluster type:**

"OpenShift"

`$ operator-sdk version`

operator-sdk version: "v1.25.3", commit: "5779ad7c8901c1e48cf324cec430c26212684b45", kubernetes version: "v1.25.0", go version: "go1.19.3", GOOS: "darwin", GOARCH: "arm64"

`$ go version` (if language is Go)

go version go1.16.15 darwin/arm64

`$ kubectl version`

 kubectl version --output=yaml                                                                                                                                                                                                                                     
clientVersion:
  buildDate: "2022-12-08T19:51:43Z"
  compiler: gc
  gitCommit: b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d
  gitTreeState: clean
  gitVersion: v1.26.0
  goVersion: go1.19.4
  major: "1"
  minor: "26"
  platform: darwin/arm64
kustomizeVersion: v4.5.7

 oc version                                                                                                                                                                                                                                                        
Client Version: 4.10.47


#### Possible Solution

<!-- Only if you have suggestions on a fix for the bug -->

#### Additional context

<!-- Add any other context about the problem here. -->
