### ISSUE TITLE
Adding Owner References for Existing Resources

### ISSUE THREAD

**Issue by laurieaw63** [operator-framework/operator-sdk#6318]
In this example I believe "to_be_owned.namespace" in the when clause supposed to be to_be_owned.metadata.namespace
```
 when: to_be_owned.namespace is not defined or to_be_owned.namespace != owning_resource.namespace
```

```
_ name: Patch resource with owner annotation
  when: to_be_owned.namespace is not defined or to_be_owned.namespace != owning_resource.namespace
  kubernetes.core.k8s:
    state: present
    resource_definition:
      apiVersion: "{{ to_be_owned.apiVersion }}"
      kind: "{{ to_be_owned.kind }}"
      metadata:
        name: "{{ to_be_owned.metadata.name }}"
        namespace: "{{ to_be_owned.metadata.namespace | default(omit)}}"
        annotations:
          operator-sdk/primary-resource: "{{ owning_resource.namespace }}/{{ owning_resource.name }}"
          operator-sdk/primary-resource-type: "{{ owning_resource.kind }}.{{ owning_resource.apiVersion.split('/')[0] }}"
```
