### ISSUE TITLE
Go Operator Unstructured Values for Helm Charts

### ISSUE THREAD

**Issue by DreamingRaven** [operator-framework/operator-sdk#6347]
## Bug Report

Hey I am having issues defining an API struct with an unstructured component. This is primarily for handling in arbitrary overrides the user may give to things like helm charts. As we don't necessarily know or want to know all possible overrides.

#### What did you do?

I defined an API resource like so:

```go
package v1alpha1

import (
  metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

//+kubebuilder:validation:Optional

type AkSpec struct {

  //+kubebuilder:validation:Schemaless

  Values map[string]interface{} `json:"values,omitempty"`
  // Values unstructured.Unstructured `json:"values,omitempty"`
}

// AkStatus defines the observed state of Ak
type AkStatus struct {}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status

// Ak is the Schema for the aks API
type Ak struct {
  metav1.TypeMeta   `json:",inline"`
  metav1.ObjectMeta `json:"metadata,omitempty"`

  Spec   AkSpec   `json:"spec,omitempty"`
  Status AkStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// AkList contains a list of Ak
type AkList struct {
  metav1.TypeMeta `json:",inline"`
  metav1.ListMeta `json:"metadata,omitempty"`
  Items           []Ak `json:"items"`
}

func init() {
  SchemeBuilder.Register(&Ak{}, &AkList{})
}

```
Then I make / generate the manifests.

#### What did you expect to see?

A generic un-validated schema to be generated.

#### What did you see instead? Under which circumstances?

```
make[1]: Entering directory '/home/archer/git/authentik-manager/operator'
test -s /home/archer/git/authentik-manager/operator/bin/controller-gen || GOBIN=/home/archer/git/authentik-manager/operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
/home/archer/git/authentik-manager/operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
gitlab.com/GeorgeRaven/authentik-manager/operator/api/v1alpha1:-: name requested for invalid type: interface{}
gitlab.com/GeorgeRaven/authentik-manager/operator/api/v1alpha1:-: invalid map value type: interface{}
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make[1]: *** [Makefile:94: generate] Error 1
make[1]: Leaving directory '/home/archer/git/authentik-manager/operator'
make: *** [Makefile:95: build] Error 2
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

Minikube, and Vanilla

`$ operator-sdk version`

operator-sdk version: "unknown", commit: "unknown", kubernetes version: "unknown", go version: "go1.19.4", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

1.20

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7

#### Additional context

I am trying to create a generic un-validated unstructured filed to hold values for helm charts applied by the Go based operator. As a sort of hybrid operator without using the hybrid operator plugin.

**Comment by everettraven** [comment]
@DreamingRaven Would you mind sharing the CR that you used that caused this error?

**Comment by DreamingRaven** [comment]
Hey @everettraven, sure, I was only testing with some gaff CR, I can create a more elaborate CR if necessary. I am just trying to create a CRD that accepts a CR which is both unstructured and unvalidated in its ``values`` field that could contain ``map[string]interface{}`` types for helm actions.

```yaml
apiVersion: akm.goauthentik.io/v1alpha1
kind: Ak
metadata:
  labels:
    app.kubernetes.io/name: ak
    app.kubernetes.io/instance: ak-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: ak-sample
  namespace: auth
spec:
  values:
    nothing: nothing
```

**Comment by DreamingRaven** [comment]
Here is a much more concrete example where the values would point to a much more complex set of values:
```yaml
apiVersion: akm.goauthentik.io/v1alpha1
kind: Ak
metadata:
  labels:
    app.kubernetes.io/name: ak
    app.kubernetes.io/instance: ak-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: ak-sample
  namespace: auth
spec:
  values:
    global:
      domain:
        # the base domain which should be used for authentication
        base: example.org
        # the domain where authentik ingress will listen
        full: auth.example.org
        # the domain where the ldap ingress will listen
        ldap: ldap.example.org
      admin:
        # the administrative user you want in ldap and the entire SSO
        # ATM does very little
        name: somebody
        email: somebody@pm.me
    
    # this assumes external SMTP server that has username and password
    # creds you can log in with.
    # from=the user all emails are going to come from
    # host=the location of SMTP server to authenticate to
    # username=the user to authenticate to SMTP server with
    smtp:
      # enable me to allow users to reset their own passwords etc
      # if diabled also disabled smtp password file env value
      enabled: false
      username: somebody@example.org
      port: 587
      host: smtp.gmail.com
      from: noreply@example.org
    
    secret:
      generate: true
      randLength: 30
      # you probably dont want to change this name as you will have to change
      # it everywhere in subcharts
      name: auth
    
    ingress:
      name: auth
      enable: true
      clusterIssuer: letsencrypt-staging # must match cert-manager cluster issuer
      maxBodySize: 32M
      authCertSecret: authentik-cert
      ldapCertSecret: ldap-cert
      # HTTP STRICT TRANSPORT SECURITY
      # hsts:
      #   enable: false
      tls:
        enable: true
    
    # postgresql DEPENDENCY CHART overrides
    # https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#parameters
    postgresql:
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 15
      # nameOverride: pgsql
      fullnameOverride: postgres
      primary:
        persistence:
          enabled: false
      readReplicas:
        persistence:
          enabled: false
      global:
        postgresql:
          service:
            ports:
              postgresql: 5432
          auth:
            existingSecret: auth
            database: authentik
            username: authentik
            secretKeys:
              adminPasswordKey: postgresPassword
              userPasswordKey: postgresUserPassword
              replicationPasswordKey: postgresReplicationPassword
      # diagnosticMode:
      #   enabled: true
      #   command: ["sleep"]
      #   args: ["infinity"]
    
    redis:
      fullnameOverride: redis
      image:
        registry: docker.io
        repository: bitnami/redis
        tag: "7.0"
      architecture: replication
      auth:
        enabled: true
        sentinel: false
        existingSecret: auth
        existingSecretPasswordKey: redisPassword
      replicaCount: 5
      master:
        service:
          ports:
            redis: 6379
        persistence:
          enabled: false
          size: 8Gi
      replica:
        persistence:
          enabled: false
          size: 8Gi
    
    ldap:
      enabled: false
      persistence:
        enabled: false
        name: ldap-pvc
        accessMode: ReadWriteOnce
        size: 8Gi
        mountPath: /data
        # mountPath: /bitnami/openldap
      deployment:
        imagePullPolicy: Always
        image: "docker.io/nitnelave/lldap:v0.4.1-alpine"
        name: ldap
        replicas: 1
        env: # statically defined environment variables can be as many as desired
        - name: LDAP_ADMIN_USERNAME
          value: "admin"
      secrets:
        secretName: auth
        basePath: /secrets
        lookup:
        - env: LLDAP_JWT_SECRET
          key: authJwtToken
        - env: LLDAP_LDAP_USER_PASS
          key: ldapAdminPassword
      service:
        name: ldap
      ports:
      - name: ldap
        containerPort: 3890
        servicePort: 3890
        protocol: TCP
      - name: http
        containerPort: 17170
        servicePort: 80
        protocol: TCP
      labels:
      - key: type
        value: auth
      - key: app
        value: ldap
    
    authentik:
      enabled: true
      # domain: <BASE_DOMAIN>
      config:
        name: authentik-config
        path: /config
        file: configuration.yml
        noteFile: /notification.txt
        generate: true
      # authentik expects its secrets as files in the same directory
      # so we tell kube where to get secret data and where to put it
      secrets:
        basePath: /secrets
        lookup:
        # this lookup will mount a secret data to a file basePath/files
        # this will also then create an env variable pointing to this secret file
        # thus we have no env variables with secrets in them but files are permed
        # https://www.authentik.com/integration/kubernetes/secrets/
        - key: postgresUserPassword
          file: postgresql-pass
          env: AUTHENTIK_POSTGRESQL__PASSWORD
        - key: redisPassword
          file: redis-pass
          env: AUTHENTIK_REDIS__PASSWORD
        - key: authJwtToken
          file: secret-key
          env: AUTHENTIK_SECRET_KEY
        # - key: sessionSecret
        #   file: SESSION_SECRET
        #   env: AUTHENTIK_SESSION_SECRET_FILE
        # - key: postgresauthentikPassword
        #   file: STORAGE_PASSWORD
        #   env: AUTHENTIK_STORAGE_POSTGRES_PASSWORD_FILE
        # - key: authStorageEncryptionKey
        #   file: STORAGE_ENCRYPTION_KEY
        #   env: AUTHENTIK_STORAGE_ENCRYPTION_KEY_FILE
        # - key: ldapAdminPassword
        #   file: LDAP_PASSWORD
        #   env: AUTHENTIK_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
        - key: smtpPassword
          file: smtp-pass
          env: AUTHENTIK_EMAIL__PASSWORD
      deployment:
        imagePullPolicy: Always
        image: "ghcr.io/goauthentik/server:2023.2.2"
        name: authentik
        replicas: 3
        env: # statically defined environment variables can be as many as desired
        - name: AUTHENTIK_LISTERN__HTTP
          value: 0.0.0.0:9000
        - name: AUTHENTIK_LISTERN__HTTPS
          value: 0.0.0.0:9443
        - name: AUTHENTIK_LISTERN__LDAP
          value: 0.0.0.0:3389
        - name: AUTHENTIK_LISTERN__LDAPS
          value: 0.0.0.0:6636
        - name: AUTHENTIK_LISTERN__METRICS
          value: 0.0.0.0:9300
        - name: AUTHENTIK_LISTERN__DEBUG
          value: 0.0.0.0:9900
        - name: AUTHENTIK_LOG_LEVEL
          value: info
        - name: AUTHENTIK_DISABLE_UPDATE_CHECK
          value: false
        - name: AUTHENTIK_ERROR_REPORTING
          value: false
        - name: AUTHENTIK_AVATARS
          value: gravatar
        - name: AUTHENTIK_DEFAULT_USER_CHANGE_NAME
          value: true
        - name: AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL
          value: true
        - name: AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME
          value: true
        - name: AUTHENTIK_GDPR_COMPLIANCE
          value: true
        - name: AUTHENTIK_DEFAULT_TOKEN_LENGTH
          value: 60
        - name: AUTHENTIK_IMPERSONATION
          value: true
        # - name: AUTHENTIK_FOOTER_LINKS
        #   value: '[{"name": "Link Name","href":"https://goauthentik.io"}]'
        - name: AUTHENTIK_WEB__WORKERS
          value: 2
        - name: AUTHENTIK_WEB__THREADS
          value: 2
      service:
        name: authentik
      ports:
      - name: http
        containerPort: 9000
        servicePort: 80
        protocol: TCP
      - name: https
        containerPort: 9443
        servicePort: 443
        protocol: TCP
      - name: ldap
        containerPort: 3389
        servicePort: 389
        protocol: TCP
      - name: ldaps
        containerPort: 6636
        servicePort: 636
        protocol: TCP
      - name: metrics
        containerPort: 9300
        servicePort: 300
        protocol: TCP
      - name: debug
        containerPort: 9900
        servicePort: 900
        protocol: TCP
      labels:
      - key: type
        value: auth
      - key: app
        value: authentik
      # list blueprint configmap names in this namespace to automount to worker instances
      # https://goauthentik.io/developer-docs/blueprints/
      blueprints: []
      # - name: some-default-blueprint
      #   configMap:
      #     name: example-custom-blueprint-configmap
      #     key: my-default-blueprint
      #   dest: /blueprints/default/some-default-blueprint.yaml
    
    # Authentik Manager
    akm:
      operator:
        # you probably dont want AKM to be loaded by this chart but we leave this option here for you
        # you should probably load the operator seperately and without this chart installed so it can
        # manage everything
        enabled: false
    
    # postgres admin dashboard
    pgadmin:
      enable: false
      persistence:
        enable: false
        name: pgadmin-pvc
        accessMode: ReadWriteOnce
        size: 4Gi
        mountPath: /var/lib/pgadmin/data
      deployment:
        imagePullPolicy: Always
        image: "docker.io/dpage/pgadmin4:latest"
        name: pgadmin
        replicas: 1
        env: # statically defined environment variables can be as many as desired
        - name: PGADMIN_LISTEN_PORT
          value: 80
      secrets:
        secretName: auth
        lookup:
        - env: PGADMIN_DEFAULT_PASSWORD
          key: pgAdminPassword
      service:
        name: pgadmin
      ports:
      - name: http-port
        containerPort: 80
        servicePort: 80
        protocol: TCP
      labels:
      - key: type
        value: auth
      - key: app
        value: pgadmin
      # OPTIONAL VOLUMES mount at /var/lib/pgadmin

```
