### ISSUE TITLE
operator-sdk 1.28.0 - Problem generating CRD with corev1.ResourceRequirements type

### ISSUE THREAD

**Issue by gaohoward** [operator-framework/operator-sdk#6382]
#### What did you do?

We are upgrading our operator-sdk to 1.28.0 (from 1.25.0). In our CRD types we have a field that is of corev1.ResourceRequirements type. 

#### What did you expect to see?

The generated CRD should be deployed without error.

#### What did you see instead? Under which circumstances?

When we deploy the generated CRDs to kubernetes it cannot pass
the schema validation. The error message is look like
`Error from server (Invalid): error when creating "deploy.yaml": CustomResourceDefinition.apiextensions.k8s.io "activemqartemises.broker.amq.io" is invalid: [spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[deploymentPlan].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set`

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

minikube v1.29.0 on Fedora 37

`$ operator-sdk version`

perator-sdk version: "v1.28.0", commit: "484013d1865c35df2bc5dfea0ab6ea6b434adefa", kubernetes version: "1.26.0", go version: "go1.19.6", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.19.3 linux/amd64

`$ kubectl version`

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution
No solution so far but it looks like the resourceRequirements.Claims field (https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2356) causes the problem. This field is generated the following piece in the CRD
```
                      claims:
                        description: "Claims lists the names of resources, defined in spec.resourceClaims, that are used by this container. \n This is an alpha field and requires enabling the DynamicResourceAllocation feature gate. \n This field is immutable."
                        items:
                          description: ResourceClaim references one entry in PodSpec.ResourceClaims.
                          properties:
                            name:
                              description: Name must match the name of one entry in pod.spec.resourceClaims of the Pod where this field is used. It makes that resource available inside a container.
                              type: string
                          required:
                          - name
                          type: object
                        type: array
                        x-kubernetes-list-type: set
```
and if I remove x-kubernetes-list-type: set manually and the CRD can be deployed without error.
