### ISSUE TITLE
After changing the label of the custom resource, reconcile continues

### ISSUE THREAD

**Issue by egenii007** [operator-framework/operator-sdk#6395]
#### What did you do?

1.  I create watches.yaml with selector

```yaml
  selector:
    matchExpressions:
      - {key: type, operator: In, values: [first]}
```

2. playbook changes the label of the custom resource
```yaml
  - name: Change custom resource label
    kubernetes.core.k8s_json_patch:
      kind: Somekind
      namespace: somenamespace
      name: "{{ ansible_operator_meta.name }}"
      patch:
        - op: replace
          path: /metadata/labels/type
          value: second
```

I change the label of a custom resource, but anyway reconcile in progress

#### What did you expect to see?

disable reconcile after changing custom resource label

#### What did you see instead? Under which circumstances?

reconcile in progress

#### Environment

**Operator type:**

 /language ansible

**Kubernetes cluster type:**

k8s

`$ operator-sdk version`

ansible-operator:v1.26.0

`$ go version` (if language is Go)

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0"
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0"

#### Additional context

if i restart operator then everything works as expected

perhaps the operator is caching a custom resource ?
