### ISSUE TITLE
How to change playbook inventory for each custom resource

### ISSUE THREAD

**Issue by yhidai** [operator-framework/operator-sdk#6439]
## Type of question

Best practices
How to implement a specific feature

#### What did you do?

I am trying to create an operator with Ansible Operator.
I'm trying to define Redis information in a custom resource, create a VM with an IaaS provider based on that data, and set up Redis.

#### What did you expect to see?

I would like to change the host that runs Ansible playbooks for each custom resource processed by the reconcile loop.
Is there such functionality in Ansible Operator?

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

vanilla

`$ operator-sdk version`

```sh
operator-sdk version: "v1.23.0", commit: "1eaeb5adb56be05fe8cc6dd70517e441696846a4", kubernetes version: "1.24.2", go version: "go1.18.5", GOOS: "linux", GOARCH: "amd64"
```

`$ kubectl version`

```sh
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by varshaprasad96** [comment]
This issue was brought up in the community meeting. We would need inputs from the ansible operator folks to get more idea on this. Tagging @everettraven for help in following this up.

**Comment by yhidai** [comment]
@varshaprasad96
Thank you for your reply.  I ask him.

@everettraven
Thank you for answering my question.

>  Could you elaborate a bit more on what you are attempting to do? It sounds like on reconciliation of a CR you are wanting to:
>
> - Create VM with an IaaS provider
> - Run a playbook against (on?) that VM to configure Redis on the VM
> Does that sound right?

Yes, that's right.
I would like to know if the following use cases are possible with Ansible Operator.

- The Operator reconcile the following custom resources.
```yaml
apiVersion: redis.example.com
kind: Redis
metadata:
  name: redis-standalone
spec:
  host:
    name: redis-standalone
  redis:
    version: 7.0.10
    memory: 16GiB
```
- Operator creates a VM in CloudStack with hostname of spec.host.name in custom resource.
- Once the VM is created, the Operator will record the IPAddress in the CR.
```yaml
apiVersion: redis.example.com
kind: Redis
metadata:
  name: redis-standalone
spec:
  host:
    name: redis-standalone
    ipAddress: 10.41.0.38
  redis:
    version: 7.0.10
    memory: 16GiB
```
- Operator executes a playbook to build Redis specified in spec.redis.version for VM of spec.host.ipAddress in CR
