### ISSUE TITLE
During reconciliation client.Update call consider default GOLang values as not initialized

### ISSUE THREAD

**Issue by SevcikMichal** [operator-framework/operator-sdk#6461]
#### What did you do?

Created a custom resource based on a CRD definition generated from a type struct using provided make commands (`make generate manifests`).
Here is a snippet of the type with one of the fields important for this issue (`Preload bool`):
```go
type WebComponentSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// The URI from which the module shall be accessed. The actual module is cached by the controller to improve performance and avoid CORS issues.
	// +kubebuilder:validation:Format=url
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	ModuleUri string `json:"module-uri"`

	// The modules are not preloaded by default but only when navigating to some of the subpaths mentioned in the 'navigation' list. Setting this property to true ensures that the module is loaded when the application starts.
	// +kubebuilder:default=true
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	Preload bool `json:"preload,omitempty"`
}
```
The Preload field is then represented like this in the generated crd.yaml:
```yaml
preload:
  default: true
  description: The modules are not preloaded by default but only when navigating to some of the subpaths mentioned in the 'navigation' list. Setting this property to true ensures that the module is loaded when the application starts.
  type: boolean
```
I created a CR with this value explicitly set to false as seen here (removed not interesting fields to make it as small as possible):
```yaml
apiVersion: microfrontend.michalsevcik.dev/v1alpha1
kind: WebComponent
metadata: 
  name: msevcik-ambulance-ufe
spec:   
  module-uri: http://msevcik-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  preload: false
```
During the reconcile function I add the finalizers and update the resource:
```go
        if !controllerutil.ContainsFinalizer(webComponent, webComponentFinalizer) {
		log.Info("Adding Finalizer for WebComponent.")
		if ok := controllerutil.AddFinalizer(webComponent, webComponentFinalizer); !ok {
			log.Error(err, "Failed to add finalizer into the custom resource!")
			return ctrl.Result{Requeue: true}, nil
		}

		if err = r.Update(ctx, webComponent); err != nil {
			log.Error(err, "Failed to update custom resource to add finalizer!")
			return ctrl.Result{}, err
		}

		return ctrl.Result{}, nil
	}
```
#### What did you expect to see?

I expected the finalizers field to be added to the CR and no change in the spec part of the CR.

#### What did you see instead? Under which circumstances?

CRs spec was updated and preload was changed to true.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

docker-desktop

`$ operator-sdk version`

operator-sdk version: "v1.29.0", commit: "78c564319585c0c348d1d7d9bbfeed1098fab006", kubernetes version: "v1.26.0", go version: "go1.20.4", GOOS: "darwin", GOARCH: "arm64"

`$ go version` (if language is Go)

go version go1.20.4 darwin/arm64

`$ kubectl version`

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.4

#### Possible Solution

I have tested this as well with an int value where I set the `// +kubebuilder:default=1`.
Since go int default is 0 I explicitly set the value in CR to 0.
After update call the int value was updated to 1 as per kubebuilder default even though it was explicitly set to 0 during apply.

I am not sure what the solution could be there but as workaround I defined the bool value as a pointer (`*bool`) so the default value in go is nil instead of false. I am not sure if this is an expected behavior or not.

#### Additional context

It is hard for me to currently pinpoint where the problem could be maybe I should have created this issue in controller-runtime or maybe it is even problem in Kubernetes implementation of docker-desktop. However I did not stumble upon same issue during my google searches therefore I hope it will serve someone that might face the same issue in future.
