### ISSUE TITLE
Helm operators generated by operator-sdk lack spec.relatedImages and thus fail RH certification

### ISSUE THREAD

**Issue by tkrishtop** [operator-framework/operator-sdk#6482]
## Bug Report

Helm operators generated with operator-sdk are missing the spec.relatedImages section, which causes them to fail RH certification.

#### What did you do?

Here is an example: [A partner is attempting to certify a helm-operator generated with operator-sdk](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2475). The generation was done following [the official operator-sdk guide](https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/).

The logs from the certification Tekton pipeline are as follows:
```
[digest-pinning : verify-related-images] 
["registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:da5d5061dbc2ec5082cf14b6c600fb5400b83cf91d7ccebfa80680a238d275db", 
"prod.harbor.xxx.digital/loadcore/xxx-websocket-service@sha256:f8e3e5c8f849795bbe385e24c5f0321aabac2782d24e7b422c4dee47186fd637"]++ jq length references.json
[digest-pinning : verify-related-images] 
+ REFERENCE_COUNT=2
[digest-pinning : verify-related-images] 
++ find /workspace/source/operators/xxx-websocket-service/0.1.9 -name '*clusterserviceversion.yaml' -o -name '*clusterserviceversion.yml'
[digest-pinning : verify-related-images] 
+ CSVFILE=/workspace/source/operators/xxx-websocket-service/0.1.9/manifests/xxx-websocket-service.clusterserviceversion.yaml
[digest-pinning : verify-related-images] 
++ yq -e '.spec.relatedImages | length' /workspace/source/operators/xxx-websocket-service/0.1.9/manifests/xxx-websocket-service.clusterserviceversion.yaml
[digest-pinning : verify-related-images] 
+ RELATED_IMAGE_COUNT=0
[digest-pinning : verify-related-images] + [[ 0 -ge 2 ]]
[digest-pinning : verify-related-images] + echo 'The relatedImages section does not exist or is missing images.'
```

As a result of the missing spec.relatedImages section, the partner is unable to RH-certify the helm-operator generated with operator-sdk and has to unpack the bundle and manually introduce the changes.

#### What did you expect to see?

Ideally, operators generated with operator-sdk should pass the certification smoothly. 

#### What did you see instead? Under which circumstances?

As a result of the missing spec.relatedImages section, the partner is unable to RH-certify the helm-operator generated with operator-sdk and has to unpack the bundle and manually introduce the changes.

#### Environment

**Operator type:**

/language helm

`$ operator-sdk version`

1.30.0

#### Possible Solution

I'm not certain about the precise technical solution, but I can work on implementing this change if we agree that this change is something that has to be done.

**Comment by tkrishtop** [comment]
I see that the `relatedImages` are already present in the template code.

https://github.com/operator-framework/api/blob/master/crds/operators.coreos.com_clusterserviceversions.yaml#L5034-L5046

```
                relatedImages:
                  description: List any related images, or other container images that your Operator might require to perform their functions. This list should also include operand images as well. All image references should be specified by digest (SHA) and not by tag. This field is only used during catalog creation and plays no part in cluster runtime.
                  type: array
                  items:
                    type: object
                    required:
                      - image
                      - name
                    properties:
                      image:
                        type: string
                      name:
                        type: string
```

It seems like we only need to understand how to request them during the operator generation.
