### ISSUE TITLE
Kustomize depricating "bases" and "patchesStrategicMerge"

### ISSUE THREAD

**Issue by christianh814** [operator-framework/operator-sdk#6531]
Running `kustomize build config/test` on a Go operator returns the following 

```
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

This is the newer syntax (that does the same thing)

```yaml
resources:
- ../crd
- ../rbac
- ../manager


patches:
  - path: manager_auth_proxy_patch.yaml
```
