### ISSUE TITLE
Ansible based operator can not read task variable value from CR object spec 

### ISSUE THREAD

**Issue by fmuyassarov** [operator-framework/operator-sdk#6623]
#### What did you do?

I have created Ansible based operator and created some tasks in roles/MY_ROLE/tasks/main.yml as below example:
```YAML
---
# tasks file for PluginConfig
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: nri-plugins
    repo_url: "https://containers.github.io/nri-plugins"

- name: Deploy topology-aware
  kubernetes.core.helm:
    name: topology-aware
    chart_ref: nri-plugins/nri-resource-policy-topology-aware
    release_namespace: default
  when: pluginName == "topology-aware"

- name: Deploy balloons
  kubernetes.core.helm:
    name: balloons
    chart_ref: nri-plugins/nri-resource-policy-balloons
    release_namespace: default
  when: pluginName == "balloons"
```

the variable name is being passed from within the custom resource `PluginConfig` spec that the operator is watching:

```YAML
apiVersion: apps.nri.io/v1alpha1
kind: PluginConfig
metadata:
  labels:
    app.kubernetes.io/name: pluginconfig
    app.kubernetes.io/instance: pluginconfig-sample
    app.kubernetes.io/part-of: nri-plugins-unified-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nri-plugins-unified-operator
  name: pluginconfig-sample
spec:
  pluginName: balloons
  # TODO(user): Add fields here
```

When the `pluginName` CR instance is created controller starts running r`oles/MY_ROLE/tasks/main.yml` nicely but it is failing to fetch the value of the `pluginName` variable from pluginconfig-sample `spec.pluginName` and playbook is crashing with `pluginName` variable undefined. 

```YAML
status:
  conditions:
  - lastTransitionTime: "2023-11-08T12:35:37Z"
    message: ""
    reason: ""
    status: "False"
    type: Successful
  - ansibleResult:
      changed: 0
      completion: 2023-11-08T12:35:39.192224
      failures: 1
      ok: 1
      skipped: 0
    lastTransitionTime: "2023-11-08T12:35:39Z"
    message: |
      The conditional check 'pluginName == "topology-aware"' failed. The error was: error while evaluating conditional (pluginName == "topology-aware"): 'pluginName' is undefined. 'pluginName' is undefined

      The error appears to be in '/opt/ansible/roles/pluginconfig/tasks/main.yml': line 8, column 3, but may
      be elsewhere in the file depending on the exact syntax problem.

      The offending line appears to be:


      - name: Deploy topology-aware
        ^ here
    reason: Failed
    status: "False"
    type: Failure
  - lastTransitionTime: "2023-11-08T12:35:39Z"
    message: Running reconciliation
    reason: Running
    status: "True"
    type: Running
```

#### What did you expect to see?

Ansible Playbook variable value inherited from the CR object spec.

#### What did you see instead? Under which circumstances?

`pluginName` variable being undefined and not getting its value from CR object `spec.pluginName`.
#### Environment

**Operator type:**
/language ansible

**Kubernetes cluster type:**

vanilla

`$ operator-sdk version`
`operator-sdk version: "v1.32.0", commit: "4dcbbe343b29d325fd8a14cc60366335298b40a3", kubernetes version: "1.26.0", go version: "go1.19.13", GOOS: "linux", GOARCH: "amd64"`

`$ kubectl version`
```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4
```

#### Additional
Example reference where replicas value being controlled from the CR and passed down to the Ansible task: https://sdk.operatorframework.io/docs/building-operators/ansible/tutorial/#modify-the-manager
