### ISSUE TITLE
Include CSV annotations to pass Preflight's RequiredAnnotations test

### ISSUE THREAD

**Issue by ramperher** [operator-framework/operator-sdk#6790]
#### Describe the problem you need a feature to resolve.

Latest versions of [openshift-preflight](https://github.com/redhat-openshift-ecosystem/openshift-preflight/tree/main) includes a new test, called RequiredAnnotations, where preflight checks if operator's CSV includes the following [infrastructure features annotations](https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html?elqTrackId=de407b752ff6427abbe9e59d03179a88&elq=d0d351ac2c234a9daafa3437745d0b86&elqaid=4115&elqat=1&elqCampaignId=2538#osdk-csv-annotations-infra_osdk-generating-csvs):

```
# Example CSV with infrastructure feature annotations
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
```

If any of these annotations is not present, this preflight test fails, impacting in Red Hat's operator certification.

The problem is, operators built with operator-sdk doesn't include these annotations by default, so they must be added manually.

#### Describe the solution you'd like.

Include these 7 annotations in the CSV, at least with a default value (`false`), so that users can modify them if required. In this way, preflight's RequiredAnnotations test would successfully pass.
