### ISSUE TITLE
Validate complains about metadata/dependencies.yaml

### ISSUE THREAD

**Issue by dcraigmv** [operator-framework/operator-sdk#6818]
#### What did you do?

Create bundle/metadata/dependencies.yaml as follows:  
```yaml
dependencies:
  - type: olm.package
    value:
      packageName: myotheroperator
      version: "0.0.1-alpha.1"
```

run `operator-sdk bundle validate ./bundle`

#### What did you expect to see?

Validation pass

#### What did you see instead? Under which circumstances?

FATA[0000] error loading objs in directory: unable to decode object: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{"dependencies":[{"type":"olm.package","value":{"packageName":"myotheroperator","version":"0.0.1-alpha.1"}}]}'

#### Environment

**Operator type:**

/language ansible - For ansible operator related bugs, please create the issue in https://github.com/operator-framework/ansible-operator-plugins

**Kubernetes cluster type:**
OpenShift 4.15

`$ operator-sdk version`
operator-sdk version: v1.31.0

`$ go version` (if language is Go)

`$ kubectl version`
