### ISSUE TITLE
Missing Cert-Manager Resources while `generate bundle` 

### ISSUE THREAD

**Issue by Manvi1203** [operator-framework/operator-sdk#6873]
#### What did you do?
Tried generating an operator bundle for helm-chart. Steps to reproduce the error:
- Download the Helm Chart (https://cloud.google.com/alloydb/omni/docs/deploy-kubernetes#install)
- operator-sdk generate bundle

#### What did you expect to see?
Expected all the resources from `templates/` to be included in the generated manifests.

#### What did you see instead? Under which circumstances?
When generating an Operator Bundle from a Helm chart using operator-sdk generate bundle, certain custom resources (those for cert-manager) are not automatically included. 
List of custom resources not included in the generated bundle:
- In templates/cluster-crs.yaml 
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: alloydbomni-selfsigned-cluster-issuer
spec:
  selfSigned: {}
```
  
- In templates/fleet-webhooks.yaml
```
apiVersion: [cert-manager.io/v1](http://cert-manager.io/v1)
kind: Certificate
metadata:
  name: fleet-serving-cert
  namespace: alloydb-omni-system
spec:
  dnsNames:
  - fleet-webhook-service.alloydb-omni-system.svc
  - fleet-webhook-service.alloydb-omni-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: fleet-selfsigned-issuer
  secretName: fleet-webhook-server-cert
```

```
apiVersion: [cert-manager.io/v1](http://cert-manager.io/v1)
kind: Issuer
metadata:
  name: fleet-selfsigned-issuer
  namespace: alloydb-omni-system
spec:
  selfSigned: {}
```
- In templates/local-webhooks.yaml
```
apiVersion: [cert-manager.io/v1](http://cert-manager.io/v1)
kind: Certificate
metadata:
  name: local-serving-cert
  namespace: alloydb-omni-system
spec:
  dnsNames:
  - local-webhook-service.alloydb-omni-system.svc
  - local-webhook-service.alloydb-omni-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: local-selfsigned-issuer
  secretName: local-webhook-server-cert
```

#### Environment

**Operator type:**

language helm

**Kubernetes cluster type:**

`$ operator-sdk version`
4.12.69

`$ kubectl version`
1.25.16
