### ISSUE TITLE
Example CRD version looks hardcoded to v1alpha1

### ISSUE THREAD

**Issue by Brian-Williams** [operator-framework/operator-sdk#689]
## Bug Report

I believe the CRD example always has a version of v1alpha1 even though the CR example correctly uses the requested version.

**What did you do?**

Made a v1beta1 API, but it creates v1alpha CRD regardless of version.

command:
```
operator-sdk add api --api-version=app.example.com/v1beta1 --kind=AppService >> README.md 2>&1
```

**What did you expect to see?**
v1beta1 version in example CRD.

**What did you see instead? Under which circumstances?**
v1alpha1

Creates a CRD with version [v1alpha1](https://github.com/Brian-Williams/app-operator/commit/31a3b94d0ce1d6a3a0760ea9181f48b1ef1c7836#diff-73c3c0ca7097da7de63c106cefb35899R13).

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appservices.app.example.com
spec:
  group: app.example.com
  names:
    kind: AppService
    listKind: AppServiceList
    plural: appservices
    singular: appservice
  scope: Namespaced
  version: v1alpha1 # <--
```

You can see the full list of operations in the commits [here](https://github.com/Brian-Williams/app-operator/commits/master). I also pushed the output into the [README.md](https://raw.githubusercontent.com/Brian-Williams/app-operator/master/README.md).

**Environment**
* operator-sdk version:

```
operator-sdk --version
operator-sdk version 0.0.7+git
```

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:18:13Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Are you writing your operator in ansible or go?
go

**Possible Solution**

Quick fix: Add note to *_crd.yaml to "ensure version(s) match" like we put "# Add fields here" in *_cr.yaml.

Complete fix: Use correct version in CRD example
