### ISSUE TITLE
Passing configuration values to the operator

### ISSUE THREAD

**Issue by mazzy89** [operator-framework/operator-sdk#714]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

I'm asking about community best practices

## Question

**What did you do?**
What I'd like to understand is how to pass to the operator variables that are used to set up it.

For instance the operator needs an `API KEY`. Which is the best way to do it? It is not clear to me.

**Environment**
* operator-sdk version:

  v0.1.0

**Comment by shawn-hurley** [comment]
I think there are probably two ways to do this.

1. Environment variables, for something like an API KEY that you will probably want to keep as a secret and then you can just add the secret to the operator as environment variables. 

2. Command line args. Most folks use https://godoc.org/github.com/spf13/pflag. I think this should be for options i.e logging verbosity.

@hasbro17 thoughts?

**Comment by mazzy89** [comment]
I'm interested to the 1.

I'm not sure in which of the steps I would have to pass it from this guide my https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#1-run-as-a-deployment-inside-the-cluster

**Comment by shawn-hurley** [comment]
You would need to edit the deployment in `deploy/operator.yaml` file.

This doc might help: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

I think what you will need to do is in the pod spec to add the:
```yaml
...
spec:
  template:
    spec:
      containers:
        - name: ....
          ... 
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: apiKey
```

Does that help?
