### ISSUE TITLE
Provide RBAC manifests

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#79]
We need to generate a basic RBAC role and rolebinding. To start with it can be just set to access all resources. Later on we can instruct the user on setting the permissions according to the resources that are being Watched and have Actions taken on them.

For e.g:

```YAML
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: memcached-operator
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-memcached-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: memcached-operator
  apiGroup: rbac.authorization.k8s.io

```
