### ISSUE TITLE
Discuss the behavior of operator-sdk build

### ISSUE THREAD

**Issue by fanminshi** [operator-framework/operator-sdk#84]
Currently, `operator-sdk build $IMAGE` builds a docker image of the operator using `$IMAGE` and creates `./tmp/operator.yaml` that contains `crd` and `deployment` details. What if I call the `operator-sdk build $IMAGE2` again? What should the behavior be?

The current behavior:

`./tmp/operator.yaml` will be overwritten. Suppose that the user has made some changes to it previously, those will be gone.

Proposed behavior 1:

Calling `operator-sdk build $IMAGE2` again doesn't do anything because `./tmp/operator.yaml` exists already. However, since `$IMAGE2` is changed, `./tmp/operator.yaml` should be updated with `$IMAGE2` instead.

Proposed behavior 2:

Calling `operator-sdk build $IMAGE2` only update the `image` field of `./tmp/operator.yaml`.

Proposed behavior 3:

Calling  first `operator-sdk build $IMAGE1` creates a one time template `./tmp/operator_tmpl.yaml` file. We expect user to copy and paste from template for any customized modification. Subsequent calls on `operator-sdk build $IMAGE-X` doesn't create any new manifests.

cc/ @hasbro17 @hongchaodeng

**Comment by fiftoine** [comment]
Case : 
When developing operators locally with minikube docker env (eval $(minikube docker-env)), the operator image can't be pulled because of the imagePullPolicy set to Always.

A solution is to change the imagePullPolicy to IfNotPresent.

The `operator-sdk build $IMAGE` should allow to customize the generated operator.yaml containing a specific value for imagePullPolicy (I supppose it could do it for the full operator.yaml)

Proposed behavior 4:

Having different templates for the operator.yaml having profile awareness passed to the `operator-sdk build $IMAGE`. Something like `operator-sdk build $IMAGE -p dev`. It would then use the template operator-dev.yaml

One could then customize operator-${PROFILE}.yaml and use it depending on the environment it's build on.

**Comment by fanminshi** [comment]
@nicksantamaria we are aware of this issue. To circumvent this issue for now, you can copy the first operator.yaml after the first build to a new `<your>.yaml`. Then use `<your>.yaml` for any further operator deployment.

**Comment by theishshah** [comment]
Sample of how this can work:
`operator-sdk build <image>` will behave as is.
`operator-sdk build <image> <path_to_template>` will build the operator.yaml with a custom template
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.ProjectName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{.ProjectName}}
  template:
    metadata:
      labels:
        name: {{.ProjectName}}
    spec:
      containers:
        - name: {{.ProjectName}}
          image: {{.Image}}
          ports:
          - containerPort: {{.MetricsPort}}
            name: {{.MetricsPortName}}
          command:
          - {{.ProjectName}}
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: {{.OperatorNameEnv}}
              value: "{{.ProjectName}}"
```
A template can look like the above, with whatever custom information that needs to be added can be placed in that template file and the operator.yaml will be generated from that

**Comment by fanminshi** [comment]
@theishshah how are values `{{.ProjectName}}`, `{{.Image}}`, and so forth being obtained? How are those those values being pass-in to the templates ?

**Comment by fanminshi** [comment]
@theishshah Suppose that the user wants to add additional custom fields to their templates.

e.g:
```yaml
  ...
  env:
  - name: <Your ENV Var>
    value: <Your value>
```

How do they achieve that with your proposed plan?
